#!/usr/bin/env python3
"""Year 4 KS2 draft specs. Loaded by emit-ks2-drafts.py."""


def t(**kwargs):
    return kwargs


def mis(misconception: str, why: str, instead: str) -> dict:
    return {"misconception": misconception, "why": why, "instead": instead}


def chk(prompt: str, looksLike: str, notYet: str, nudge: str) -> dict:
    return {"prompt": prompt, "looksLike": looksLike, "notYet": notYet, "nudge": nudge}


YEAR4 = [
        t(
            id="y4-thousands",
            year=4,
            strand="Number and place value",
            title="Thousands, hundreds, tens and ones",
            shortTitle="4-digit place value",
            summary="Know what each digit is worth in a four-digit number, including splitting it in more than one way.",
            statutoryOutcomes=[
                "Recognise the place value of each digit in a four-digit number (1,000s, 100s, 10s, and 1s)",
                "Order and compare numbers beyond 1,000",
            ],
            readyToProgress=["4NPV-1", "4NPV-2"],
            whyThisMatters="4,058 is four thousands, no hundreds, five tens and eight ones. Written methods in Year 4 fall apart if that picture is fuzzy.",
            inPlainEnglish="A thousand is ten hundreds. In 4,058 the 4 is 4,000, the 0 holds the hundreds place, the 5 is 50, the 8 is 8. You can also think of 4,058 as 40 hundreds and 58 ones.",
            howSchoolTeachesIt="School uses place-value charts, sliders, and Gattegno-style charts. They compose and decompose with standard and non-standard partitions, and they place numbers on a line to 10,000.",
            sayThis=[
                {"prompt": "What is the 5 worth in 4,058?", "listenFor": "50, or five tens."},
                "Make 4,058 with thousands and hundreds in two different ways.",
                "Which is greater, 4,058 or 4,508?",
            ],
            avoidThis=[
                "Reading 4,058 as 458 because the 0 ‘does nothing’.",
                "Jumping to rounding before they can name each place.",
            ],
            misconceptions=[
                mis("They write four thousand and fifty-eight as 400058 or 458.", "The zeros as place-holders are not solid.", "Build it on a chart: thousands | hundreds | tens | ones."),
                mis("They say 4,508 is smaller than 4,058 because 08 looks small.", "They compared from the right.", "Compare thousands first, then hundreds."),
            ],
            youAreReadyWhen="You can name the worth of each digit in a four-digit number and split it at least two ways.",
            householdItems=["Place-value columns drawn on paper (Th | H | T | O)", "Digit scraps 0–9", "Optional: four objects to stand for thousands if you treat a cup as 100"],
            setup="Draw Th H T O columns. Write 4,058.",
            activityTitle="Build, split, compare",
            steps=[
                "Place digits 4, 0, 5, 8. Say each worth.",
                "Trade 1 thousand for 10 hundreds. Is it still 4,058?",
                "Write 4,508 beside it. Compare hundreds.",
                "Put both on a 0–10,000 line marked in thousands.",
            ],
            check=[
                chk("Worth of 7 in 7,203?", "7,000.", "7 or 70.", "The thousands place."),
                chk("Show 2,040 with a zero hundreds.", "2 thousands, 0 hundreds, 4 tens, 0 ones.", "240.", "Keep the empty hundreds box."),
                chk("Order 3,090, 3,900, 3,009.", "3,009; 3,090; 3,900.", "Sorted as if extra zeros do not matter.", "Hundreds decide after thousands match."),
            ],
            stretch="How many hundreds in 4,058?",
        ),
        t(
            id="y4-count-6-7-9-25-1000",
            year=4,
            strand="Number and place value",
            title="Counting in 6s, 7s, 9s, 25s and 1,000s",
            shortTitle="Count in 6, 7, 9, 25, 1,000",
            summary="Keep equal jumps of 6, 7, 9, 25 or 1,000, linking them to tables and to 1,000 more or less.",
            prerequisites=["y4-thousands"],
            statutoryOutcomes=[
                "Count in multiples of 6, 7, 9, 25 and 1,000",
                "Find 1,000 more or less than a given number",
            ],
            whyThisMatters="These jumps feed the remaining tables and make 25 and 1,000 feel like units, not scary numbers.",
            inPlainEnglish="Counting in 25s is 0, 25, 50, 75, 100… Four 25s make 100. Counting in 1,000s changes only the thousands digit, until you hit 9,000 + 1,000.",
            howSchoolTeachesIt="School uses number lines, 100-squares for 25s, and place-value charts for ±1,000. 6, 7 and 9 sit with times-table practice, not as a separate chant.",
            sayThis=["Jump 25 four times from 0. Where are you?", "1,000 more than 3,406?", "9, 18, 27… what is the jump?"],
            avoidThis=["Mixing jump size without saying so.", "Treating +1,000 as ‘add a zero’."],
            misconceptions=[
                mis("They count 25, 50, 75, 90.", "They slipped into 15 or 10 at the end.", "Keep a 25-object story: a quarter of 100 each time."),
                mis("3,406 + 1,000 becomes 3,506 or 13,406.", "They added 100, or they glued a 1 on the front.", "Only the thousands digit moves: 3 thousands become 4 thousands."),
            ],
            youAreReadyWhen="You can hop 25s through 100 and add or subtract 1,000 from a four-digit number.",
            householdItems=["Paper number line", "Four identical objects to stand for 25s if you call each ‘a quarter of 100’"],
            setup="Tonight: 25s and ±1,000. Touch 6s/7s/9s only as a short chant with fingers if time.",
            activityTitle="Quarters of 100, then a thousand hop",
            steps=[
                "Mark 0, 25, 50, 75, 100.",
                "Write 3,406. Add 1,000. Subtract 1,000. Check you return.",
                "Try 9,050 + 1,000.",
                "Optional: 6, 12, 18, 24 with six fingers-as-groups.",
            ],
            check=[
                chk("Four jumps of 25 from 0.", "100.", "80 or 90.", "Four quarters of 100."),
                chk("1,000 less than 4,070.", "3,070.", "4,060 or 3,070 written 470.", "Thousands digit 4 → 3."),
                chk("Next 9 after 27.", "36.", "35 or 45.", "Equal jumps of 9."),
            ],
            stretch="Count backwards through 0 in 1s later this week — that is the next pack.",
        ),
        t(
            id="y4-negative-numbers",
            year=4,
            strand="Number and place value",
            title="Counting through zero",
            shortTitle="Negative numbers",
            summary="Count backwards through 0 into negative numbers, using a line, not a ‘minus means take away’ mix-up.",
            prerequisites=["y4-thousands"],
            statutoryOutcomes=["Count backwards through 0 to include negative numbers"],
            whyThisMatters="Weather, lifts and later coordinates all use numbers below zero. Year 4 is the number line, not calculating with negatives yet.",
            inPlainEnglish="After 1, 0, comes −1, −2, −3. Negative is a direction on the line, the other side of zero. −3 is less than −1.",
            howSchoolTeachesIt="School uses a number line that crosses 0, temperature, and sometimes a lift going below ground. They compare positions, and they do not yet do 3 − 5 as a written algorithm unless the line is there.",
            sayThis=["What comes before 0 when we count back?", "Which is colder, −1 or −4?", "Show 2, then 0, then −2 on the line."],
            avoidThis=["Saying negative numbers are ‘like subtracting’ with no line.", "Teaching two minuses make a plus — that is later."],
            misconceptions=[
                mis("They think −8 is greater than −2 because 8 is greater.", "They compared size of the numerals.", "Further left on the line is smaller. −8 is left of −2."),
                mis("They write 0 − 1 as 0, or skip 0.", "Zero feels like a stop, not a crossing.", "Say ‘through zero’ while a finger crosses the 0 mark."),
            ],
            youAreReadyWhen="You can count back through 0 and say which of two negative numbers is smaller using a line.",
            householdItems=["A long paper line marked −5 to 5", "A toy or button to hop"],
            setup="Draw −5 to 5 with 0 in the middle. Make the negative marks as clear as the positive ones.",
            activityTitle="Hop through zero",
            steps=[
                "Start at 3. Hop back one at a time through 0 to −3. Name each landing.",
                "Compare −1 and −4. Which is further left?",
                "Tell a temperature story: 2 degrees, falls 5 degrees. Land at −3.",
                "Count forwards from −4 to 2.",
            ],
            check=[
                chk("Count back 4 from 2.", "−2.", "2, or 0.", "2, 1, 0, −1, −2."),
                chk("Which is smaller: −5 or −1?", "−5.", "−1.", "Further left."),
                chk("What sits equally far from 0 as 3, the other way?", "−3.", "0 or 6.", "Mirror through zero."),
            ],
            stretch="A lift: floor 2 down 4 floors. Name the landing if ground is 0 and basement is negative.",
        ),
        t(
            id="y4-rounding",
            year=4,
            strand="Number and place value",
            title="Round to the nearest 10, 100 or 1,000",
            shortTitle="Rounding",
            summary="Place a number on a line and see which multiple of 10, 100 or 1,000 it sits nearer to.",
            prerequisites=["y4-thousands"],
            statutoryOutcomes=["Round any number to the nearest 10, 100 or 1,000"],
            readyToProgress=["4NPV-3"],
            whyThisMatters="Rounding is how children check whether a calculation is in the right ballpark. It is a location skill, not a ‘5 goes up’ chant first.",
            inPlainEnglish="368 to the nearest 10 is 370 because it sits nearer 370 than 360. To the nearest 100 it is 400. A 5 on the knife-edge usually rounds up in school’s convention.",
            howSchoolTeachesIt="School puts the number on a line between two multiples, marks the midpoint, and asks which end is closer. The ‘5 or more, round up’ rule comes after the picture.",
            sayThis=["Which tens is 368 between?", "Is it past halfway?", "Now zoom out: which hundreds?"],
            avoidThis=["Only a rhyme, with no line.", "Rounding each digit separately."],
            misconceptions=[
                mis("They round 368 to 300 because they look at the hundreds digit 3.", "They rounded the wrong place.", "For nearest 10, look at the ones. For nearest 100, look at the tens."),
                mis("They always round down to be ‘safe’.", "They mix rounding with estimating low.", "Halfway and beyond go to the higher multiple in this convention."),
            ],
            youAreReadyWhen="You can round a four-digit number to 10, 100 and 1,000 using a line or a midpoint.",
            householdItems=["Paper lines: one 360–370, one 300–400, one 0–1,000 marked in hundreds"],
            setup="Write 368. Draw the three zooms of line.",
            activityTitle="Zoom the line",
            steps=[
                "Place 368 between 360 and 370. Halfway is 365. 368 is past it → 370.",
                "Place 368 between 300 and 400. Halfway 350. Past it → 400.",
                "Place 3,680 between 3,000 and 4,000 for nearest 1,000.",
                "Try 350 to the nearest 100 (midpoint convention: 400).",
            ],
            check=[
                chk("74 to the nearest 10.", "70.", "80 or 74.", "74 is nearer 70 than 80; halfway would be 75."),
                chk("368 to the nearest 100.", "400.", "370 or 300.", "Past 350."),
                chk("2,499 to the nearest 1,000.", "2,000.", "2,500 or 3,000.", "Halfway to 3,000 is 2,500. 2,499 is just before."),
            ],
            stretch="A measure: 368 ml of juice — about how many 100 ml glasses?",
        ),
        t(
            id="y4-roman-to-100",
            year=4,
            strand="Number and place value",
            title="Roman numerals to 100",
            shortTitle="Roman numerals to C",
            summary="Read Roman numerals to 100 (I to C) and notice they have no place-value zero.",
            statutoryOutcomes=["Read Roman numerals to 100 (I to C) and know that over time, the numeral system changed to include the concept of 0 and place value"],
            whyThisMatters="Clocks and dates still use them. The contrast with 0 and place value is the real mathematical point.",
            inPlainEnglish="I=1, V=5, X=10, L=50, C=100. You add when a smaller comes after a larger (VI=6). You subtract when a smaller comes before (IV=4). There is no symbol for zero, and XIV is not ‘places’ like 14.",
            howSchoolTeachesIt="School puts them in a historical story: different cultures wrote numbers differently; place value and 0 were a later idea. They read clock faces and simple dates.",
            sayThis=["What is X? What is C?", "Why is 14 XIV, not XIIII, on many clocks?", "Where would you put a zero if this system had one?"],
            avoidThis=["Long subtraction strings (XCIV…) as the first diet.", "Saying Roman is ‘wrong’ — it is different."],
            misconceptions=[
                mis("They read VI as 4 because V and I are ‘take away’.", "The order rule is reversed.", "Small before large subtracts. Small after large adds. VI is 6."),
                mis("They think X means 1 because it looks like a cross or like 10 in tally but written once.", "Symbol values are not yet attached.", "Keep a tiny key card: I V X L C."),
            ],
            youAreReadyWhen="You can read I–XII on a clock and a number such as XL (40) or LX (60) with a key in reach.",
            householdItems=["A key card: I=1 V=5 X=10 L=50 C=100", "An analogue clock if you have one", "Scrap paper"],
            setup="Write the key card. Sit with a clock if possible.",
            activityTitle="Clock, then tens",
            steps=[
                "Read 1–12 in Roman on the clock.",
                "Build 20 as XX, 30 as XXX, 40 as XL (10 before 50).",
                "Build 60 as LX. Compare XL and LX on a line.",
                "Write today’s day of the month if it is 1–30 in Roman for fun, checking the key.",
            ],
            check=[
                chk("XIV.", "14.", "16 or 15.", "X + (V − I) wait: X + IV = 10 + 4."),
                chk("XL.", "40.", "60 or 10.", "10 before 50."),
                chk("Why isn’t 10 written as VV?", "Convention uses X; also the system is not place value.", "They say it is allowed.", "Each symbol has a usual role. 10 is X."),
            ],
            stretch="Year numbers such as MM are Year 5. Stop at C tonight.",
        ),
        t(
            id="y4-written-add-subtract-4-digit",
            year=4,
            strand="Addition and subtraction",
            title="Written add and subtract with 4-digit numbers",
            shortTitle="Written +/− 4-digit",
            summary="The same exchanging method as Year 3, now with thousands, plus a rough estimate to check.",
            prerequisites=["y4-thousands", "y4-rounding"],
            statutoryOutcomes=[
                "Add and subtract numbers with up to 4 digits using the formal written methods of columnar addition and subtraction where appropriate",
                "Estimate and use inverse operations to check answers to a calculation",
            ],
            whyThisMatters="Fluency with the compact layout frees attention for two-step problems. The estimate catches lining-up errors.",
            inPlainEnglish="Line thousands under thousands. Exchange 10 in a column for 1 in the next. After 5,738 + 2,196, check with 5,700 + 2,200. Subtraction can check by adding back.",
            howSchoolTeachesIt="School compact method with exchanging, not ‘borrow and pay back’. They choose mental vs written. Inverse check is part of the lesson, not an extra.",
            sayThis=["Estimate first. What should this be near?", "Ones under ones?", "How could adding check this subtract?"],
            avoidThis=["Skipping the estimate.", "The old pay-back rhyme if school says exchange."],
            misconceptions=[
                mis("They line 2196 under 5738 starting from the left.", "Reading direction fought place value.", "Right-align the ones. The thousands will sit correctly."),
                mis("They ‘check’ by repeating the same method and copying a mistake.", "A true check uses estimate or inverse.", "Add the answer to the subtracted part, or round both numbers."),
            ],
            youAreReadyWhen="You can complete one 4-digit add and one subtract with exchange, and you can say why the estimate fits.",
            householdItems=["Column grid on paper", "Pencil"],
            setup="Write 5,738 + 2,196. Estimate 5,700 + 2,200 first.",
            activityTitle="Estimate, write, inverse",
            steps=[
                "Say the estimate (~7,900).",
                "Add with exchanges. Compare to the estimate.",
                "Subtract 4,002 − 1,637 with exchanges.",
                "Add your subtract answer to 1,637. Do you get 4,002?",
            ],
            check=[
                chk("Estimate 5,738 + 2,196.", "About 7,900 (or 8,000).", "7,000 with no reason, or 57 + 21.", "Round to hundreds or thousands."),
                chk("Why exchange 12 ones?", "10 ones make 1 ten; 2 ones stay.", "Because the teacher said carry.", "Name the exchange."),
                chk("If 4,002 − 1,637 = 2,365, what add checks it?", "2,365 + 1,637.", "4,002 + 1,637.", "Add the two parts to make the whole."),
            ],
            stretch="A two-step story: a club has 2,450 points, gains 1,380, then loses 905.",
        ),
        t(
            id="y4-tables-to-12",
            year=4,
            strand="Multiplication and division",
            title="Multiplication facts to 12 × 12",
            shortTitle="Tables to 12 × 12",
            summary="Recall tables to 12 × 12, and the matching division facts, using known facts and patterns, not only a chant.",
            prerequisites=["y4-count-6-7-9-25-1000"],
            statutoryOutcomes=["Recall multiplication and division facts for multiplication tables up to 12 × 12"],
            readyToProgress=["4NF-1"],
            whyThisMatters="The Year 4 multiplication tables check is a government snapshot. Home should still be pictured and unhurried. Fluency is availability, not speed-shame.",
            inPlainEnglish="12 × 7 is 84. That one fact also gives 7 × 12, 84 ÷ 12 and 84 ÷ 7. You can derive 12 × 7 from 10 × 7 and 2 × 7.",
            howSchoolTeachesIt="School uses arrays, derived facts (double 6s to get 12s), and short practice. They still allow thinking time. Division facts live with the same family.",
            sayThis=["If 6 × 8 is 48, what is 12 × 8?", "How many 7s in 56?", "Do not race. Use a fact you know."],
            avoidThis=["Timed tests as the only diet.", "Shame if they still derive rather than instant-recall."],
            misconceptions=[
                mis("They know 7 × 8 but not 8 × 7.", "Commutativity is not yet trusted.", "Turn the array: 7 rows of 8 is the same rectangle as 8 rows of 7."),
                mis("They chant 7 × 8 = 54 (mixing 6×9 or 9×6).", "Near-facts collide.", "Build 7 × 8 as 5×8 and 2×8: 40+16=56."),
            ],
            youAreReadyWhen="You can derive or recall a missing 6, 7, 8, 9 or 12 fact and state a matching division.",
            householdItems=["24–36 small objects for one array", "Paper"],
            setup="Pick one awkward table tonight, such as 7s. Objects for 7 × 8.",
            activityTitle="One family, derived not shouted",
            steps=[
                "Build 7 × 8 as 7 rows of 8. Count 56.",
                "Write the family: 7×8, 8×7, 56÷7, 56÷8.",
                "Derive 12×8 from 10×8 and 2×8.",
                "Cover one fact and ask it again without rebuilding if they can.",
            ],
            check=[
                chk("6 × 7.", "42.", "36 or 48.", "6×5=30, 6×2=12, join; or 7×6 same rectangle."),
                chk("72 ÷ 8.", "9.", "8 or 64.", "How many 8s in 72? 8×9=72."),
                chk("12 × 7 from 10 × 7 and 2 × 7.", "84.", "70 or 27.", "70+14."),
            ],
            stretch="What is 11 × 7 as 10 × 7 plus one more 7?",
        ),
        t(
            id="y4-factor-pairs",
            year=4,
            strand="Multiplication and division",
            title="Factor pairs and multiplying three numbers",
            shortTitle="Factor pairs",
            summary="Find pairs that multiply to a number, and use commutativity so 2 × 3 × 4 can be grouped helpfully.",
            prerequisites=["y4-tables-to-12"],
            statutoryOutcomes=[
                "Use place value, known and derived facts to multiply and divide mentally, including: multiplying by 0 and 1; dividing by 1; multiplying together 3 numbers",
                "Recognise and use factor pairs and commutativity in mental calculations",
            ],
            readyToProgress=["4MD-2"],
            whyThisMatters="Factor pairs later unlock fractions and primes. Grouping 4 × 12 × 5 as 4 × 5 × 12 is a mental superpower.",
            inPlainEnglish="Factors of 12 are pairs: 1 and 12, 2 and 6, 3 and 4. Multiplying by 1 leaves a number. Multiplying by 0 gives 0. 2 × 3 × 4 can be (2×3)×4 or 2×(3×4).",
            howSchoolTeachesIt="School uses arrays that split, factor bugs, and regrouping. They are careful with ×0, which children find rude.",
            sayThis=["Pairs that make 12?", "Can we multiply in a different order to make this easier?", "What is 9 × 0? What is 9 × 1?"],
            avoidThis=["Listing factors in a random scatter with duplicates and misses.", "Saying ×0 is ‘nothing happened’ — the product is 0, which is something."],
            misconceptions=[
                mis("They think 4 is a factor of 12 but 3 is not, because they only see even splits.", "Odd factors feel illegal.", "3 rows of 4 is still a rectangle of 12."),
                mis("They think 2 × 3 × 4 depends on order for the answer.", "They mix order with the product.", "Build (2×3)×4 and 2×(3×4) with objects."),
            ],
            youAreReadyWhen="You can list factor pairs of a small number and regroup three one-digit factors.",
            householdItems=["12 objects", "Paper"],
            setup="Twelve objects. Tonight 12 is the star.",
            activityTitle="All the rectangles of 12",
            steps=[
                "Make 1×12, 2×6, 3×4 rectangles. Write the pairs.",
                "Compute 2 × 3 × 4 by grouping 2×4=8 then ×3, and 3×4=12 then ×2.",
                "Ask 12 × 1 and 12 × 0.",
                "Try factor pairs of 18 if energy remains.",
            ],
            check=[
                chk("Factor pairs of 10.", "1×10 and 2×5.", "Only 2×5, or 3×3.", "Include 1 and itself."),
                chk("5 × 0.", "0.", "5.", "Zero groups of 5, or 5 groups of 0."),
                chk("4 × 5 × 3, grouping 4×5 first.", "60.", "20 or 12.", "20 × 3."),
            ],
            stretch="Which pair helps 4 × 12 × 5 mentally? (4×5)×12.",
        ),
        t(
            id="y4-short-multiplication",
            year=4,
            strand="Multiplication and division",
            title="Multiply 2-digit and 3-digit numbers by a 1-digit number",
            shortTitle="Short multiplication",
            summary="Use an expanded or compact written method for TO × O and HTO × O, built from tens/hundreds and ones.",
            prerequisites=["y4-tables-to-12", "y4-thousands"],
            statutoryOutcomes=["Multiply two-digit and three-digit numbers by a one-digit number using formal written layout"],
            readyToProgress=["4MD-3"],
            whyThisMatters="This is school’s short multiplication. If the child only ‘adds a zero’, they will mis-place extra tens.",
            inPlainEnglish="146 × 3 is 100×3, 40×3 and 6×3, then join. The compact layout does those multiplies in columns, exchanging when a column hits 10 or more.",
            howSchoolTeachesIt="Grid / area model, then expanded, then compact short multiplication. Distributive law is named in teacher-speak; parents can say ‘split, multiply, join’.",
            sayThis=["Split 146 into hundreds, tens, ones. Multiply each by 3.", "Where does the extra ten from 6×3=18 go?", "Does the estimate fit?"],
            avoidThis=["Compact method with no split first.", "‘Just add a zero’ for the tens, with no ‘those are tens’."],
            misconceptions=[
                mis("146 × 3 as 1×3, 4×3, 6×3 written 3 12 18 as 31218.", "Digits not values.", "1 hundred × 3 is 300."),
                mis("They forget to add the exchanged ten into the next column.", "Exchange is still a Year 3 leftover wobble.", "Say the extra ten out loud as you write it."),
            ],
            youAreReadyWhen="You can work 23 × 6 and 146 × 3 with a split or a compact layout you can explain.",
            householdItems=["Paper", "Optional objects for 23 × 4 as a warm-up array of tens and ones"],
            setup="Estimate 146 × 3 ≈ 150 × 3 = 450. Then split.",
            activityTitle="Grid then compact",
            steps=[
                "Grid: 100, 40, 6 along the top; ×3 down the side. Fill 300, 120, 18. Total.",
                "Write the same as 300+120+18.",
                "If they are ready, compact columns, ones first.",
                "A second example: 37 × 5.",
            ],
            check=[
                chk("23 × 4.", "92.", "86 or 27.", "20×4=80, 3×4=12."),
                chk("146 × 3.", "438.", "318 or 4380.", "300+120+18."),
                chk("Estimate 37 × 5.", "About 200 (40×5) or 150 (30×5).", "37 or 5.", "Round 37."),
            ],
            stretch="201 × 4. Watch the 0 tens.",
        ),
        t(
            id="y4-remainders",
            year=4,
            strand="Multiplication and division",
            title="Division with remainders",
            shortTitle="Remainders",
            summary="When it will not share equally, name the leftover and decide whether it is leftover objects, another group, or ‘not enough’.",
            prerequisites=["y4-tables-to-12"],
            statutoryOutcomes=["Solve problems involving multiplying and adding, including … integer scaling problems and harder correspondence problems"],
            readyToProgress=["4NF-2"],
            whyThisMatters="Year 5 short division needs remainders that mean something in the story, not just ‘r 2’ as wallpaper.",
            inPlainEnglish="17 ÷ 5 is 3 each with 2 left over, if we cannot split objects. If the story is cars holding 5, you may need a 4th car. The remainder’s meaning follows the story.",
            howSchoolTeachesIt="School uses objects, then short division with a remainder. They ask ‘what does the leftover mean?’ before they write r.",
            sayThis=["How many equal groups? What is left?", "Does this leftover need another group in the story?", "Can we split leftover objects tonight? (Usually no.)"],
            avoidThis=["Always writing r without a sentence.", "Decimals remaining in Year 4 as the default."],
            misconceptions=[
                mis("They force 17 ÷ 5 = 4 because they round up every time.", "They mixed the ‘another car’ story with every story.", "Ask whether leftover people still need a seat."),
                mis("They write the remainder larger than the divisor (17 ÷ 5 = 2 r 7).", "They subtracted wrong.", "Leftover must be less than 5. If not, you can make another group."),
            ],
            youAreReadyWhen="You can share a two-digit number by a one-digit number, name the remainder, and say what it means in a simple story.",
            householdItems=["17 objects", "5 plates"],
            setup="17 objects, 5 plates. Two stories: cakes on plates, and cars with 5 seats.",
            activityTitle="Share, leftover, two stories",
            steps=[
                "Share 17 onto 5 plates equally (whole objects). 3 each, 2 left in the pile.",
                "Cakes story: 2 cakes left over, not enough for another full plate each.",
                "Cars story: 17 people, 5 per car. 3 cars full, 2 people still need a car → 4 cars.",
                "Write 17 ÷ 5 = 3 r 2, then the sentence for each story.",
            ],
            check=[
                chk("14 ÷ 4 as objects that cannot be cut.", "3 r 2.", "4 r 0 or 3.5.", "Three plates of 4, two left."),
                chk("Remainder when dividing by 4 can be…", "0, 1, 2 or 3, not 4 or more.", "4.", "4 leftover would make another group."),
                chk("20 children, 6 per table. How many tables if no one stands?", "4 tables (3 full, 2 children need another).", "3 r 2 as the final answer with no story.", "The leftover children still need a table."),
            ],
            stretch="23 ÷ 5. Write r and a sentence.",
        ),
        t(
            id="y4-multiply-divide-by-10-100",
            year=4,
            strand="Multiplication and division",
            title="Multiply and divide by 10 and 100",
            shortTitle="× ÷ 10 and 100",
            summary="Moving digits one or two places because the number is 10 or 100 times the size — not ‘add zeros’ as a magic trick.",
            prerequisites=["y4-thousands"],
            statutoryOutcomes=["Find the effect of dividing a one- or two-digit number by 10 and 100, identifying the value of the digits in the answer as ones, tenths and hundredths"],
            readyToProgress=["4MD-1", "4NF-3"],
            whyThisMatters="This is the engine of decimals, money and converting centimetres to metres.",
            inPlainEnglish="3 × 10 = 30: the 3 ones become 3 tens. 3 × 100 = 300. 30 ÷ 10 = 3. 5 ÷ 10 = 5/10 = 0.5 if school has shown tenths as decimals. The digits slide; zeros hold empty places.",
            howSchoolTeachesIt="Place-value sliders / Gattegno. They show tenths and hundredths when dividing ones. They avoid ‘add a zero’ without place talk.",
            sayThis=["Did the digits get 10 times the size, or 100?", "What sits in the ones place now?", "5 ones divided by 10 — what fraction is that?"],
            avoidThis=["‘Add a zero’ as the whole method.", "Sliding the decimal point as a first image if they have no point yet — slide the digits on a chart."],
            misconceptions=[
                mis("3 × 10 = 310 because they insert a 1 and a 0.", "They mixed +10 and ×10.", "Times 10 is a place shift, not gluing 10."),
                mis("20 ÷ 10 = 20 or 0.20 with no meaning.", "They moved the wrong way or added a point for luck.", "2 tens become 2 ones."),
            ],
            youAreReadyWhen="You can ×10, ×100, ÷10 (and ÷100 when it stays a whole number) and say which place each digit moved to.",
            householdItems=["A place-value chart including tenths if you can: H T O . t h", "Digit cards"],
            setup="Chart: Hundreds Tens Ones | tenths. Place a 4 in ones.",
            activityTitle="Slide the 4",
            steps=[
                "4 × 10: slide to tens. Say 40.",
                "4 × 100: slide to hundreds. Say 400.",
                "4 ÷ 10: slide to tenths. Say 4 tenths (0.4 if school uses that).",
                "23 × 10 and 230 ÷ 10 as a round trip.",
            ],
            check=[
                chk("7 × 10.", "70.", "17 or 710.", "7 ones become 7 tens."),
                chk("60 ÷ 10.", "6.", "600 or 50.", "6 tens become 6 ones."),
                chk("3 ÷ 10 as tenths.", "3 tenths.", "30 or 3/3.", "Each one splits into 10 tenths; 3 ones make 30 tenths, which is 3 tenths if we divide the number 3 by 10 — 3/10."),
            ],
            stretch="45 ÷ 10 = 4 ones and 5 tenths.",
        ),
        t(
            id="y4-equivalent-fraction-families",
            year=4,
            strand="Fractions",
            title="Families of equivalent fractions",
            shortTitle="Equivalent families",
            summary="Use diagrams to see that 1/2, 2/4, 3/6 sit in a family, using factors and multiples when the picture is clear.",
            prerequisites=["y4-factor-pairs"],
            statutoryOutcomes=["Recognise and show, using diagrams, families of common equivalent fractions"],
            whyThisMatters="Year 5 will add unlike denominators. Families now prevent random multiplying.",
            inPlainEnglish="A family shares the same amount of the whole. 2/4 is 1/2 with each part split in two. You can often multiply or divide the top and bottom by the same number after you see why.",
            howSchoolTeachesIt="Fraction walls, bars, and then factors. Simplifying ‘where appropriate’ uses common factors, not cancelling luck.",
            sayThis=["Same whole, extra splits — same amount?", "What did we multiply top and bottom by?", "Can 6/9 shrink using a common factor?"],
            avoidThis=["Cross-cancel as a first trick.", "Different-size wholes compared as if they were the same."],
            misconceptions=[
                mis("They think 2/4 is twice 1/2 because 2 and 4 are bigger.", "They look at the numerals, not the amount.", "Stack the bars."),
                mis("They simplify 6/8 to 3/5 by subtracting 3 from both.", "They used subtract not a common factor.", "Halve both: 3/4. Factors, not subtract."),
            ],
            youAreReadyWhen="You can show a family for 1/2 or 1/3 on a wall, and you can simplify one fraction such as 6/9.",
            householdItems=["Same-length paper strips", "Pens"],
            setup="Three equal strips: halves, quarters, sixths.",
            activityTitle="Build a 1/2 family",
            steps=[
                "Shade 1/2, 2/4, 3/6. Stack.",
                "Say the multiplier: ×2, ×3.",
                "6/9 strip: fold or mark thirds. Shade 6 of 9, then see 2/3.",
                "Write 6/9 = 2/3.",
            ],
            check=[
                chk("Name two fractions equivalent to 1/3.", "2/6, 3/9 (or others).", "1/6.", "Extra equal splits."),
                chk("Simplify 8/12.", "2/3.", "4/7 or 8/12 is already simplest.", "Divide top and bottom by 4."),
                chk("Why not 2/4 = 1/3?", "Different amounts of the same whole.", "Both have a 1-ish feeling.", "Compare bars."),
            ],
            stretch="Where does 4/8 sit on the wall?",
        ),
        t(
            id="y4-hundredths",
            year=4,
            strand="Fractions",
            title="Hundredths",
            shortTitle="Hundredths",
            summary="Hundredths are 100 equal parts, and also tenths split into ten, and a one-digit number divided by 100.",
            prerequisites=["y4-multiply-divide-by-10-100"],
            statutoryOutcomes=["Count up and down in hundredths; recognise that hundredths arise when dividing an object by 100 and dividing tenths by 10"],
            whyThisMatters="Money (pence in a pound) and 0.01 sit here. Missing hundredths makes decimals a pattern without meaning.",
            inPlainEnglish="Split a whole into 100 equal parts: each is one hundredth. 10 hundredths make one tenth. 7 ÷ 100 = 7 hundredths.",
            howSchoolTeachesIt="100-square, metre stick in cm, pound in pence. Count 0.01, 0.02 if decimals are in play, or 1/100, 2/100.",
            sayThis=["How many hundredths in a tenth?", "7 ones divided by 100 is how many hundredths?", "Count in hundredths from 0.08 to 0.12 (or 8/100 to 12/100)."],
            avoidThis=["Saying 0.10 is ‘zero point ten’ as if it were 10 tenths in the hundredths column wrongly aligned.", "Skipping the 10 hundredths = 1 tenth link."],
            misconceptions=[
                mis("They think 1/100 is bigger than 1/10 because 100 is bigger.", "Denominator size mix-up.", "More splits, smaller pieces. A tenth is ten hundredths."),
                mis("They write 0.9 as 0.09 thinking extra zero makes it neater.", "Place of tenths vs hundredths.", "9 tenths is 90 hundredths, 0.90 if you write two places — not 0.09."),
            ],
            youAreReadyWhen="You can show a hundredth, count in hundredths through a tenth, and relate 7 ÷ 100 to 7 hundredths.",
            householdItems=["A 10-by-10 grid (100 squares)", "Two colours"],
            setup="Draw or print a 100-square as one whole.",
            activityTitle="Colour hundredths and tenths",
            steps=[
                "Shade 1 square: 1/100. Shade 10 squares in a row: 1/10.",
                "Shade 7 squares: 7/100. Say 7 ÷ 100.",
                "Count in hundredths from 8/100 to 12/100, crossing 10/100 = 1/10.",
                "If school uses 0.07, write it under 7/100.",
            ],
            check=[
                chk("How many hundredths in 1/10?", "10.", "100 or 1.", "One row of the 100-square."),
                chk("4 ÷ 100.", "4 hundredths.", "25 or 400.", "4 ones become 4 hundredths."),
                chk("0.09 or 9/100 vs 0.9 or 9/10 — which is larger?", "9/10.", "9/100.", "Nine tenths is nine rows, not nine squares."),
            ],
            stretch="1 pound = 100 pence. 7p is 7 hundredths of a pound.",
        ),
        t(
            id="y4-mixed-numbers",
            year=4,
            strand="Fractions",
            title="Mixed numbers and improper fractions",
            shortTitle="Mixed numbers",
            summary="Numbers such as 1 3/4 and 7/4 are the same amount: wholes plus a bit, or only extra quarters.",
            prerequisites=["y4-equivalent-fraction-families"],
            statutoryOutcomes=["Solve problems involving increasingly harder fractions to calculate quantities, including non-unit fractions where the answer is a whole number"],
            readyToProgress=["4F-1", "4F-2"],
            whyThisMatters="Adding fractions that bridge 1 needs both pictures. Year 4 RTP makes conversion explicit.",
            inPlainEnglish="7/4 is seven quarters. Four quarters make 1, so 7/4 is 1 and 3/4. Mixed number: whole + fraction. Improper: numerator bigger than denominator.",
            howSchoolTeachesIt="Number lines beyond 1, bars of several wholes, converting both ways. Location of mixed numbers on the line is an RTP focus.",
            sayThis=["How many quarters make 1?", "7 quarters is how many wholes and leftover?", "Show 1 3/4 as only quarters."],
            avoidThis=["A convert formula with no bars.", "Calling improper ‘wrong’ — the name is unlucky; it is a useful form."],
            misconceptions=[
                mis("They write 1 3/4 as 1.34 or 134.", "Place-value habits leak.", "It is 1 + 3/4, not digits glued."),
                mis("They convert 7/4 to 3/4, throwing the whole away.", "They only kept the remainder.", "The 1 whole is four of the seven quarters."),
            ],
            youAreReadyWhen="You can move 7/4 to 1 3/4 and back, and place 1 1/2 on a line.",
            householdItems=["Two same-size strips, each marked in quarters", "Paper line from 0 to 2"],
            setup="Two strips as two wholes, each in 4 quarters.",
            activityTitle="Fill 7 quarters",
            steps=[
                "Shade 4 quarters (1 whole) then 3 more. Say 1 3/4 and 7/4.",
                "Place 1 3/4 on the 0–2 line.",
                "Start from 1 1/4. Convert to quarters: 5/4.",
                "Count in quarters from 0 to 2.",
            ],
            check=[
                chk("5/4 as a mixed number.", "1 1/4.", "5/1 or 1/4.", "4 quarters make 1, 1 quarter left."),
                chk("1 2/3 as thirds only.", "5/3.", "3/2 or 12/3.", "1 = 3/3, plus 2/3."),
                chk("Where is 1 1/2 on 0–2?", "Halfway from 1 to 2.", "Halfway from 0 to 1.", "Past 1."),
            ],
            stretch="Add 3/4 + 2/4 as 5/4 = 1 1/4 — next pack goes further.",
        ),
        t(
            id="y4-add-subtract-fractions",
            year=4,
            strand="Fractions",
            title="Add and subtract fractions, including bridging 1",
            shortTitle="Add fractions past 1",
            summary="Same denominator, including answers greater than 1, using mixed numbers.",
            prerequisites=["y4-mixed-numbers"],
            statutoryOutcomes=["Add and subtract fractions with the same denominator"],
            readyToProgress=["4F-3"],
            whyThisMatters="Year 3 stayed within 1. Year 4 crosses 1, which is where mixed numbers earn their keep.",
            inPlainEnglish="5/7 + 4/7 = 9/7 = 1 2/7. You still only add the counts of equal pieces.",
            howSchoolTeachesIt="Bars that continue onto a second whole. Convert to mixed numbers. Still no unlike denominators.",
            sayThis=["Same size pieces?", "How many sevenths now? Is that more than a whole?", "Write it as a mixed number too."],
            avoidThis=["Adding denominators.", "Unlike denominators."],
            misconceptions=[
                mis("They stop at 7/7 and ignore extra sevenths.", "They think 1 is a wall.", "Keep counting pieces onto the next bar."),
                mis("5/8 + 5/8 = 10/16.", "Old add-both-numbers habit.", "Keep 8. Ten eighths."),
            ],
            youAreReadyWhen="You can add or subtract same-denominator fractions that bridge 1 and write a mixed number.",
            householdItems=["Two strips in eighths", "Pens"],
            setup="Two wholes in 8 equal parts.",
            activityTitle="Cross the whole",
            steps=[
                "5/8 + 5/8. Fill 8/8 and 2/8 more. Say 10/8 = 1 2/8.",
                "Simplify 1 2/8 to 1 1/4 if they see the family.",
                "1 3/8 − 5/8: think 11/8 − 5/8 = 6/8.",
                "Compare 6/8 and 1.",
            ],
            check=[
                chk("3/5 + 4/5.", "7/5 or 1 2/5.", "7/10.", "Seven fifths."),
                chk("9/6 − 1/6.", "8/6 or 1 2/6.", "8/0.", "Eight sixths."),
                chk("1 1/4 + 3/4.", "2.", "1 4/4 left as is, or 4/8.", "5/4 + 3/4 = 8/4 = 2."),
            ],
            stretch="A story: 3/4 of a litre + 3/4 of a litre. How many litres?",
        ),
        t(
            id="y4-decimal-equivalents",
            year=4,
            strand="Fractions",
            title="Decimal equivalents of tenths, hundredths and halves",
            shortTitle="Fraction–decimal links",
            summary="Write tenths and hundredths as decimals, and know 1/2 = 0.5, 1/4 = 0.25, 3/4 = 0.75.",
            prerequisites=["y4-hundredths"],
            statutoryOutcomes=[
                "Recognise and write decimal equivalents of any number of tenths or hundredths",
                "Recognise and write decimal equivalents to 1/4, 1/2, 3/4",
            ],
            whyThisMatters="These three ‘benchmark’ decimals unlock money and measures. They should be pictured, not only memorised.",
            inPlainEnglish="3/10 = 0.3. 7/100 = 0.07. Half a whole is 0.5 because it is 5 tenths. A quarter is 25 hundredths = 0.25.",
            howSchoolTeachesIt="Place-value chart with a decimal point, 100-square, and number lines. They say ‘zero point three’ as 3 tenths, not ‘nought point three zero’ unless hundredths are meant.",
            sayThis=["3 tenths, how do we write that with a point?", "Why is 0.25 a quarter?", "0.5 or 0.50 — same amount?"],
            avoidThis=["Reading 0.25 as 25 or as 2.5.", "Teaching 1/3 = 0.33 as if it were exact, unless you say it is an approximation."],
            misconceptions=[
                mis("They think 0.25 is bigger than 0.5 because 25 > 5.", "They compared digits, not places.", "0.5 is 5 tenths. 0.25 is 2 tenths and 5 hundredths."),
                mis("They write 3/10 as 0.03.", "Tenths vs hundredths.", "3 tenths sit in the tenths column: 0.3."),
            ],
            youAreReadyWhen="You can write tenths and hundredths as decimals and show 1/2, 1/4, 3/4 on a 100-square or line.",
            householdItems=["100-square", "Place-value chart with a point"],
            setup="100-square as 1 whole. Chart: ones . tenths hundredths.",
            activityTitle="Benchmarks on a hundred square",
            steps=[
                "Shade 50 squares: 1/2 = 0.5.",
                "Shade 25: 1/4 = 0.25. 75: 3/4 = 0.75.",
                "Write 3/10 as 30 hundredths = 0.30 = 0.3.",
                "Place 0.07 as 7 squares.",
            ],
            check=[
                chk("7/10 as a decimal.", "0.7.", "0.07 or 7.10.", "Tenths column."),
                chk("1/4 as a decimal.", "0.25.", "0.4 or 1.4.", "25 hundredths."),
                chk("Which is larger: 0.4 or 0.25?", "0.4.", "0.25.", "4 tenths vs 2 tenths and a bit."),
            ],
            stretch="Money: £0.25 is a quarter of a pound.",
        ),
        t(
            id="y4-compare-decimals",
            year=4,
            strand="Fractions",
            title="Compare decimals with up to 2 decimal places",
            shortTitle="Compare decimals",
            summary="Compare 0.45 and 0.6 by place value or by making the same number of decimal places, and round 1-place decimals to the nearest whole.",
            prerequisites=["y4-decimal-equivalents"],
            statutoryOutcomes=[
                "Round decimals with 1 decimal place to the nearest whole number",
                "Compare numbers with the same number of decimal places up to 2 decimal places",
                "Solve simple measure and money problems involving fractions and decimals to 2 decimal places",
            ],
            whyThisMatters="Measures and money are already 2 decimal places. Children who compare 0.9 and 0.89 as ‘89 is bigger’ need this pack.",
            inPlainEnglish="Compare tenths first, then hundredths. 0.6 is 0.60, which is more than 0.45. 3.6 to the nearest whole is 4 because it is past 3.5.",
            howSchoolTeachesIt="Place-value charts, lines, and equalising places (0.6 = 0.60). Rounding uses the midpoint .5.",
            sayThis=["Look at tenths first.", "Write 0.6 as hundredths too.", "Is 3.6 nearer 3 or 4?"],
            avoidThis=["Comparing 0.45 and 0.6 as 45 vs 6.", "Rounding 2.5 down ‘to be fair’ — school convention rounds 0.5 up to the next whole."],
            misconceptions=[
                mis("0.89 > 0.9 because 89 > 9.", "Extra digits look bigger.", "0.9 is 9 tenths. 0.89 is 8 tenths and 9 hundredths."),
                mis("They round 3.4 to 4 because they saw a 4.", "Wrong digit.", "To nearest whole, look at the tenths. 4 tenths is below halfway."),
            ],
            youAreReadyWhen="You can compare two 2-place decimals and round a 1-place decimal to the nearest whole.",
            householdItems=["Place-value chart", "A 0–4 number line marked in tenths", "Two prices from a receipt if you have one"],
            setup="Write 0.45 and 0.6. Chart ready.",
            activityTitle="Equalise, then round",
            steps=[
                "Write 0.6 as 0.60. Compare 45 hundredths and 60 hundredths.",
                "Place 3.6 on the line between 3 and 4.",
                "Round 3.6 and 3.4.",
                "Compare two receipt pence amounts as pounds if you have them.",
            ],
            check=[
                chk("Larger: 0.3 or 0.28?", "0.3.", "0.28.", "3 tenths vs 2 tenths."),
                chk("Round 4.5 to nearest whole.", "5.", "4.", "Halfway rounds up in this convention."),
                chk("Order 0.4, 0.04, 0.44.", "0.04, 0.4, 0.44.", "0.4, 0.04, 0.44 as if 4=04.", "Hundredths: 4, 40, 44."),
            ],
            stretch="A 1.8 m plank vs 1.75 m. Which is longer?",
        ),
        t(
            id="y4-convert-measures",
            year=4,
            strand="Measurement",
            title="Convert units, including time",
            shortTitle="Convert units",
            summary="Use ×10, ×100, ×1000 thinking for km–m and similar, and convert hours–minutes, years–months, weeks–days.",
            prerequisites=["y4-multiply-divide-by-10-100"],
            statutoryOutcomes=[
                "Convert between different units of measure, for example kilometre to metre; hour to minute",
                "Solve problems involving converting from hours to minutes, minutes to seconds, years to months, weeks to days",
            ],
            whyThisMatters="Conversion is multiplication in costume. Time is not base 10, which is why minutes catch people out.",
            inPlainEnglish="3 km = 3,000 m because 1 km is 1,000 m. 2 hours = 120 minutes because 1 hour is 60 minutes, not 100. 1 week = 7 days; 1 year = 12 months.",
            howSchoolTeachesIt="School uses place-value for metric and number lines / clocks for time. They keep money as pounds and pence alongside.",
            sayThis=["Is this metric (tens, hundreds, thousands) or time (60, 7, 12)?", "3 km in metres?", "How many minutes in 2 hours?"],
            avoidThis=["Using 100 minutes in an hour.", "Converting with no unit said out loud."],
            misconceptions=[
                mis("2.5 hours = 2 hours 5 minutes or 25 minutes.", "Decimal hours mixed with time places.", "Half an hour is 30 minutes. 2.5 hours = 2 h 30 min."),
                mis("3 km = 30 m or 300 m.", "Wrong power of 10.", "Kilo means 1,000. ×1,000."),
            ],
            youAreReadyWhen="You can convert a simple km–m or m–cm, and hours–minutes, saying the conversion number.",
            householdItems=["Paper", "A clock", "Optional: a 1 litre bottle and a 100 ml cup"],
            setup="Write two conversion facts: 1 km = 1,000 m; 1 hour = 60 min.",
            activityTitle="Two systems",
            steps=[
                "Convert 4 km to m, 300 cm to m.",
                "Convert 3 hours to minutes, 90 minutes to hours and minutes.",
                "2 weeks in days. 18 months in years and months.",
                "If you have a jug, 1 l in 100 ml cupfuls (10).",
            ],
            check=[
                chk("5 km in metres.", "5,000 m.", "500 m or 5,000 km.", "×1,000."),
                chk("2 hours in minutes.", "120.", "200 or 60.", "2 × 60."),
                chk("80 minutes as hours and minutes.", "1 hour 20 minutes.", "80 hours or 1.20 hours as if money.", "60 min make 1 hour; 20 left."),
            ],
            stretch="A film 135 minutes. Hours and minutes.",
        ),
        t(
            id="y4-perimeter-and-area",
            year=4,
            strand="Measurement",
            title="Perimeter of rectilinear shapes and area by counting squares",
            shortTitle="Perimeter and area",
            summary="Walk the outer edge for perimeter. Fill the inside with squares for area. Keep the two words apart.",
            prerequisites=["y4-convert-measures"],
            statutoryOutcomes=[
                "Measure and calculate the perimeter of a rectilinear figure (including squares) in centimetres and metres",
                "Find the area of rectilinear shapes by counting squares",
            ],
            whyThisMatters="Mixing fence and carpet is the lasting error. Year 4 counts squares; Year 5 will multiply length by width.",
            inPlainEnglish="Rectilinear means edges meet at right angles, like a stepped house outline. Perimeter: add every outer side. Area: how many 1 cm squares cover the inside.",
            howSchoolTeachesIt="Squared paper, then missing-length problems on an L shape. They may write perimeter as 2(a+b) for a rectangle after adding four sides.",
            sayThis=["Edge or inside?", "Are we missing a length we can work out?", "Count full squares. What about half squares?"],
            avoidThis=["length × width before counting squares is secure.", "Calling area ‘the times’ with no squares."],
            misconceptions=[
                mis("They add all the grid numbers they see, including inner ticks.", "They counted every printed mark.", "Only the outer walk, or only inner squares — pick one job."),
                mis("L-shape area as one big rectangle, forgetting to subtract the missing bit, or double-counting.", "Composition needs care.", "Split into two rectangles. Add the squares."),
            ],
            youAreReadyWhen="You can find an L-shape perimeter with a missing side, and an area by counting squares.",
            householdItems=["Squared paper (draw a grid if needed)", "A 6-by-4 rectangle of squares, and an L made of 8 squares"],
            setup="Draw a 6 by 4 rectangle on squares. Draw an L: 6 squares along, 3 up.",
            activityTitle="Fence then carpet",
            steps=[
                "Rectangle: add four sides for perimeter. Count 24 squares for area (or 6×4 if they see it).",
                "L-shape: walk the outer edge. Work out any missing length from the others.",
                "Count squares inside the L.",
                "Say both answers with units: cm for perimeter, square cm for area.",
            ],
            check=[
                chk("3 by 5 rectangle area in squares.", "15.", "16 or 8.", "Count or 3×5."),
                chk("Perimeter of 3 by 5.", "16.", "15.", "3+5+3+5."),
                chk("Units: why not cm for area?", "Area is squares, so square cm.", "They shrug.", "Fence vs tiles."),
            ],
            stretch="Same area, different perimeter: 1×12 and 3×4.",
        ),
        t(
            id="y4-12-and-24-hour",
            year=4,
            strand="Measurement",
            title="Analogue, digital, 12-hour and 24-hour time",
            shortTitle="12- and 24-hour time",
            summary="Read and convert between analogue, digital 12-hour and 24-hour clocks.",
            prerequisites=["y4-convert-measures"],
            statutoryOutcomes=["Read, write and convert time between analogue and digital 12- and 24-hour clocks"],
            whyThisMatters="Timetables in Year 5 assume 24-hour. Mixing am/pm with 15:00 is a practical safety issue for buses.",
            inPlainEnglish="3:00 pm is 15:00. Add 12 to pm hours except 12 pm (noon) stays 12:00. 12 am (midnight) is 00:00. Analogue 4:20 still means 20 minutes past 4.",
            howSchoolTeachesIt="Paired clocks, number lines 0–24, and ‘add 12 after noon’. They still use am/pm talk.",
            sayThis=["Is it before noon or after?", "What do we add to 3 pm to make 24-hour?", "Show 07:05 on an analogue face."],
            avoidThis=["Saying 12 pm is midnight. Noon is 12 pm; midnight is 12 am / 00:00.", "Writing 3:00 pm as 15:00 pm."],
            misconceptions=[
                mis("They add 12 to 12 pm and get 24:00 for lunch.", "The noon exception.", "12:00–12:59 stays 12:xx in 24-hour. 1 pm becomes 13:00."),
                mis("They read digital 4:20 as 20 past 5 because the hour hand would have moved.", "Digital already states the hour.", "4:20 means hour still 4."),
            ],
            youAreReadyWhen="You can convert a pm time to 24-hour and set an analogue clock from a digital time.",
            householdItems=["Paper clock or real analogue clock", "Paper for a 0–24 line"],
            setup="Draw 0–24. Mark noon at 12, midnight at 0/24.",
            activityTitle="Three ways to say the same time",
            steps=[
                "Set analogue 7:05. Write 7:05 am and 07:05.",
                "Set 3:20 pm. Write 15:20.",
                "Convert 19:45 to analogue and to 7:45 pm.",
                "Talk through noon and midnight.",
            ],
            check=[
                chk("2:30 pm in 24-hour.", "14:30.", "2:30 or 16:30.", "Add 12 to the hour."),
                chk("00:10 in 12-hour.", "12:10 am.", "12:10 pm or 10 am.", "Just after midnight."),
                chk("Analogue minute hand on 9, hour just before 5.", "Quarter to 5, 4:45.", "9:20.", "Minute hand on 9 is 45 minutes."),
            ],
            stretch="A bus at 17:05. How many hours and minutes from 3:20 pm?",
        ),
        t(
            id="y4-shape-properties",
            year=4,
            strand="Geometry",
            title="Triangles, quadrilaterals and angles",
            shortTitle="Classify shapes",
            summary="Compare triangles and quadrilaterals by sides and angles. Identify acute and obtuse, and compare angles up to two right angles.",
            statutoryOutcomes=[
                "Compare and classify geometric shapes, including quadrilaterals and triangles, based on their properties and sizes",
                "Identify acute and obtuse angles and compare and order angles up to 2 right angles by size",
            ],
            readyToProgress=["4G-2"],
            whyThisMatters="Names (isosceles, parallelogram) should follow properties, not ‘it looks like a roof’.",
            inPlainEnglish="Acute: smaller than a right angle. Obtuse: larger than a right angle but less than a straight line. Equilateral: three equal sides. Isosceles: two equal. Scalene: none equal. Quadrilaterals include square, rectangle, rhombus, parallelogram, trapezium — school’s exact trapezium definition can vary; follow their poster.",
            howSchoolTeachesIt="Sorting loops, geostrips, right-angle testers, then comparing angles by matching openings (protractor comes in Year 5).",
            sayThis=["Right, smaller, or larger?", "How many equal sides?", "Does it have a pair of parallel sides?"],
            avoidThis=["Names without tests.", "Degrees unless school has started them."],
            misconceptions=[
                mis("They think a long thin rhombus is not a rhombus because it is not ‘diamond sitting on a vertex’.", "Orientation and a cartoon diamond.", "Check equal sides. Turn it."),
                mis("They call every triangle with a flat base isosceles.", "The base fooled them.", "Measure or match sides, not the way it sits."),
            ],
            youAreReadyWhen="You can sort a handful of triangles and quads using equal sides, right angles, and acute/obtuse.",
            householdItems=["Paper triangles and quads (cut 6 mixed)", "Right-angle card tester", "Optional: spaghetti equal lengths"],
            setup="Cut an equilateral-ish, a right-angled scalene, a rectangle, a non-rectangular parallelogram, a square.",
            activityTitle="Test, then name",
            steps=[
                "Sort angles: acute, right, obtuse using the tester.",
                "Group triangles by equal sides.",
                "Group quads by parallel sides and right angles.",
                "Order three angles smallest to largest by overlaying.",
            ],
            check=[
                chk("An angle smaller than the square tester.", "Acute.", "Obtuse.", "Fits inside the tester."),
                chk("Rectangle vs square.", "Square has four equal sides; both have four right angles.", "They are the same word.", "Test side lengths."),
                chk("Can a triangle have two obtuse angles?", "No — they would not close.", "Yes.", "Try to build it."),
            ],
            stretch="Is a square a rectangle? School usually says yes (special rectangle). Follow their language.",
        ),
        t(
            id="y4-symmetry",
            year=4,
            strand="Geometry",
            title="Line symmetry",
            shortTitle="Line symmetry",
            summary="Find lines of symmetry and complete a picture so both sides match, including when the shape is turned.",
            statutoryOutcomes=[
                "Identify lines of symmetry in 2-D shapes presented in different orientations",
                "Complete a simple symmetric figure with respect to a specific line of symmetry",
            ],
            readyToProgress=["4G-3"],
            whyThisMatters="Reflection in Year 5 needs this match-across-a-line idea, not ‘it looks pretty’.",
            inPlainEnglish="A line of symmetry is a fold line: both sides match exactly. A rectangle has two (usually), a square has four, a typical scalene triangle has none. Complete the other side by matching distance from the line.",
            howSchoolTeachesIt="Mirrors, tracing, squared paper. Shapes are rotated so children do not only accept vertical folds.",
            sayThis=["If we fold here, do the sides match?", "This point is 2 squares from the line — where is its partner?", "Turn the shape. Does it still have the same lines?"],
            avoidThis=["Only vertical ‘butterflies’.", "Calling diagonal stripes symmetry when they do not match by fold."],
            misconceptions=[
                mis("They think a parallelogram that is not a rectangle has a line of symmetry because it looks balanced.", "Rotational balance is not a fold.", "Try the fold. Corners miss."),
                mis("They copy a point across by moving along the line, not perpendicular to it.", "Wrong direction of match.", "The partner is straight across, same distance."),
            ],
            youAreReadyWhen="You can find the fold lines on a square and complete a simple picture across a given line on squared paper.",
            householdItems=["Squared paper", "A small mirror if you have one", "Paper shapes to fold"],
            setup="Draw a vertical line on squared paper. Plot 4 dots on one side.",
            activityTitle="Fold, then complete",
            steps=[
                "Fold a paper rectangle. How many successful folds?",
                "Complete the 4 dots’ partners across your drawn line.",
                "Draw a triangle that has one line of symmetry. Check by folding.",
                "Turn a square. Find four lines (two diagonal).",
            ],
            check=[
                chk("Lines of symmetry of a square.", "4.", "1 or 2.", "Two midlines, two diagonals."),
                chk("Isosceles triangle with two equal sides: how many fold lines typically?", "1.", "3 or 0.", "The fold that maps equal sides."),
                chk("A partner 3 squares left of a vertical line.", "3 squares right, same height.", "3 down, or 3 along the line.", "Straight across."),
            ],
            stretch="Complete a pattern where the line is horizontal.",
        ),
        t(
            id="y4-coordinates-and-translations",
            year=4,
            strand="Geometry",
            title="Coordinates and translations in the first quadrant",
            shortTitle="Coordinates",
            summary="Read (x, y) as across then up, plot points, and slide a shape without turning it.",
            statutoryOutcomes=[
                "Describe positions on a 2-D grid as coordinates in the first quadrant",
                "Describe movements between positions as translations of a given unit to the left/right and up/down",
                "Plot specified points and draw sides to complete a given polygon",
            ],
            readyToProgress=["4G-1"],
            whyThisMatters="Year 6 four-quadrant grids reuse this order: across first, then up. Mixing the order is sticky.",
            inPlainEnglish="(2, 5) means 2 along the corridor, 5 up the stairs. Translation is a slide: every point moves the same right/left and up/down. The shape does not turn or flip.",
            howSchoolTeachesIt="First quadrant only. Equal scales. They complete polygons from given points and describe moves in words, not vectors.",
            sayThis=["Across first, then up.", "Has every corner moved the same?", "Did we turn it? (We should not.)"],
            avoidThis=["Starting with up first because reading is top-to-bottom.", "Calling a flip a translation."],
            misconceptions=[
                mis("They plot (2,5) at 5 along and 2 up.", "Order swapped.", "Say ‘2 along, 5 up’ every time tonight."),
                mis("They move one corner 3 right and another 2 right.", "Not a translation.", "The whole shape takes the same journey."),
            ],
            youAreReadyWhen="You can plot three corners of a rectangle, complete the fourth, and slide it 2 right and 1 up.",
            householdItems=["Squared paper with axes 0–8 along and up", "Pencil"],
            setup="Draw axes in the first quadrant. Label 0–8 on both. Equal spacing.",
            activityTitle="Plot, complete, slide",
            steps=[
                "Plot (2,1), (5,1), (5,4). Ask for the missing corner of the rectangle.",
                "Write (2,4). Draw the sides.",
                "Translate 2 right and 1 up. Write the new corners.",
                "Check the shape has not turned.",
            ],
            check=[
                chk("Plot (0, 3).", "On the up axis, 3 up.", "3 along.", "(0, something) sits on the vertical axis."),
                chk("After 1 right from (2,5).", "(3,5).", "(2,6) or (1,5).", "Along changes."),
                chk("Is a quarter-turn a translation?", "No.", "Yes.", "Turns change orientation. Slides do not."),
            ],
            stretch="Draw a triangle from (1,1), (4,1), (1,3). Translate 3 left — stay in the first quadrant or notice you would fall off (so choose a smaller slide).",
        ),
        t(
            id="y4-time-graphs",
            year=4,
            strand="Statistics",
            title="Bar charts, time graphs and comparison questions",
            shortTitle="Graphs over time",
            summary="Read discrete and continuous data, including time graphs, and solve sum and difference questions.",
            statutoryOutcomes=[
                "Interpret and present discrete and continuous data using appropriate graphical methods, including bar charts and time graphs",
                "Solve comparison, sum and difference problems using information presented in bar charts, pictograms, tables and other graphs",
            ],
            whyThisMatters="A time graph’s in-between points can mean ‘during the hour’, not a new category. Scale still matters.",
            inPlainEnglish="Discrete: counts in categories (favourite fruit). Continuous: something that can sit between, like temperature over a day. A time graph plots values against time. Always read the scale.",
            howSchoolTeachesIt="School draws a simple temperature or height-over-time graph, and still uses bar charts. Questions: how much more, total, difference.",
            sayThis=["Is this categories, or something changing through time?", "What is one step on the scale?", "How much did it rise between 2 o’clock and 4?"],
            avoidThis=["Joining bars into a line for favourite fruit.", "Ignoring the time axis."],
            misconceptions=[
                mis("They add the times instead of the values.", "Two axes, wrong one.", "The height of the graph is the value. Time runs along."),
                mis("They read between two plotted times as a category they can count.", "Discrete habit on continuous data.", "Between 2 and 4 the temperature moved; there is not a third fruit called 3 o’clock."),
            ],
            youAreReadyWhen="You can read a simple time graph’s scale and answer a difference question, and you can still read a bar chart.",
            householdItems=["Paper", "A made-up table: temperature at 8am, 12pm, 4pm, 8pm"],
            setup="Invent four temperatures, such as 8, 14, 16, 11. Draw time across, temperature up, scale 2.",
            activityTitle="Plot a day, then a bar",
            steps=[
                "Plot the four points. Join them gently for a time graph.",
                "Ask the difference between noon and 8pm.",
                "Make a bar chart of something categorical: 4, 7, 3 votes.",
                "Ask a two-step: total votes, then how many more the winner had than last.",
            ],
            check=[
                chk("Scale 2, bar 6 squares tall.", "12.", "6.", "6 × 2."),
                chk("Temperature 14 at noon and 11 at 8pm. Difference?", "3 degrees down.", "25 or 3 hours.", "The values, not the times."),
                chk("Should favourite colour be a time graph?", "No — categories. Use a bar chart.", "Yes.", "Colour does not run through hours."),
            ],
            stretch="Estimate the temperature at 2pm from the line between 12 and 4, saying it is a reading of the graph not a measurement.",
        ),
    ]
