#!/usr/bin/env python3
"""Year 5 KS2 draft specs."""


def t(**kwargs):
    return kwargs


def mis(misconception: str, why: str, instead: str) -> dict:
    return {"misconception": misconception, "why": why, "instead": instead}


def chk(prompt: str, looksLike: str, notYet: str, nudge: str) -> dict:
    return {"prompt": prompt, "looksLike": looksLike, "notYet": notYet, "nudge": nudge}


YEAR5 = [
    t(
        id="y5-numbers-to-a-million",
        year=5,
        strand="Number and place value",
        title="Numbers to a million",
        shortTitle="To 1,000,000",
        summary="Read, write, order and compare numbers to at least 1,000,000 and say what each digit is worth.",
        statutoryOutcomes=["Read, write, order and compare numbers to at least 1,000,000 and determine the value of each digit"],
        readyToProgress=["5NPV-2"],
        whyThisMatters="Place value is still the whole game, just with more rooms in the house. 4,050,000 is not ‘four and five with zeros’.",
        inPlainEnglish="Each place is ten times the one to its right. 1,000,000 is a thousand thousands. In 4,050,307 the 5 is fifty thousand.",
        howSchoolTeachesIt="Place-value charts with millions, sliders, and grouping in threes (4 050 307) so commas/spaces match thousands.",
        sayThis=["What is the 5 worth in 4,050,307?", "Read this in groups of three digits.", "Which is greater, 809,000 or 810,000?"],
        avoidThis=["Reading 4,050,307 as 4 million 50 thousand 307 without checking the hundreds of thousands is empty.", "Skipping the names of the new places."],
        misconceptions=[
            mis("They write 2 million 40 as 2,000,040 or 240.", "Empty places dropped.", "Fill every place: 2,000,040 is 2 million and 40; 2 million 40 thousand is 2,040,000."),
            mis("They order 99,999 above 100,000 because it has more 9s.", "Digit glitter vs size.", "100,000 has a 1 in the hundred-thousands. It is larger."),
        ],
        youAreReadyWhen="You can name each digit in a 6- or 7-digit number and order three such numbers.",
        householdItems=["Place-value chart: M HTh TTh Th H T O", "Digit scraps"],
        setup="Write 4,050,307 in the chart.",
        activityTitle="Name, regroup, order",
        steps=["Say each place.","Trade 1 million for 10 hundred-thousands.","Order 809,000, 90,000, 810,000.","Write two million and forty thousand in digits."],
        check=[
            chk("Value of 5 in 4,050,307.", "50,000.", "5,000 or 5.", "Ten-thousands? Wait: 4,050,307 — 5 is ten-thousands? 4 050 307: 0 hundred thousands, 5 ten thousands. Yes 50,000."),
            chk("2 million 40 thousand in digits.", "2,040,000.", "2,000,040.", "Forty thousand, not forty."),
            chk("Smaller: 1,002,000 or 999,999.", "999,999.", "1,002,000.", "1 million is already more than 999,999."),
        ],
        stretch="How many thousands in 1,000,000?",
    ),
    t(
        id="y5-powers-of-10",
        year=5,
        strand="Number and place value",
        title="Counting in powers of 10",
        shortTitle="Powers of 10",
        summary="Count forwards and backwards in 10, 100, 1,000, 10,000, 100,000 from any number up to a million.",
        prerequisites=["y5-numbers-to-a-million"],
        statutoryOutcomes=["Count forwards or backwards in steps of powers of 10 for any given number up to 1,000,000"],
        readyToProgress=["5NPV-1", "5NF-2"],
        whyThisMatters="This is scaling place value. It later becomes ×10 and ÷10 with decimals in the same breath.",
        inPlainEnglish="A power of 10 is 10, 100, 1,000, and so on. From 45,080, a jump of 10,000 lands on 55,080. The other digits stay still unless you roll over.",
        howSchoolTeachesIt="Place-value chart hops, not reciting from 0. They include decimal tenths as 1/10 the size of 1 when ready.",
        sayThis=["Which digit will move if we add 10,000?", "Add 100,000 to 760,000. What rolls over?", "What is 10 times smaller than 3,000?"],
        avoidThis=["Always starting the count at 0.", "‘Add a zero’ with no place named."],
        misconceptions=[
            mis("45,080 + 10,000 becomes 45,090 or 145,080.", "Wrong place.", "The 4 is 40,000. Adding 10,000 makes 55,080."),
            mis("They think 10 times smaller than 3,000 is 2,000.", "Minus 10 vs ÷10.", "10 times smaller is 300."),
        ],
        youAreReadyWhen="You can hop 10, 100, 1,000, 10,000 or 100,000 from a six-digit number, including one rollover.",
        householdItems=["Place-value chart", "A starting number such as 45,080"],
        setup="Chart plus 45,080.",
        activityTitle="Hop one place at a time",
        steps=["+10, +100, +1,000, +10,000 from 45,080.","760,000 + 100,000.","3,000 ÷ 10 as 10 times smaller.","Count back in 10,000s from 80,000 through 0 if they are ready (optional)."],
        check=[
            chk("10,000 more than 45,080.", "55,080.", "45,090.", "Ten-thousands digit."),
            chk("100,000 more than 760,000.", "860,000.", "770,000.", "Hundred-thousands."),
            chk("10 times smaller than 4,000.", "400.", "3,990.", "÷10, not −10."),
        ],
        stretch="1/10 of 0.3 comes in the decimals pack. Tonight stay whole unless they push.",
    ),
    t(
        id="y5-negative-numbers-in-context",
        year=5,
        strand="Number and place value",
        title="Negative numbers in context",
        shortTitle="Negatives in context",
        summary="Read negatives in temperature, money, and height, and count through 0 with positive and negative wholes.",
        prerequisites=["y5-numbers-to-a-million"],
        statutoryOutcomes=["Interpret negative numbers in context, count forwards and backwards with positive and negative whole numbers, including through 0"],
        whyThisMatters="Context stops −3 from being ‘a take-away 3’. Year 6 will find intervals across 0.",
        inPlainEnglish="−3 °C is 3 degrees below 0. From 4 °C to −2 °C the drop is 6 degrees. You can count 4, 3, 2, 1, 0, −1, −2.",
        howSchoolTeachesIt="Thermometers, bank overdrafts (carefully), sea level. Number lines that cross 0. They compare and count; full calculation across 0 is tightened in Year 6.",
        sayThis=["Which is colder, −1 or −6?", "Count from 3 down through 0 to −4.", "A temperature falls from 2 to −5. How many degrees?"],
        avoidThis=["Two minuses make a plus as a first rule.", "Shame around overdraft stories — keep it to a number line if money is sensitive."],
        misconceptions=[
            mis("They think −1 is colder than −6 because 1 is smaller.", "Magnitude vs position.", "−6 is further below 0."),
            mis("From 2 to −5 they say 3 degrees (2+5 without crossing).", "They added the numerals.", "Count the hops through 0: 2 to 0 is 2, then 5 more, total 7."),
        ],
        youAreReadyWhen="You can count through 0 and compare two temperatures below 0, and have a go at the size of a drop that crosses 0.",
        householdItems=["A line from −8 to 8", "A weather story"],
        setup="Line −8 to 8. Mark 0 clearly.",
        activityTitle="Thermometer hops",
        steps=["Count 4 down to −3.","Compare −1 and −6.","Drop from 2 to −5. Count hops.","A lift: floor 3 to basement −1."],
        check=[
            chk("Colder: −2 or −5.", "−5.", "−2.", "Further below 0."),
            chk("Count back 5 from 2.", "−3.", "3 or 0.", "2,1,0,−1,−2,−3 — that is 5 hops to −3."),
            chk("Rise from −4 to 3.", "7 degrees.", "1 or −1.", "4 to reach 0, then 3 more."),
        ],
        stretch="If school wants the interval now: |2 − (−5)| as hops, not a formula.",
    ),
    t(
        id="y5-rounding-large-numbers",
        year=5,
        strand="Number and place value",
        title="Round numbers up to 1,000,000",
        shortTitle="Round large numbers",
        summary="Round to the nearest 10, 100, 1,000, 10,000 or 100,000 by finding the midpoint of that place.",
        prerequisites=["y5-powers-of-10"],
        statutoryOutcomes=["Round any number up to 1,000,000 to the nearest 10, 100, 1,000, 10,000 and 100,000"],
        readyToProgress=["5NPV-3"],
        whyThisMatters="Checking 24,680 × 3 against 25,000 × 3 is how Year 5 catches wild answers.",
        inPlainEnglish="To the nearest 10,000, look at the thousands. 24,680 sits between 20,000 and 30,000; midpoint 25,000; 24,680 is below so 20,000. Wait: 24,680 compared with 25,000 — below midpoint, nearer 20,000. Yes.",
        howSchoolTeachesIt="Zoomed number lines for the place you are rounding to. Same 5-up convention.",
        sayThis=["Which two multiples of 10,000 sit either side?", "Where is halfway?", "Which end is closer?"],
        avoidThis=["Rounding every digit at once.", "A rhyme with no line for a new place (10,000)."],
        misconceptions=[
            mis("They round 24,680 to 30,000 because they saw 4 and 6 and ‘went up twice’.", "Multiple places at once.", "Choose one place to round to."),
            mis("They think 25,000 as midpoint should go down.", "Fear of 5.", "School convention: 5 or more, up."),
        ],
        youAreReadyWhen="You can round the same number to 100, to 1,000 and to 10,000 and explain the three midpoints.",
        householdItems=["Paper lines for 24,000–25,000 and 20,000–30,000"],
        setup="Number 24,680. Two zooms.",
        activityTitle="Same number, three roundings",
        steps=["Nearest 100: between 24,600 and 24,700.","Nearest 1,000: 24,000 vs 25,000.","Nearest 10,000: 20,000 vs 30,000.","Nearest 100,000: 0 vs 100,000."],
        check=[
            chk("24,680 to nearest 1,000.", "25,000.", "24,000 or 24,700.", "Past 24,500."),
            chk("24,680 to nearest 10,000.", "20,000.", "30,000.", "Below 25,000 midpoint."),
            chk("350,000 to nearest 100,000.", "400,000.", "300,000.", "Exact midpoint: convention rounds up."),
        ],
        stretch="Use the rounded number to estimate 24,680 + 51,200.",
    ),
    t(
        id="y5-roman-to-1000",
        year=5,
        strand="Number and place value",
        title="Roman numerals to 1,000 and years",
        shortTitle="Roman numerals to M",
        summary="Read Roman numerals to M and recognise years written in Roman numerals.",
        statutoryOutcomes=["Read Roman numerals to 1,000 (M) and recognise years written in Roman numerals"],
        whyThisMatters="Dates on buildings and copyright lines. Still a chance to contrast with place value and 0.",
        inPlainEnglish="D=500, M=1,000. 2016 is MMXVI. You still add and subtract by position, with no zero.",
        howSchoolTeachesIt="Extend the Y4 key. Read a few year numbers. Historical note on 0 and place value remains the maths, not Latin club.",
        sayThis=["What is M? What is D?", "Why is 2016 MMXVI not MM6?", "Where is the zero in Roman 2016? (There isn’t one.)"],
        avoidThis=["Decoding long film-end dates as the first task.", "Treating it as a replacement for Arabic numbers."],
        misconceptions=[
            mis("They read MC as 1100+ or 1000−100 wrongly: MC is 1100 (M+C).", "Subtract vs add order.", "C after M adds. CM would be 900."),
            mis("They write 2016 as MMVI, dropping the 10.", "X for 10 missed.", "2016 = 2000+10+6 = MM + X + VI."),
        ],
        youAreReadyWhen="You can read M, D, C, L, X, V, I in a year such as MMXX (2020) with a key.",
        householdItems=["Key card including D=500 M=1000", "A year on a book copyright if you have one"],
        setup="Extend the Y4 key. Write MMXVI.",
        activityTitle="Build a year",
        steps=["Build 1000, 500, 100.","Build 2016 as MM XVI with the X.","Read a copyright year if available.","Contrast 2016 with 2,016 in place value (the 0)."],
        check=[
            chk("M.", "1,000.", "100 or 2,000.", "M is 1,000."),
            chk("CM.", "900.", "1,100.", "C before M subtracts 100 from 1,000."),
            chk("MMXX.", "2020.", "2010 or 2022.", "Two thousands and two tens."),
        ],
        stretch="A building stone: MDCCCLXVI (1866) only if they enjoy the puzzle — not required tonight.",
    ),
    t(
        id="y5-written-add-subtract-large",
        year=5,
        strand="Addition and subtraction",
        title="Add and subtract more than 4 digits",
        shortTitle="Large +/−",
        summary="Compact written add and subtract with more than 4 digits, mental jottings with large numbers, and rounding to check.",
        prerequisites=["y5-rounding-large-numbers"],
        statutoryOutcomes=[
            "Add and subtract whole numbers with more than 4 digits, including using formal written methods (columnar addition and subtraction)",
            "Add and subtract numbers mentally with increasingly large numbers",
            "Use rounding to check answers to calculations and determine, in the context of a problem, levels of accuracy",
        ],
        whyThisMatters="Multi-step word problems are unforgiving if the add itself is wobbly. Rounding is the sanity check.",
        inPlainEnglish="Same exchanging as always, more columns. Mental: 12,462 − 2,300 by subtracting 2 thousand and 3 hundred. Check 24,819 + 5,076 against 25,000 + 5,000.",
        howSchoolTeachesIt="Compact columns, plus mental place-value subtracts. Multi-step stories with a bar model.",
        sayThis=["Estimate with rounded numbers first.", "Which method: mental jotting or full columns?", "Does the answer sit near the estimate?"],
        avoidThis=["Columns for 12,462 − 2,300 if they can do it mentally.", "Checking by rewriting the same errors neatly."],
        misconceptions=[
            mis("They subtract 2,300 from 12,462 as 10,162 but then doubt it because it felt too easy.", "Easy can be right.", "2 thousand off, then 3 hundred off. Keep both."),
            mis("They round to check but then ‘fix’ the exact answer to match the estimate.", "Estimate is a magnet, not the answer.", "The exact answer should be near, not identical, unless you rounded to the same."),
        ],
        youAreReadyWhen="You can complete one large column add, one mental large subtract, and say whether they fit the estimates.",
        householdItems=["Column paper", "A two-step story: stadium 12,462, 2,300 leave, 1,150 arrive"],
        setup="Estimate 12,462 − 2,300 ≈ 10,000. Then exact.",
        activityTitle="Mental, written, story",
        steps=["Mental: 12,462 − 2,300.","Written: 24,819 + 5,076 with estimate.","Story with two steps.","Check one with inverse."],
        check=[
            chk("12,462 − 2,300.", "10,162.", "10,262 or 12,162.", "Subtract 2 thousands then 3 hundreds."),
            chk("Estimate 24,819 + 5,076.", "About 30,000.", "25,000 exactly as the answer.", "25,000+5,000."),
            chk("If 1,150 then arrive at 10,162, new total?", "11,312.", "9,012.", "Add the arrivals."),
        ],
        stretch="A third step: 480 complimentary tickets. Subtract.",
    ),
    t(
        id="y5-factors-multiples-primes",
        year=5,
        strand="Multiplication and division",
        title="Factors, multiples and primes",
        shortTitle="Factors and primes",
        summary="Find factor pairs and common factors, know prime numbers to 19, and test whether a number to 100 is prime.",
        prerequisites=["y5-numbers-to-a-million"],
        statutoryOutcomes=[
            "Identify multiples and factors, including finding all factor pairs of a number, and common factors of 2 numbers",
            "Know and use the vocabulary of prime numbers, prime factors and composite (non-prime) numbers",
            "Establish whether a number up to 100 is prime and recall prime numbers up to 19",
        ],
        readyToProgress=["5MD-2"],
        whyThisMatters="Fractions, division and later algebra all sit on factors. Prime is not a personality type; it is ‘exactly two factors: 1 and itself’.",
        inPlainEnglish="Multiple of 6: 6, 12, 18… Factor of 12: 1,2,3,4,6,12. Common factors of 12 and 18 include 1,2,3,6. Prime: 2,3,5,7,11,13,17,19… 1 is not prime. 4 is composite.",
        howSchoolTeachesIt="Arrays, factor bugs, sieve talk. Prime factors such as 12 = 2×2×3 once the idea of prime is in.",
        sayThis=["List factor pairs of 24.", "Is 1 prime? Why not?", "A common factor of 12 and 18 that is not 1?"],
        avoidThis=["Saying 1 is prime.", "Calling even numbers all composite — 2 is prime."],
        misconceptions=[
            mis("They think 9 is prime because it is odd.", "Odd ≠ prime.", "3×3 = 9. More than two factors."),
            mis("They miss 1 and the number itself as factors.", "Factors feel like ‘proper splits only’.", "1×24 is a pair. Include it."),
        ],
        youAreReadyWhen="You can list factors of a number such as 24, name a common factor of two numbers, and say whether 21 is prime.",
        householdItems=["24 objects", "Paper for a factor rainbow"],
        setup="24 objects. Rainbow: pairs that multiply to 24.",
        activityTitle="Rainbow, then primes",
        steps=["Pairs of 24: 1×24, 2×12, 3×8, 4×6.","Common factors of 12 and 18 with two rainbows.","Test 21: 3×7, not prime. Recite primes to 19.","Is 2 prime? Yes — even and prime."],
        check=[
            chk("Primes to 19.", "2,3,5,7,11,13,17,19.", "Includes 1, 9 or 15.", "Exactly two factors."),
            chk("Is 21 prime?", "No — 3×7.", "Yes because odd.", "Find a factor other than 1 and 21."),
            chk("Common factors of 12 and 18.", "1,2,3,6.", "Only 6, or 9.", "Both rainbows share those."),
        ],
        stretch="Prime factors of 12: 2×2×3.",
    ),
    t(
        id="y5-squares-and-cubes",
        year=5,
        strand="Multiplication and division",
        title="Square and cube numbers",
        shortTitle="Squares and cubes",
        summary="Recognise square and cube numbers and the notation ² and ³, using arrays and cubes you can build.",
        prerequisites=["y5-factors-multiples-primes"],
        statutoryOutcomes=["Recognise and use square numbers and cube numbers, and the notation for squared (²) and cubed (³)"],
        whyThisMatters="Area of squares and volume of cubes later use this. 5² is 5×5, not 5×2.",
        inPlainEnglish="A square number makes a square array: 1,4,9,16,25… 5² = 25. A cube number makes a cube: 1,8,27,64… 3³ = 27.",
        howSchoolTeachesIt="Build squares and cubes. Link ² to area of a square, ³ to volume. They still multiply, they do not ‘add the little 2’.",
        sayThis=["Show 4² as a square of 4 by 4.", "Why is 5² not 10?", "Build 2³ with 8 small cubes if you have them."],
        avoidThis=["Reading 5² as 5×2.", "Calling every even number a square."],
        misconceptions=[
            mis("5² = 10.", "The small 2 looks like ×2.", "Two 5s multiplied, 5 rows of 5."),
            mis("They think 8 is square because 2×2×2.", "That is cube.", "8 is 2³. The square would be 2²=4 or 3²=9."),
        ],
        youAreReadyWhen="You can explain 6² and 2³ with a picture and list square numbers to 100.",
        householdItems=["Objects for a 5-by-5 array", "Optional: 8 cubes or sugar cubes"],
        setup="Make 3×3 and 4×4 squares.",
        activityTitle="Squares then a small cube",
        steps=["Build 3²=9, 4²=16, 5²=25. Write notation.","List 1,4,9,16,25,36… toward 100.","Build 2³=8.","Say 3³=27 without building all 27 if short on cubes — 3 layers of 9."],
        check=[
            chk("7².", "49.", "14.", "7×7."),
            chk("2³.", "8.", "6.", "2×2×2."),
            chk("Is 20 a square number?", "No.", "Yes, because even.", "No whole number times itself is 20."),
        ],
        stretch="Which is larger, 5² or 2⁵ if they ask — 2⁵ is Year 6/KS3. Stay with 5² vs 3³ (25 vs 27).",
    ),
    t(
        id="y5-long-multiplication",
        year=5,
        strand="Multiplication and division",
        title="Multiply 4-digit by 1-digit and 2-digit numbers",
        shortTitle="Long multiplication",
        summary="Short multiplication by one digit, then long multiplication by two digits as 10s and 1s, joined.",
        prerequisites=["y5-factors-multiples-primes"],
        statutoryOutcomes=["Multiply numbers up to 4 digits by a one- or two-digit number using a formal written method, including long multiplication for two-digit numbers"],
        readyToProgress=["5MD-3"],
        whyThisMatters="24 × 36 is 24×30 plus 24×6. The compact long-multiplication layout is that split. A missing place-holder zero is a ten-times error.",
        inPlainEnglish="First multiply by the ones, then by the tens (that product is 10 times as big), then add. Grid method is the same maths.",
        howSchoolTeachesIt="Grid, expanded, then compact long multiplication. Estimate first. They still talk 3 tens, not ‘add a zero’ empty-handed.",
        sayThis=["Estimate 24 × 36.", "24 × 6, then 24 × 30. Where do we write the 24 × 30?", "Add the two products."],
        avoidThis=["A compact layout with no expanded or grid beside it the first time.", "Missing the 0 in the ones place of the tens product."],
        misconceptions=[
            mis("They do 24×3 and 24×6 and add, forgetting the 3 is 3 tens.", "Tens not scaled.", "24×30 is 720, not 72."),
            mis("They add as they go and lose a column.", "Two products must both be complete first.", "Write both rows, then add."),
        ],
        youAreReadyWhen="You can compute 24 × 36 with a grid or long multiplication and explain the tens row.",
        householdItems=["Paper", "A grid drawn 20+4 against 30+6"],
        setup="Estimate 25×40=1,000. Then 24×36.",
        activityTitle="Grid, then long layout",
        steps=["Fill grid: 20×30, 20×6, 4×30, 4×6. Total.","Write compact: 24×6, then 24×30 with 0 in ones.","Add. Compare to 1,000.","A 4-digit × 1-digit: 2,146 × 3 as a short multiply."],
        check=[
            chk("24 × 10.", "240.", "24 or 2400.", "Each digit one place up."),
            chk("24 × 36 via 24×30 and 24×6.", "720+144=864.", "168 or 72+24.", "Tens product is 720."),
            chk("Why a 0 on the tens row?", "We multiplied by 3 tens, so ones place is empty (0).", "To make it look like school.", "Place holder for ones."),
        ],
        stretch="146 × 12.",
    ),
    t(
        id="y5-short-division",
        year=5,
        strand="Multiplication and division",
        title="Short division and interpreting remainders",
        shortTitle="Short division",
        summary="Divide numbers up to 4 digits by a 1-digit number, and interpret remainders as leftover, extra groups, fractions or rounding — matching the story.",
        prerequisites=["y5-long-multiplication"],
        statutoryOutcomes=["Divide numbers up to 4 digits by a one-digit number using the formal written method of short division and interpret remainders appropriately for the context"],
        readyToProgress=["5MD-4"],
        whyThisMatters="The same 98 ÷ 4 can be 24 r 2, 24 1/2, 24.5 or 25 taxis. The story decides.",
        inPlainEnglish="Short division (bus stop) shares hundreds, then tens, then ones, carrying leftovers to the next place. Then ask what the remainder means.",
        howSchoolTeachesIt="Concrete sharing, then bus stop. They practise remainder as r, as a fraction, as a decimal, as round up — not all in one night, but the idea of choosing.",
        sayThis=["How many 4s in this place? What is left for the next place?", "What does the leftover mean in this story?", "Would we round up (taxis) or leave a remainder (leftover cakes)?"],
        avoidThis=["Always rounding the remainder up.", "Decimals for every remainder tonight."],
        misconceptions=[
            mis("They write a remainder larger than the divisor.", "Not enough groups taken.", "Leftover must be smaller than the number you divide by."),
            mis("They ignore zeros in the middle, so 408 ÷ 4 becomes 12.", "Empty tens not held.", "4 into 0 tens is 0. Write it."),
        ],
        youAreReadyWhen="You can complete a short division such as 98 ÷ 4 and say two different remainder meanings.",
        householdItems=["Paper", "98 objects only if you want a tiny version (use 14 ÷ 4 as objects, 98 on paper)"],
        setup="Warm up 14 ÷ 4 with objects. Then 98 ÷ 4 on paper.",
        activityTitle="Share, bus stop, two stories",
        steps=["14 objects ÷ 4: 3 r 2.","98 ÷ 4 short division.","Story A: leftover cakes. Story B: 98 people, 4 per taxi — how many taxis?","Try 408 ÷ 4 watching the 0."],
        check=[
            chk("98 ÷ 4.", "24 r 2, or 24.5 / 24 1/2.", "23 r 6.", "4×24=96, remainder 2."),
            chk("Taxis for 98 people, 4 seats.", "25 taxis.", "24.", "The 2 people still need a taxi."),
            chk("408 ÷ 4.", "102.", "12 or 1002.", "Hold the 0 tens: 4 into 08."),
        ],
        stretch="98 ÷ 4 as money £98 shared by 4: £24.50 if they have decimal money.",
    ),
    t(
        id="y5-multiply-divide-by-10-100-1000",
        year=5,
        strand="Multiplication and division",
        title="Multiply and divide by 10, 100 and 1,000, including decimals",
        shortTitle="× ÷ 10, 100, 1,000",
        summary="Digits move one, two or three places; tenths and hundredths appear when you divide ones.",
        prerequisites=["y5-powers-of-10"],
        statutoryOutcomes=["Multiply and divide whole numbers and those involving decimals by 10, 100 and 1,000"],
        readyToProgress=["5MD-1"],
        whyThisMatters="Metric conversion and decimal place value are this move. Empty ‘add zeros’ breaks as soon as 3.4 × 10 is needed.",
        inPlainEnglish="3.4 × 10 = 34: the 3 ones become 3 tens, the 4 tenths become 4 ones. 3.4 ÷ 10 = 0.34. ×100 is two places, ×1,000 three.",
        howSchoolTeachesIt="Sliders with a decimal point that stays in the chart while digits move (or some schools move the point — follow school, but meaning is 10 times the size).",
        sayThis=["10 times the size — which way do digits move on this chart?", "3.4 × 10.", "Why is 0.5 × 10 equal to 5?"],
        avoidThis=["Moving the point with no idea of size.", "Adding zeros to 3.4 × 10 to get 3.40 as if that multiplied."],
        misconceptions=[
            mis("3.4 × 10 = 3.40.", "They added a cosmetic zero.", "The 4 must leave the tenths. 34."),
            mis("0.5 × 10 = 0.50 or 0.05.", "Wrong direction.", "5 tenths times 10 is 5 ones."),
        ],
        youAreReadyWhen="You can × and ÷ by 10 and 100 with at least one decimal starting number, naming the new places.",
        householdItems=["Chart: Th H T O . t h th", "Digit cards including a 3 and 4"],
        setup="Place 3.4 on the chart.",
        activityTitle="Slide 3.4",
        steps=["×10, ×100, ×1,000 from 3.4.","÷10, ÷100 from 3.4.","Round trip: 5 × 100 ÷ 100.","3 mm in metres as ÷1,000 if they want a measure story."],
        check=[
            chk("3.4 × 10.", "34.", "3.40 or 3.4.0.", "One place toward the larger places."),
            chk("6 ÷ 100.", "0.06.", "0.6 or 6/100 written 0.60 as six tenths.", "6 hundredths."),
            chk("0.5 × 10.", "5.", "0.05 or 50.", "5 tenths become 5 ones."),
        ],
        stretch="Convert 4.5 km to metres.",
    ),
    t(
        id="y5-equivalent-and-mixed-fractions",
        year=5,
        strand="Fractions",
        title="Equivalent fractions, mixed numbers and improper fractions",
        shortTitle="Equivalent and mixed",
        summary="Find equivalent fractions including tenths and hundredths, and convert mixed numbers and improper fractions both ways.",
        prerequisites=["y5-factors-multiples-primes"],
        statutoryOutcomes=[
            "Identify, name and write equivalent fractions of a given fraction, represented visually, including tenths and hundredths",
            "Recognise mixed numbers and improper fractions and convert from one form to the other",
        ],
        readyToProgress=["5F-2"],
        whyThisMatters="You cannot add 1/2 and 1/5 until they share a denominator. Mixed vs improper is how answers bigger than 1 get written.",
        inPlainEnglish="3/5 = 6/10 = 60/100. 2/5 + 4/5 = 6/5 = 1 1/5. Convert by grouping denominators into wholes, or exploding wholes into parts.",
        howSchoolTeachesIt="Walls, 100-squares, then multiply/divide by the same number. Convert with diagrams then a compact method.",
        sayThis=["What do we multiply top and bottom by to make tenths?", "6/5 is how many wholes and leftover?", "1 3/4 as quarters only?"],
        avoidThis=["Cancelling across an add (the later crime).", "Converting without a picture the first time tonight."],
        misconceptions=[
            mis("3/5 = 3/10 because they doubled only the bottom.", "One number changed.", "Both parts of the fraction scale together."),
            mis("2 3/4 as 5/4 (added 2+3).", "The 2 wholes are 8 quarters, not 2 quarters.", "2 = 8/4, plus 3/4 = 11/4."),
        ],
        youAreReadyWhen="You can write 3/5 as tenths and hundredths, and convert 7/4 and 2 1/3 both ways.",
        householdItems=["100-square", "Strips for fifths and tenths"],
        setup="Shade 3/5 on a 5-strip and on a 10-strip.",
        activityTitle="Scale, then convert",
        steps=["3/5 = 6/10 = 60/100.","7/4 = 1 3/4 on two strips.","2 1/3 = 7/3.","Write 6/5 as 1 1/5."],
        check=[
            chk("3/5 as tenths.", "6/10.", "3/10.", "×2 top and bottom."),
            chk("11/4 as mixed.", "2 3/4.", "1 3/4 or 11/4 left only.", "8/4=2, remainder 3/4."),
            chk("1 2/5 as improper.", "7/5.", "3/5.", "5/5+2/5."),
        ],
        stretch="Place 1 3/5 on a line between 1 and 2.",
    ),
    t(
        id="y5-add-subtract-related-fractions",
        year=5,
        strand="Fractions",
        title="Add and subtract fractions with related denominators",
        shortTitle="Related denominators",
        summary="When one denominator is a multiple of the other, convert so the pieces match, then add or subtract — including mixed numbers.",
        prerequisites=["y5-equivalent-and-mixed-fractions"],
        statutoryOutcomes=[
            "Compare and order fractions whose denominators are all multiples of the same number",
            "Add and subtract fractions with the same denominator, and denominators that are multiples of the same number",
        ],
        whyThisMatters="This is the last step before any two denominators in Year 6. Related fractions keep the picture honest.",
        inPlainEnglish="1/2 + 1/8: eighths fit into halves (1/2 = 4/8), so 4/8 + 1/8 = 5/8. Compare 3/4 and 5/8 by converting to eighths.",
        howSchoolTeachesIt="Bars with extra splits. Common denominator is the larger one when it is a multiple. Mixed numbers: convert or add wholes then parts.",
        sayThis=["Which piece size will both fractions fit?", "1/2 as eighths?", "Is 3/4 larger than 5/8?"],
        avoidThis=["Adding 1/2 + 1/8 = 2/10.", "Lowest common multiple language before the picture, unless they are ready."],
        misconceptions=[
            mis("1/2 + 1/8 = 2/10.", "Add tops, add bottoms.", "Same size pieces first."),
            mis("They convert 1/2 to 1/8.", "They copied the denominator only.", "1/2 is 4/8, not 1/8."),
        ],
        youAreReadyWhen="You can add 1/2 and 1/8, subtract 5/6 − 1/3, and compare 3/4 and 5/8.",
        householdItems=["Two equal bars, one split in 2 then each half in 4 (eighths)"],
        setup="Make eighths from a half-bar.",
        activityTitle="Split the half",
        steps=["1/2 + 1/8.","5/6 − 1/3 (1/3=2/6).","Compare 3/4 and 5/8.","1 1/2 + 3/4 if keen (convert 1 1/2 = 6/4, +3/4=9/4=2 1/4)."],
        check=[
            chk("1/2 + 1/8.", "5/8.", "2/10 or 1/10.", "4/8+1/8."),
            chk("1/3 + 1/6.", "1/2 or 3/6.", "2/9.", "2/6+1/6."),
            chk("Larger: 3/4 or 5/8.", "3/4 (6/8).", "5/8.", "Convert to eighths."),
        ],
        stretch="2/3 + 5/6 = 9/6 = 1 1/2.",
    ),
    t(
        id="y5-multiply-fractions-by-wholes",
        year=5,
        strand="Fractions",
        title="Multiply proper fractions and mixed numbers by whole numbers",
        shortTitle="Fractions × whole",
        summary="Repeated equal groups of a fraction, with bars, then a compact method.",
        prerequisites=["y5-add-subtract-related-fractions"],
        statutoryOutcomes=["Multiply proper fractions and mixed numbers by whole numbers, supported by materials and diagrams"],
        whyThisMatters="This is ‘4 groups of 2/3’ and also ‘2/3 of 4’ in many schools — same product, two stories. Keep the bar so it does not become multiply-everything.",
        inPlainEnglish="4 × 2/3 is four lots of two thirds: 8/3 = 2 2/3. You can think 8 thirds. Mixed: 3 × 1 1/4 = 3 + 3/4 = 3 3/4, or convert 5/4 × 3 = 15/4.",
        howSchoolTeachesIt="Bars repeated, number lines, then numerator × whole, denominator stays (for proper × whole). They connect to fractions of quantities.",
        sayThis=["Four lots of two thirds — how many thirds?", "Is this the same as 2/3 of 4?", "1 1/4 three times — three wholes and three quarters?"],
        avoidThis=["Multiplying denominators as well when the other factor is a whole number, unless converting mixed first in a way that needs it.", "Skipping the bar."],
        misconceptions=[
            mis("4 × 2/3 = 8/12.", "Both parts ×4.", "Four lots of thirds: 8 thirds, still thirds."),
            mis("They do 4 × 1 1/4 as 4 1/4.", "They scaled only the whole.", "Each of 4 groups has 1 and 1/4."),
        ],
        youAreReadyWhen="You can work 4 × 2/3 and 3 × 1 1/4 with a bar and a written form.",
        householdItems=["Paper bars in thirds and quarters"],
        setup="A bar in thirds. You will draw it four times.",
        activityTitle="Repeat the bar",
        steps=["Shade 2/3 four times. Count 8/3 = 2 2/3.","Connect to 2/3 of 4 on four wholes.","3 × 1 1/4 with mixed numbers.","Write 5/4 × 3 = 15/4."],
        check=[
            chk("3 × 2/5.", "6/5 or 1 1/5.", "6/15.", "Six fifths."),
            chk("2/3 of 12.", "8.", "4 or 18.", "12 split into 3 is 4, two parts 8."),
            chk("2 × 1 3/4.", "3 1/2 or 7/2.", "2 3/4.", "Two wholes and six quarters."),
        ],
        stretch="A recipe: 1 1/2 cups, three times.",
    ),
    t(
        id="y5-decimals-to-3dp",
        year=5,
        strand="Fractions",
        title="Thousandths and decimals to 3 decimal places",
        shortTitle="Decimals to 3 dp",
        summary="Read, write, order and round decimals with up to 3 decimal places, relating thousandths to tenths and hundredths.",
        prerequisites=["y5-multiply-divide-by-10-100-1000"],
        statutoryOutcomes=[
            "Read and write decimal numbers as fractions",
            "Recognise and use thousandths and relate them to tenths, hundredths and decimal equivalents",
            "Round decimals with 2 decimal places to the nearest whole number and to 1 decimal place",
            "Read, write, order and compare numbers with up to 3 decimal places",
        ],
        readyToProgress=["5NPV-3"],
        whyThisMatters="Measures already use 3 dp (1.275 kg). Rounding money to 2 dp is a later habit; tonight is place value.",
        inPlainEnglish="0.007 is 7 thousandths. 0.07 is 7 hundredths. 0.7 is 7 tenths. 0.46 as a fraction is 46/100. Round 2.46 to 1 dp by looking at the hundredths: 6 ≥ 5 so 2.5.",
        howSchoolTeachesIt="Charts to thousandths, number lines, and 0.71 = 71/100. Complements to 1 such as 0.83 + 0.17.",
        sayThis=["Which is larger, 0.07 or 0.007?", "0.71 as hundredths?", "Round 2.46 to one decimal place."],
        avoidThis=["Saying 0.07 is 7 tenths.", "Rounding 2.45 to 2.4 ‘because we round even’ — primary convention is 5 up unless school says otherwise."],
        misconceptions=[
            mis("0.07 > 0.2 because 7 > 2.", "Digit size.", "2 tenths is 0.20, more than 0.07."),
            mis("They round 2.46 to 2.5 and also to 3 if asked nearest whole, confusing the look-at digit.", "Nearest whole looks at tenths (4), so 2.", "Name the place you round to first."),
        ],
        youAreReadyWhen="You can order 0.7, 0.07, 0.707 and round a 2 dp number to 1 dp and to the nearest whole.",
        householdItems=["Chart O . t h th", "Line from 2.4 to 2.5 in hundredths"],
        setup="Place 2.46 on the chart and on the line.",
        activityTitle="Places, then round",
        steps=["Order 0.7, 0.07, 0.707.","Write 0.71 as 71/100.","Round 2.46 to 1 dp and to nearest whole.","0.83 + 0.17 = 1 as complements."],
        check=[
            chk("0.07 vs 0.007 — larger?", "0.07.", "0.007.", "Hundredths vs thousandths."),
            chk("2.46 to 1 dp.", "2.5.", "2.4 or 2.50 as if unrounded.", "6 hundredths → up."),
            chk("2.46 to nearest whole.", "2.", "2.5 or 3.", "4 tenths, below 5."),
        ],
        stretch="1.275 kg to the nearest 0.01 kg (2 dp).",
    ),
    t(
        id="y5-percentages",
        year=5,
        strand="Fractions",
        title="Percentages as parts per hundred",
        shortTitle="Percentages",
        summary="Per cent means parts per 100. Link 50%, 25%, 10%, 1% to fractions and decimals.",
        prerequisites=["y5-decimals-to-3dp"],
        statutoryOutcomes=[
            "Recognise the per cent symbol (%) and understand that per cent relates to ‘number of parts per hundred’, and write percentages as a fraction with denominator 100, and as a decimal fraction",
            "Solve problems which require knowing percentage and decimal equivalents of 1/2, 1/4, 1/5, 2/5, 4/5 and those fractions with a denominator of a multiple of 10 or 25",
        ],
        readyToProgress=["5F-3"],
        whyThisMatters="Year 6 will find 15% of amounts. Year 5 is the meaning and the benchmarks.",
        inPlainEnglish="100% is the whole. 1% is 1/100. 50% = 1/2 = 0.5. 25% = 1/4 = 0.25. 20% = 1/5 = 0.2. 40% = 2/5.",
        howSchoolTeachesIt="100-square, then known fraction equivalents. They solve simple ‘what % is shaded’ before ‘% of 360’.",
        sayThis=["How many hundredths is 25%?", "50% of this bar?", "1/5 as a percentage?"],
        avoidThis=["Finding 17% of 83 as the first task.", "Saying % is just a plus-shaped decoration."],
        misconceptions=[
            mis("They think 5% is 1/5.", "5 and fifth collide.", "1/5 is 20%. 5% is 5/100 = 1/20."),
            mis("They think 100% of 40 is 100.", "They replaced the amount with 100.", "100% is all of the 40, so 40."),
        ],
        youAreReadyWhen="You can write 25%, 50%, 20% as fractions and decimals, and shade a % on a 100-square.",
        householdItems=["100-square", "A bar as ‘the whole’"],
        setup="100-square is 100%.",
        activityTitle="Benchmarks on 100",
        steps=["Shade 50, 25, 10, 1. Name % , fraction, decimal.","1/5 = 20 squares = 20%.","40% = 2/5.","100% of 12 raisins is 12; 50% is 6."],
        check=[
            chk("25% as a fraction.", "1/4 or 25/100.", "1/25.", "25 hundredths."),
            chk("1/5 as %.", "20%.", "5% or 15%.", "20/100."),
            chk("50% of 18.", "9.", "50 or 8.", "Half."),
        ],
        stretch="10% of 40, then 5% as half of that.",
    ),
    t(
        id="y5-metric-and-imperial",
        year=5,
        strand="Measurement",
        title="Metric conversion and common imperial equivalents",
        shortTitle="Metric and imperial",
        summary="Convert metric units using × ÷ 10, 100, 1,000, and know rough imperial equivalents such as inches, pounds and pints.",
        prerequisites=["y5-multiply-divide-by-10-100-1000"],
        statutoryOutcomes=[
            "Convert between different units of metric measure",
            "Understand and use approximate equivalences between metric units and common imperial units such as inches, pounds and pints",
        ],
        readyToProgress=["5NPV-5"],
        whyThisMatters="Recipes and road signs still mix systems. Approximation is the statutory skill, not a 12-inch conversion table memorised to 3 dp.",
        inPlainEnglish="1 m = 100 cm = 1,000 mm. 1 kg = 1,000 g. 1 l = 1,000 ml. About 2.5 cm in an inch, about 450 g in a pound, about 570 ml in a pint — use school’s poster numbers.",
        howSchoolTeachesIt="Place-value conversion for metric. A few benchmark imperial facts, not a full dual curriculum.",
        sayThis=["Bigger unit to smaller: multiply.", "3.5 kg in grams?", "Is 12 inches closer to 20 cm or 50 cm? (about 30 cm)."],
        avoidThis=["Exact 2.54 cm as the first fact if school says ‘about 2.5’.", "Converting imperial with no benchmark."],
        misconceptions=[
            mis("3.5 kg = 3.5 g or 350 g.", "Wrong factor.", "×1,000 → 3,500 g."),
            mis("They think a pint is a litre.", "Roughly 1/2 litre, not 1.", "About 500–570 ml."),
        ],
        youAreReadyWhen="You can convert 3.5 kg, 2.4 m and 1.2 l, and give a rough inch or pint comparison.",
        householdItems=["A 1 litre bottle", "A ruler with inches if it has them", "Kitchen scales if present"],
        setup="Write metric facts. Note one imperial benchmark from school or ‘about 2.5 cm = 1 inch’.",
        activityTitle="Metric first, then a rough imperial",
        steps=["3.5 kg → g, 45 mm → cm, 2.4 m → cm.","1.2 l in ml.","If the ruler has inches, compare 10 cm to 4 inches (about).","A pint of milk vs a litre bottle: which is more?"],
        check=[
            chk("3.5 kg in g.", "3,500 g.", "350 g.", "×1,000."),
            chk("240 cm in m.", "2.4 m.", "24 m or 0.24 m.", "÷100."),
            chk("About how many cm in 12 inches?", "About 30 cm.", "12 cm or 120 cm.", "12 × 2.5."),
        ],
        stretch="A 5 mile walk is about 8 km if school uses that benchmark — Year 6 will formalise miles–km.",
    ),
    t(
        id="y5-perimeter-composite",
        year=5,
        strand="Measurement",
        title="Perimeter of composite rectilinear shapes",
        shortTitle="Composite perimeter",
        summary="Find missing lengths on an L-shape or stepped shape, then add the outer walk.",
        prerequisites=["y5-metric-and-imperial"],
        statutoryOutcomes=["Measure and calculate the perimeter of composite rectilinear shapes in centimetres and metres"],
        whyThisMatters="Missing lengths are algebra in costume: the long side is the sum of the two shorter parallels.",
        inPlainEnglish="If the bottom is 12 cm and a notch takes 4 cm, the remaining outer piece is 8 cm. Add every outer edge once. Do not add inner cuts that are not fences.",
        howSchoolTeachesIt="Label all sides, find missing ones from parallels, then add. They may write 4 + 2b = 20 as a missing length.",
        sayThis=["Which sides are parallel and share a total length?", "Is this edge outer or an inner cut?", "Walk it with a finger."],
        avoidThis=["Adding the given numbers only and hoping.", "Using area numbers for perimeter."],
        misconceptions=[
            mis("They include the internal line where two rectangles were glued.", "That line is not a fence.", "Only the outline."),
            mis("They double-count a long side that was already the sum of parts.", "Labelling twice.", "Each outer edge once."),
        ],
        youAreReadyWhen="You can find at least one missing length on an L-shape and the perimeter.",
        householdItems=["Squared paper", "An L: 10 by 6 rectangle with a 4 by 3 rectangle missing from a corner"],
        setup="Draw the L with some lengths missing.",
        activityTitle="Label, fill, walk",
        steps=["Mark every vertex.","Find missing lengths from opposites.","Add the outer walk.","Check by string around a book-L made of two cards if you want."],
        check=[
            chk("Long side 10, two parts 4 and ?", "6.", "14.", "10 − 4."),
            chk("Do we add the inner glue line?", "No.", "Yes.", "Not an outer fence."),
            chk("Units.", "cm (or m), not cm².", "cm².", "Perimeter is length."),
        ],
        stretch="Express a rectangle perimeter as 2(l+w) after adding four sides once.",
    ),
    t(
        id="y5-area-of-rectangles",
        year=5,
        strand="Measurement",
        title="Area of rectangles, including squares",
        shortTitle="Area of rectangles",
        summary="Calculate area in cm² and m² using length × width, and estimate irregular areas by counting squares.",
        prerequisites=["y5-perimeter-composite"],
        statutoryOutcomes=["Calculate and compare the area of rectangles (including squares), including using standard units, and estimate the area of irregular shapes"],
        readyToProgress=["5G-2"],
        whyThisMatters="Counting squares in Y4 becomes a multiplication. Comparing area and perimeter of the same rectangle stops the mix-up.",
        inPlainEnglish="A 7 cm by 4 cm rectangle covers 28 square centimetres. You can see 7 rows of 4 squares. Irregular lakes: count full squares, then guess the almost-full ones.",
        howSchoolTeachesIt="Arrays of 1 cm², then formula in words. They compare two rectangles’ areas and estimate blobs on squared paper.",
        sayThis=["How many 1 cm squares would cover this?", "Why cm² not cm?", "This blob: full squares plus about how many bits?"],
        avoidThis=["Using 2(l+w) for area.", "Saying square cm for perimeter."],
        misconceptions=[
            mis("Area of 7 by 4 is 22 (perimeter).", "The mix-up.", "Fill, don’t walk."),
            mis("They think a longer skinnier rectangle always has larger area.", "One length dominates.", "1×12=12, 3×4=12. Same area, different shape."),
        ],
        youAreReadyWhen="You can calculate two rectangle areas in cm², compare them, and roughly count an irregular shape.",
        householdItems=["Squared paper (1 cm if possible)", "A 7 by 4 rectangle and a blob"],
        setup="Draw 7 by 4 and a potato-shape blob.",
        activityTitle="Array, formula, blob",
        steps=["Count 28 squares. Say 7×4.","A 5 cm by 5 cm square: 25 cm².","Compare areas.","Blob: full + half-ish squares."],
        check=[
            chk("6 cm by 3 cm area.", "18 cm².", "18 cm or 18.", "× , square units."),
            chk("Perimeter of that rectangle.", "18 cm.", "18 cm².", "6+3+6+3. Coincidence that numbers match 18 — talk about that trap."),
            chk("Which is larger area: 2×10 or 4×6?", "4×6=24 vs 20.", "2×10 because 10 is long.", "Multiply."),
        ],
        stretch="Missing side: area 24 cm², one side 8 cm. Other side 3 cm.",
    ),
    t(
        id="y5-volume-of-cubes",
        year=5,
        strand="Measurement",
        title="Volume as cubes, capacity as pours",
        shortTitle="Volume and capacity",
        summary="Build cuboids from 1 cm cubes and estimate volume; compare with capacity in ml using water if you have it.",
        statutoryOutcomes=["Estimate volume, for example using 1 cm³ blocks to build cuboids, and capacity, for example using water"],
        whyThisMatters="Year 6 will use l×w×h. Year 5 should feel 12 cubes as 12 cm³, not jump to a formula empty-handed.",
        inPlainEnglish="Volume is how much space a solid takes. 1 cm³ is a cube 1 cm on each edge. Capacity is how much a container holds — millilitres of water. Related, not identical language.",
        howSchoolTeachesIt="Multilink / centimetre cubes, then a jug. They count layers: 3 by 2 by 2 = 12 cubes.",
        sayThis=["How many cubes in one layer? How many layers?", "Is volume the inside fill or the cubes we built?", "This cup holds about how many ml?"],
        avoidThis=["l×w×h before they count layers.", "Calling 12 cubes 12 cm."],
        misconceptions=[
            mis("They count only the faces they can see.", "Hidden cubes.", "Build it. Count every cube, including inside."),
            mis("They think 100 ml is 100 cm³ as a fact they ‘should feel’ without a note — actually 1 ml = 1 cm³, but only say it if school does.", "A true fact can still be assumed too early.", "Tonight count cubes and pour separately unless school has linked them."),
        ],
        youAreReadyWhen="You can count the cubes in a small cuboid by layers and make a rough capacity estimate with a bottle.",
        householdItems=["12 sugar cubes or Lego bricks of one size", "A 500 ml bottle"],
        setup="Build 3 by 2 by 2.",
        activityTitle="Layers, then a pour",
        steps=["Count one layer (6), two layers (12). Say 12 cubes.","Build a different cuboid with 12.","Pour to half a 500 ml bottle: about 250 ml.","Talk volume vs capacity in one sentence."],
        check=[
            chk("2 by 2 by 3 cubes.", "12.", "7 (faces) or 8.", "Layers."),
            chk("Unit for cube volume in school.", "Usually cm³.", "cm.", "Cubic centimetres."),
            chk("Half of 1 litre in ml.", "500 ml.", "50 or 1/2 ml.", "1,000 ml in a litre."),
        ],
        stretch="If school has linked ml and cm³, a 1 cm³ cube displaces about 1 ml.",
    ),
    t(
        id="y5-angles-in-degrees",
        year=5,
        strand="Geometry",
        title="Angles in degrees",
        shortTitle="Angles in degrees",
        summary="Estimate and measure acute, obtuse and reflex angles, and use 90°, 180°, 360° facts.",
        statutoryOutcomes=[
            "Know angles are measured in degrees: estimate and compare acute, obtuse and reflex angles",
            "Draw given angles, and measure them in degrees",
            "Identify angles at a point and 1 whole turn (total 360°); angles at a point on a straight line (total 180°); other multiples of 90°",
        ],
        readyToProgress=["5G-1"],
        whyThisMatters="Missing-angle problems are just these facts. A protractor without 90/180/360 is a guessing stick.",
        inPlainEnglish="A right angle is 90°. Straight line 180°. Full turn 360°. Acute < 90. Obtuse between 90 and 180. Reflex more than 180. Measure from 0 on the protractor, not the pretty number you like.",
        howSchoolTeachesIt="Estimate first, then protractor. Angles around a point. Rectangle facts to find missing angles.",
        sayThis=["Estimate: nearer 90 or 180?", "Which 0 did we use on the protractor?", "On a straight line, 110° and a missing angle — what is left?"],
        avoidThis=["Measuring without estimating.", "Always reading the inner scale or always the outer, blindly."],
        misconceptions=[
            mis("They read 60° as 120° from the wrong scale.", "Two scales.", "Start from 0 on the side the angle opens from."),
            mis("They think reflex means ‘backwards’ and measure the small bit.", "They measured the interior they prefer.", "Reflex is the large opening. Estimate: more than a half-turn?"),
        ],
        youAreReadyWhen="You can estimate an angle, measure one acute angle, and find a missing angle on a straight line.",
        householdItems=["A protractor if you have one; if not, a right-angle card and a paper half-turn", "Paper angles"],
        setup="Draw an acute angle, an obtuse, a straight line with 110° marked.",
        activityTitle="Estimate, measure, facts",
        steps=["Estimate the acute. Measure if you have a protractor.","Straight line: 110°, missing = 70°.","Around a point: 90+90+90+? = 360.","A rectangle corner is 90. If one angle of a quad is 90 and an adjacent is 90, talk parallel later — keep to 90 tonight."],
        check=[
            chk("Straight line, 125° marked. Missing?", "55°.", "235° or 35°.", "180−125."),
            chk("Full turn minus a right angle.", "270°.", "180°.", "360−90. That 270 is reflex."),
            chk("Is 95° acute?", "No — obtuse.", "Yes, near 90.", "Just over 90."),
        ],
        stretch="Draw 45° by halving a right angle if no protractor.",
    ),
    t(
        id="y5-3d-from-2d",
        year=5,
        strand="Geometry",
        title="3-D shapes from 2-D pictures, regular polygons",
        shortTitle="3-D from 2-D",
        summary="Identify cubes and cuboids from 2-D drawings, and tell regular from irregular polygons by equal sides and angles.",
        statutoryOutcomes=[
            "Identify 3-D shapes, including cubes and other cuboids, from 2-D representations",
            "Use the properties of rectangles to deduce related facts and find missing lengths and angles",
            "Distinguish between regular and irregular polygons based on reasoning about equal sides and angles",
        ],
        whyThisMatters="Nets and isometric sketches in Year 6 need this. Regular means all sides and all angles equal, not ‘looks even’.",
        inPlainEnglish="A drawing of a cube shows squares that look like parallelograms because of perspective. A regular hexagon has 6 equal sides and 6 equal angles. A rectangle that is not a square is not a regular polygon.",
        howSchoolTeachesIt="Polydron / boxes, isometric dots if they have them, and measuring sides. Missing lengths in rectangles: opposites equal, angles 90°.",
        sayThis=["Could this picture be a cube? What would the hidden faces be?", "Are all sides equal? All angles?", "Opposite sides of a rectangle — what do we know?"],
        avoidThis=["Only naming from a tidy textbook isometric of a cube sitting pretty.", "Calling a rectangle regular."],
        misconceptions=[
            mis("They think a 2-D drawing of a cube is a hexagon because they count the outline.", "Silhouette vs faces.", "Talk about faces you would see if you held the box."),
            mis("Regular means ‘common’ (a regular everyday pentagon that’s irregular mathematically).", "English vs maths.", "Regular = equal sides and equal angles."),
        ],
        youAreReadyWhen="You can say whether a polygon is regular and identify a cube vs cuboid from a simple drawing or object.",
        householdItems=["A cube-ish box and a long cereal cuboid", "Paper polygons: square, rectangle, jagged pentagon, careful hexagon"],
        setup="Objects plus paper shapes.",
        activityTitle="Hold, then judge regular",
        steps=["Match the cereal box to a 2-D sketch you draw.","Square: regular. Rectangle: not (unless square).","Hexagon: test sides.","Rectangle 8 cm by ?, area 32 cm² → 4 cm. Opposite also 8 and 4."],
        check=[
            chk("Is a non-square rectangle a regular polygon?", "No.", "Yes — four 90°.", "Angles equal but sides not all equal."),
            chk("Cube vs cuboid.", "Cube: square faces. Cuboid: rectangular faces (cube is a special cuboid — follow school).","They swap names.","Feel a face."),
            chk("Opposite sides of rectangle 7 cm and 4 cm. Perimeter?", "22 cm.", "28 or 11.", "7+4+7+4."),
        ],
        stretch="A pentagon with equal sides but a dented angle is not regular.",
    ),
    t(
        id="y5-reflection-and-translation",
        year=5,
        strand="Geometry",
        title="Reflection and translation",
        shortTitle="Reflection and translation",
        summary="Slide a shape or flip it in a line parallel to an axis; the shape stays the same size.",
        statutoryOutcomes=["Identify, describe and represent the position of a shape following a reflection or translation, using the appropriate language, and know that the shape has not changed"],
        whyThisMatters="Congruence language starts here: same shape, same size. Year 6 adds four quadrants and reflection in the axes.",
        inPlainEnglish="Translation: every point slides the same. Reflection: mirror in a line (Year 5 usually parallel to the axes). Distances to the mirror match. It is not a turn.",
        howSchoolTeachesIt="Squared grids, first quadrant, mirrors. They check vertices one by one.",
        sayThis=["Slide or flip?", "Same distance the other side of the mirror line?", "Has the size changed?"],
        avoidThis=["Diagonal mirrors if school has not started them.", "Calling a rotation a reflection because it ‘looks flipped’."],
        misconceptions=[
            mis("They translate by moving each point a different amount to ‘fit’.", "Not a rigid slide.", "One recipe for every vertex."),
            mis("They reflect by copying on the same side of the line.", "They translated instead.", "Cross the line."),
        ],
        youAreReadyWhen="You can translate a triangle 3 right 2 up and reflect a simple shape in a vertical grid line.",
        householdItems=["Squared paper with a vertical mirror line", "A triangle drawn on one side"],
        setup="Grid 0–10. Mirror at x=5 if you use coordinates, or a drawn vertical line.",
        activityTitle="Slide, then flip",
        steps=["Translate the triangle 3 right, 1 up.","Reflect the original in the vertical line, matching distances.","Say the shape has not changed size.","Notice the flip: left and right swapped."],
        check=[
            chk("After 2 up, (3,1) goes to…", "(3,3).", "(5,1) or (3,2) if they add 2 to x.", "Up changes the second number if you use coordinates."),
            chk("A point 2 squares left of a vertical mirror.", "Partner 2 squares right, same height.", "2 down.", "Perpendicular to the mirror."),
            chk("Does reflection change side lengths?", "No.", "Yes, it shrinks.", "Same size, flipped."),
        ],
        stretch="Reflect then translate — order talk, keep it light.",
    ),
    t(
        id="y5-line-graphs-and-timetables",
        year=5,
        strand="Statistics",
        title="Line graphs and timetables",
        shortTitle="Line graphs and tables",
        summary="Read line graphs for comparison, sum and difference, and complete timetables.",
        statutoryOutcomes=[
            "Solve comparison, sum and difference problems using information presented in a line graph",
            "Complete, read and interpret information in tables, including timetables",
        ],
        whyThisMatters="A bus timetable is 24-hour reading plus a table. Missing a row is a real missed bus.",
        inPlainEnglish="A line graph shows how a value changes. Read across to the time, up to the value. A timetable: find the row and column, then how long between two times.",
        howSchoolTeachesIt="Temperature/height graphs and bus/TV timetables. Two-step: how much more, how long is the journey.",
        sayThis=["What is the value at 3 o’clock?", "How much did it rise?", "Which column is the 17:05 bus from our stop?"],
        avoidThis=["Treating a line graph like a bar of categories.", "24-hour minus 12-hour without converting."],
        misconceptions=[
            mis("They subtract times as if they were decimals: 17:05 − 16:50 = 0.55.", "Time is 60 minutes in an hour.", "10 minutes to 17:00, plus 5, is 15 minutes."),
            mis("They read the wrong line of a timetable.", "Row/column mix.", "Finger the stop name and the time header."),
        ],
        youAreReadyWhen="You can read a value from a line graph, find a difference, and read a duration from a simple two-row timetable.",
        householdItems=["A homemade 4-point temperature graph", "A 3-stop mini timetable in 24-hour"],
        setup="Graph plus timetable: Stop A 16:50, Stop B 17:05, Stop C 17:22.",
        activityTitle="Graph difference, then a bus",
        steps=["Read noon temperature vs 8pm. Difference.","Timetable: how long A to C?","A two-step: if the graph rose 4° then fell 7°, net change.","Complete a missing cell in the table."],
        check=[
            chk("16:50 to 17:05.", "15 minutes.", "55 minutes or 1:55.", "Through 17:00."),
            chk("Graph 8 at 9am and 12 at 11am. Rise?", "4.", "20 or 3 hours as the answer.", "Values 12−8."),
            chk("If a cell is blank in a timetable, what do we need?", "The missing time from the pattern or a given duration.", "Guess.", "Use the other times in the row."),
        ],
        stretch="A line graph with a scale of 4. Read a point halfway between lines.",
    ),
]
