import { ks1Year2Draft } from "@/content/england/ks1/year-2/maths/draft";
import type { Topic } from "@/content/schema";

export const year2MathsTopics: Topic[] = [
  ks1Year2Draft({
    id: "y2-tens-and-ones",
    glossaryTerms: ["place-value", "ten-frame"],
    strand: "Number and place value",
    title: "Tens and ones in two-digit numbers",
    shortTitle: "Tens and ones",
    summary: "See what each digit is worth in a two-digit number, and split it in more than one way.",
    prerequisites: [],
    statutoryOutcomes: [
      "Recognise the place value of each digit in a two-digit number (tens, ones)",
      "Use place value and number facts to solve problems",
    ],
    readyToProgress: ["2NPV-1"],
    whyThisMatters: "47 is four tens and seven ones, not a 4 glued to a 7. Later adding and subtracting only work if that picture is solid.",
    inPlainEnglish: "In 47 the 4 is forty — four tens — and the 7 is seven ones. You can also split 47 as 30 and 17, or 40 and 7. The digits are not two separate small numbers sitting side by side. That worth, depending on where the digit sits, is what school calls place value.",
    howSchoolTeachesIt: "School builds numbers with ten-sticks and ones, place-value cards, or ten-frames stacked. They ask for the usual split (tens and ones) and for unusual splits, so the child is not stuck on only one picture.",
    sayThis: [
      { prompt: "In 47, what is the 4 worth?", listenFor: "40, or four tens." },
      "Can you make 47 with tens and ones?",
      "Show me 47 another way — maybe using extra ones instead of a ten.",
    ],
    avoidThis: [
      "Calling the digits ‘the first number and the last number’ without saying tens and ones.",
      "Jumping to a written adding layout before they can say what each digit is worth.",
    ],
    misconceptions: [
      {
        misconception: "They read 47 as four and seven, or think it is 4 + 7 = 11.",
        why: "The two digits look like two one-digit numbers.",
        instead: "Build 47 with four ten-bundles and seven loose ones. Point to the 4 and say four tens.",
      },
      {
        misconception: "They say 40 and 7 make 47, but cannot show 30 and 17 as the same number.",
        why: "They only know the standard split.",
        instead: "Trade one ten-bundle for ten ones. Ask if it is still 47.",
      },
    ],
    youAreReadyWhen: "You can point to either digit in a two-digit number and say its worth, and you can split the number in two ways.",
    householdItems: [
      "About 50 small objects, such as pasta, Lego, or spoons",
      "Something to bundle tens: elastic bands, cups, or ten-hole egg boxes",
      "Scrap paper for writing the number",
    ],
    setup: "Sit with a pile of small objects. Decide that one object is one, and a bundle or cup of ten is a ten. Write 47 on paper.",
    activityTitle: "Build, then rebuild, a two-digit number",
    steps: [
      "Build 47: four tens and seven ones. Say ‘4 tens and 7 ones’.",
      "Trade one ten for ten ones. Ask if it is still 47.",
      "Hide the tens. Ask what is missing if the number is still 47.",
      "Repeat with 30, so they have to show zero ones.",
    ],
    tip: "If you run short of objects, drawing sticks of ten is fine. The talk is the point.",
    check: [
      {
        prompt: "What is the 3 worth in 35?",
        looksLike: "30, or three tens.",
        notYet: "Three, or they read the whole number.",
        nudge: "Cover the 5. Ask how many tens that 3 stands for.",
      },
      {
        prompt: "Make 26 two different ways.",
        looksLike: "For example 2 tens and 6 ones, and 1 ten and 16 ones.",
        notYet: "Only one arrangement, or they mix the digits up.",
        nudge: "Start with tens and ones, then trade one ten for ten ones.",
      },
      {
        prompt: "Write the number that is 5 tens and 0 ones.",
        looksLike: "50.",
        notYet: "5 or 15.",
        nudge: "Put a card in the ones place that says 0.",
      },
    ],
    stretch: "Ask which is more: 3 tens or 28 ones. Let them build both.",
  }),
  ks1Year2Draft({
    id: "y2-numbers-to-100-on-a-line",
    glossaryTerms: ["multiple", "number-line", "estimate"],
    strand: "Number and place value",
    title: "Numbers to 100 on a line",
    shortTitle: "Numbers on a line",
    summary: "Find any two-digit number on a 0–100 line, including the ten just before and the ten just after.",
    prerequisites: ["y2-tens-and-ones"],
    statutoryOutcomes: [
      "Identify, represent and estimate numbers using different representations, including the number line",
    ],
    readyToProgress: ["2NPV-2"],
    whyThisMatters: "A number line is how children later estimate and check whether an answer is sensible. 47 sits between 40 and 50, closer to 50 than to 40.",
    inPlainEnglish: "Imagine a straight path from 0 to 100 marked in tens. 47 lives after 40 and before 50. The previous ten is 40; the next ten is 50. Estimate means a sensible about-where, not a lucky guess. You do not need to count from 0 every time.",
    howSchoolTeachesIt: "School uses a blank 0–100 line, a hundred square, and bead strings of 100. They ask children to place a number, then name the multiples of 10 on either side (40, 50, 60… — numbers in the 10 times list), then say which is closer.",
    sayThis: [
      "About where would 47 sit between 40 and 50?",
      "What is the ten just before 47? The ten just after?",
      "Is 47 closer to 40 or to 50?",
    ],
    avoidThis: [
      "Always starting at 0 and counting on in ones to find a number.",
      "Treating the hundred square as the only picture — a straight line matters too.",
    ],
    misconceptions: [
      {
        misconception: "They put 47 next to 70 because they looked at the 7.",
        why: "They compared digits, not place on the line.",
        instead: "Mark 40 and 50 first. 47 is three steps past 40 if each mark is one.",
      },
      {
        misconception: "They say the next ten after 47 is 57, adding ten to the ones.",
        why: "Next ten means the next multiple of 10, not ten more.",
        instead: "Point to 40, 50, 60 on the line. 47 sits before 50.",
      },
    ],
    youAreReadyWhen: "You can place a two-digit number on a 0–100 line and name the ten before and the ten after.",
    householdItems: [
      "A long strip of paper for a 0–100 line, marked 0, 10, 20 … 100",
      "Sticky notes or scraps with numbers such as 47, 62, 90, 8",
    ],
    setup: "Draw a long line. Mark 0 and 100 at the ends, then the tens in between as evenly as you can.",
    activityTitle: "Peg the number, name the neighbours",
    steps: [
      "Place 50 first — halfway. Then place 10 and 90.",
      "Place 47. Talk about 40 and 50 on either side.",
      "Place 62. Is it closer to 60 or 70?",
      "Ask what the next ten after 90 is.",
    ],
    check: [
      {
        prompt: "What is the ten just before 73?",
        looksLike: "70.",
        notYet: "63 or 72.",
        nudge: "The tens marks are 70 and 80. 73 sits just after 70.",
      },
      {
        prompt: "Is 47 closer to 40 or 50?",
        looksLike: "Closer to 50.",
        notYet: "Closer to 40, or ‘in the middle’.",
        nudge: "Halfway from 40 to 50 is 45. 47 is past halfway.",
      },
      {
        prompt: "Point to about 8 on the 0–100 line.",
        looksLike: "Near 10, not near the middle.",
        notYet: "Near 80, reading the digit.",
        nudge: "8 is a small number, close to 0.",
      },
    ],
    stretch: "Give a number. Ask how many steps to the next ten.",
  }),
  ks1Year2Draft({
    id: "y2-order-to-100",
    glossaryTerms: ["number-line", "place-value", "number-word"],
    strand: "Number and place value",
    title: "Compare and order numbers to 100",
    shortTitle: "Order to 100",
    summary: "Put numbers to 100 in size order by looking at tens first, then ones, using <, > and =.",
    prerequisites: ["y2-tens-and-ones"],
    statutoryOutcomes: [
      "Compare and order numbers from 0 up to 100; use <, > and = signs",
    ],
    readyToProgress: [],
    whyThisMatters: "Ordering is how children check whether an answer is sensible. 71 is not ‘a bit more than 17’.",
    inPlainEnglish: "To compare 71 and 68, look at tens first: 7 tens beats 6 tens, so 71 is greater even though 8 looks ‘big’. The signs < and > just record that talk.",
    howSchoolTeachesIt: "School uses number lines, place-value charts, and the signs <, > and =. They compare tens first, then ones if the tens match. They do not teach the crocodile as the whole lesson.",
    sayThis: [
      "Which is greater, 71 or 68? How do you know?",
      "Put 45, 54 and 40 in order, smallest first.",
      "When do we look at the ones digit?",
    ],
    avoidThis: [
      "Comparing from the ones digit first, as if they were all one-digit numbers.",
      "Teaching only ‘the crocodile eats the bigger number’ with no talk of tens.",
    ],
    misconceptions: [
      {
        misconception: "They say 19 is greater than 21 because 9 is bigger than 2.",
        why: "They compared the digits they noticed, not the tens.",
        instead: "Build both. 21 has two tens; 19 has one ten.",
      },
      {
        misconception: "They write 45 > 54 because they read left to right.",
        why: "The sign was copied without the comparison.",
        instead: "Say the sentence in words first: 45 is less than 54. Then choose the sign.",
      },
    ],
    youAreReadyWhen: "You can order three two-digit numbers and say which place you looked at first.",
    householdItems: [
      "Two-digit numbers written on scrap paper",
      "A 0–100 line marked in tens",
    ],
    setup: "Write six numbers such as 19, 21, 45, 54, 40, 71. Keep the 0–100 line nearby.",
    activityTitle: "Line them up, then write the sign",
    steps: [
      "Place 19 and 21 on the line. Talk about why 21 is further along.",
      "Order 45, 54 and 40, smallest first.",
      "Write 71 > 68 as a sentence: 71 is greater than 68.",
      "Find two numbers that are equal if you invent a matching pair, such as 40 and 40.",
    ],
    check: [
      {
        prompt: "Which is smaller: 39 or 41?",
        looksLike: "39.",
        notYet: "41, because 1 is small.",
        nudge: "Compare tens: 3 tens against 4 tens.",
      },
      {
        prompt: "Order 26, 62, 16.",
        looksLike: "16, 26, 62.",
        notYet: "Sorted by the first digit they see without place value.",
        nudge: "Tens first, then ones.",
      },
      {
        prompt: "Write a sign for 50 and 50.",
        looksLike: "50 = 50.",
        notYet: "50 > 50.",
        nudge: "Same number, equal.",
      },
    ],
    stretch: "Give a number between 30 and 40 that is closer to 40 than 30. Ask them to justify.",
  }),
  ks1Year2Draft({
    id: "y2-count-in-2-3-5-10",
    glossaryTerms: ["skip-counting", "multiple", "number-line"],
    strand: "Number and place value",
    title: "Counting in 2s, 3s, 5s and 10s",
    shortTitle: "Count in 2, 3, 5, 10",
    summary: "Keep a steady jump of 2, 3, 5 or 10, including tens from any number, forwards and back.",
    prerequisites: ["y2-tens-and-ones"],
    statutoryOutcomes: [
      "Count in steps of 2, 3, and 5 from 0, and in tens from any number, forward and backward",
    ],
    readyToProgress: [],
    whyThisMatters: "These jumps feed the 2, 5 and 10 times tables and make ‘ten more’ feel like a hop, not a new count from 1.",
    inPlainEnglish: "Counting in 2s is 0, 2, 4, 6… Equal jumps. 5s and 10s are the same idea with bigger steps. You can also hop 10 from 23: 23, 33, 43.",
    howSchoolTeachesIt: "School uses a number line, a hundred square, and groups of objects. They count back as well as forward. Tens from any number change the tens digit; the ones stay still — until you hit a rollover at 90.",
    sayThis: [
      "Start at 0. Jump 2 each time. Where do you land?",
      "Start at 23. Jump 10. Which digit changed?",
      "Count back in 5s from 50.",
    ],
    avoidThis: [
      "Racing through a chant with no objects or line.",
      "Mixing the step size mid-count without saying you have changed the jump.",
    ],
    misconceptions: [
      {
        misconception: "They add 2 wrongly, such as 8 then 11.",
        why: "They slipped into +3, or counted objects one-by-one and lost the pair.",
        instead: "Keep two objects in a cup and add a new cup each time.",
      },
      {
        misconception: "From 23 they hop 10 and land on 24 or 230.",
        why: "They moved the ones, or they ‘added a zero’.",
        instead: "Point to the tens digit. 2 tens become 3 tens; the 3 ones stay.",
      },
    ],
    youAreReadyWhen: "You can keep a 2-jump, a 5-jump and a 10-jump going, and you can hop 10 from a number that is not a multiple of 10.",
    householdItems: [
      "A strip of paper for a number line",
      "Small objects in pairs or fives",
      "A cup or plate for each group",
    ],
    setup: "Draw a line. Mark 0. Decide the jump (start with 2). Have objects ready to make matching groups.",
    activityTitle: "Pairs, then fives, then ten more",
    steps: [
      "Make pairs. After each new pair, write the total: 2, 4, 6…",
      "When that is steady, make groups of 5: 5, 10, 15, 20.",
      "Start at 23. Add one ten-bundle. Write 33, then 43.",
      "Count back in 10s from 70: 70, 60, 50.",
    ],
    check: [
      {
        prompt: "Count four jumps of 2 from 0.",
        looksLike: "2, 4, 6, 8.",
        notYet: "Uneven jumps or missing 6.",
        nudge: "Add one pair at a time and write the total.",
      },
      {
        prompt: "10 more than 46.",
        looksLike: "56.",
        notYet: "47 or 460.",
        nudge: "The tens digit ticks on. The 6 ones stay.",
      },
      {
        prompt: "Count back three 5s from 30.",
        looksLike: "25, 20, 15.",
        notYet: "They count in 1s or 10s.",
        nudge: "Hop back five on the line each time.",
      },
    ],
    stretch: "Start at 3 (not 0) and keep jumping 2. Notice the odd landings.",
  }),
  ks1Year2Draft({
    id: "y2-number-words-to-100",
    glossaryTerms: ["number-word", "numeral"],
    strand: "Number and place value",
    title: "Read and write numbers to 100",
    shortTitle: "Number words to 100",
    summary: "Match numerals and words to at least 100, including the teen and -ty mix-ups.",
    prerequisites: ["y2-tens-and-ones"],
    statutoryOutcomes: [
      "Read and write numbers to at least 100 in numerals and in words",
    ],
    readyToProgress: [],
    whyThisMatters: "Thirteen and thirty sound alike. Getting the word wrong is how 13 and 30 swap on the page.",
    inPlainEnglish: "A numeral is the digit symbol (47). A number word is the letters (forty-seven): the tens word, then the ones word. Teens (thirteen to nineteen) are the awkward family. Forty does not start like four.",
    howSchoolTeachesIt: "School matches numeral cards to word cards, and they say the tens-and-ones split as they write. They practise the teen / -ty pairs on purpose: 13 and 30, 14 and 40, 15 and 50.",
    sayThis: [
      "Read this: 40. Now 14. What is different?",
      "Write forty-seven in digits.",
      "Say 73 in tens and ones, then write the word.",
    ],
    avoidThis: [
      "Only copying words from a wall without saying tens and ones.",
      "Leaving 13 and 30 uncompared — they are the classic swap.",
    ],
    misconceptions: [
      {
        misconception: "They write 13 for thirty, or 30 for thirteen.",
        why: "The words sound close, and both have a 1 and a 3.",
        instead: "Build both. Thirteen is 1 ten and 3 ones. Thirty is 3 tens.",
      },
      {
        misconception: "They write fourty for 40.",
        why: "The spoken four leaked into the spelling.",
        instead: "Write forty beside four. Notice the u has gone. Matching the numeral matters more than a spelling test tonight.",
      },
    ],
    youAreReadyWhen: "You can read and write a mix of teens and tens-and-ones numbers to 100, and you can tell 13 from 30.",
    householdItems: [
      "Scrap paper",
      "Numeral cards or scraps 11–20 and 30, 40, 50",
      "Optional: ten-bundles to build a confusing pair",
    ],
    setup: "Write the words thirteen, thirty, fourteen, forty on scraps. Write 13, 30, 14, 40 on others.",
    activityTitle: "Match the tricky pairs, then write 47",
    steps: [
      "Match 13 to thirteen and 30 to thirty. Build both if it helps.",
      "Match 14 and 40 the same way.",
      "Say 47 as four tens and seven ones. Write forty-seven, then 47.",
      "Read a homemade shop price written in words, such as seventy-two.",
    ],
    check: [
      {
        prompt: "Write 16 in words.",
        looksLike: "Sixteen.",
        notYet: "Sixty, or 16 copied as digits only.",
        nudge: "Sixteen is a teen: 1 ten and 6 ones.",
      },
      {
        prompt: "What number is seventy?",
        looksLike: "70.",
        notYet: "17.",
        nudge: "Seven tens, no extra ones.",
      },
      {
        prompt: "Read 81.",
        looksLike: "Eighty-one.",
        notYet: "Eighteen, or eight one.",
        nudge: "8 tens and 1 one.",
      },
    ],
    stretch: "Write ninety-nine and one hundred. Talk about the extra place in 100.",
  }),
  ks1Year2Draft({
    id: "y2-facts-to-20",
    glossaryTerms: ["part-whole", "ten-frame", "fluency"],
    strand: "Addition and subtraction",
    title: "Addition and subtraction facts to 20",
    shortTitle: "Facts to 20",
    summary: "Keep the facts within 10 fluent, and use them to work facts to 20 without a long count from 1.",
    prerequisites: [],
    statutoryOutcomes: [
      "Recall and use addition and subtraction facts to 20 fluently, and derive and use related facts up to 100",
    ],
    readyToProgress: ["2NF-1"],
    whyThisMatters: "Year 2 still practises facts within 10. Those small facts are how 8 + 6 and 14 − 5 become quick, not a climb from 1 every time.",
    inPlainEnglish: "If you know 8 + 2 = 10, then 8 + 6 is 8 + 2 + 4: make 10, then 4 more, 14. Fluency is not a race against a clock. It is seeing the fact instead of recounting the pile.",
    howSchoolTeachesIt: "School keeps ten-frames, bead strings and part–whole pictures. They build through 10 for facts that cross 10, and they keep practising the within-10 facts so they do not fade.",
    sayThis: [
      "8 and what make 10? Then how many more to add?",
      "You knew 7 + 3. Does that help with 7 + 5?",
      "Don’t rush. See it on the frame first.",
    ],
    avoidThis: [
      "Racing against a timer. Anxiety hides the facts you are trying to grow.",
      "Banning fingers or a ten-frame. In Year 2 they are still a legitimate picture.",
    ],
    misconceptions: [
      {
        misconception: "They can do 8 + 2 but count all from 1 for 8 + 6.",
        why: "Crossing 10 feels like a new kind of sum.",
        instead: "Fill 8 on a ten-frame. Two more make 10; four more sit on a second frame.",
      },
      {
        misconception: "They know 9 + 1 = 10 but cannot say 10 − 1.",
        why: "Addition and subtraction are still two subjects in their head.",
        instead: "Build 10, take 1 away, and say the family: 9 + 1, 1 + 9, 10 − 1, 10 − 9.",
      },
    ],
    youAreReadyWhen: "You can use a within-10 fact to help a fact to 20, and you can show it on a ten-frame or with objects.",
    householdItems: [
      "Twenty small objects of two types or colours",
      "Two homemade ten-frames (two rows of five) or two 10-hole egg boxes",
    ],
    setup: "Count ten holes on each frame. Have 20 objects ready. Tonight live in 8 + 6 and 14 − 5.",
    activityTitle: "Make 10, then the rest",
    steps: [
      "Fill 8 on the first frame. Ask how many to make 10. Add 2, then 4 more on the second frame. Say 8 + 6 = 14.",
      "Start with 14. Take 5 away. Talk through 14 − 4 = 10, then 1 more, or count back on the frame.",
      "Try 9 + 7 the same way.",
      "Write the fact family for 8, 6 and 14 if they are still keen.",
    ],
    tip: "If crossing 10 wobbles, spend the whole session on facts within 10. That is still the Year 2 job.",
    check: [
      {
        prompt: "7 + 5.",
        looksLike: "12, with a make-10 picture or known fact.",
        notYet: "Count-all from 1 ending on a wrong total.",
        nudge: "7 needs 3 to make 10, then 2 more is 12.",
      },
      {
        prompt: "15 − 6.",
        looksLike: "9.",
        notYet: "11 or they count all 15 then guess.",
        nudge: "15 − 5 = 10, then 1 more away is 9. Or take 6 off the frames.",
      },
      {
        prompt: "9 + 1, then 9 + 3.",
        looksLike: "10, then 12.",
        notYet: "They recount 9 each time.",
        nudge: "Once 9 + 1 is 10, two more is 12.",
      },
    ],
    stretch: "Cover one part of 14 = 8 + ? and ask for the missing part.",
  }),
  ks1Year2Draft({
    id: "y2-related-facts-to-100",
    glossaryTerms: ["place-value"],
    strand: "Addition and subtraction",
    title: "Related facts to 100",
    shortTitle: "Related facts to 100",
    summary: "If 3 + 4 = 7, then 30 + 40 = 70. Use known ones facts to work tens facts.",
    prerequisites: ["y2-facts-to-20", "y2-tens-and-ones"],
    statutoryOutcomes: [
      "Recall and use addition and subtraction facts to 20 fluently, and derive and use related facts up to 100",
    ],
    readyToProgress: [],
    whyThisMatters: "This is how 30 + 40 stops being a new sum. It is the same fact, scaled into tens.",
    inPlainEnglish: "3 ones and 4 ones make 7 ones. 3 tens and 4 tens make 7 tens, which is 70. 70 − 40 is 30 for the same reason. You are not counting 70 objects.",
    howSchoolTeachesIt: "School puts ones facts next to tens facts, often with place-value equipment or a chart of tens columns. They say ‘3 + 4 = 7, so 3 tens + 4 tens = 7 tens’.",
    sayThis: [
      "If 3 + 4 is 7, what is 30 + 40?",
      "3 tens and 4 tens — how many tens?",
      "70 take away 40. Which fact is hiding?",
    ],
    avoidThis: [
      "Saying ‘just add a zero’ with no meaning for tens.",
      "Counting on in ones from 30 to 70 every time.",
    ],
    misconceptions: [
      {
        misconception: "They write 30 + 40 = 70 but say ‘3 + 4 = 7 and then a zero’, with no tens talk.",
        why: "The zero is a trick, not a place.",
        instead: "Build 3 ten-bundles and 4 ten-bundles. Seven bundles are 70.",
      },
      {
        misconception: "They add 30 + 40 as 34 or 3040.",
        why: "They concatenated digits instead of adding tens.",
        instead: "Line tens under tens. 3 tens + 4 tens.",
      },
    ],
    youAreReadyWhen: "You can turn a ones fact into a tens fact and say it with the word tens.",
    householdItems: [
      "Ten-bundles or cups of ten",
      "Paper to write the ones fact next to the tens fact",
    ],
    setup: "Write 3 + 4 = 7. Have seven cups of ten ready, or draw seven sticks of ten.",
    activityTitle: "Same fact, bigger units",
    steps: [
      "Build 3 + 4 with ones. Write 3 + 4 = 7.",
      "Swap each one for a ten-bundle. Write 30 + 40 = 70.",
      "Take 4 bundles away from 7 bundles. Write 70 − 40 = 30.",
      "Try 5 + 2 = 7 beside 50 + 20 = 70.",
    ],
    check: [
      {
        prompt: "20 + 50.",
        looksLike: "70.",
        notYet: "25 or 7.",
        nudge: "2 tens and 5 tens make 7 tens.",
      },
      {
        prompt: "90 − 30.",
        looksLike: "60.",
        notYet: "87 or 6.",
        nudge: "9 tens take 3 tens leave 6 tens.",
      },
      {
        prompt: "If 6 + 3 = 9, what is 60 + 30?",
        looksLike: "90.",
        notYet: "63 or 9.",
        nudge: "6 tens + 3 tens = 9 tens.",
      },
    ],
    stretch: "What about 25 + 40 if they can hold 2 tens, 5 ones, plus 4 tens?",
  }),
  ks1Year2Draft({
    id: "y2-add-subtract-across-10",
    glossaryTerms: ["part-whole", "ten-frame"],
    strand: "Addition and subtraction",
    title: "Add and subtract across 10",
    shortTitle: "Across 10",
    summary: "Bridge through 10 when a ones fact is not enough: 8 + 5, 13 − 6.",
    prerequisites: ["y2-facts-to-20"],
    statutoryOutcomes: [
      "Add and subtract numbers using concrete objects, pictorial representations, and mentally, including a two-digit number and ones",
      "Solve problems with addition and subtraction using concrete objects and pictorial representations",
    ],
    readyToProgress: ["2AS-1"],
    whyThisMatters: "Crossing 10 is the wobble that later two-digit adding still hits. Year 2 wants a make-10 habit, not a long count.",
    inPlainEnglish: "8 + 5: 8 needs 2 to make 10, so split 5 into 2 and 3. 10 and 3 make 13. 13 − 6: 13 to 10 is 3, then 3 more away is 7 — or split 6 as 3 and 3.",
    howSchoolTeachesIt: "School uses two ten-frames, a bead string of 20, and a part–whole split of the second number. They do not want ‘put the bigger number in your head’ as the first story if it hides the bridge through 10.",
    sayThis: [
      "How many to make 10? Then how many are left to add?",
      "Split the 5 so part of it fills to 10.",
      "13 take away 3 gets you to 10. Then what?",
    ],
    avoidThis: [
      "Teaching ‘put the bigger number in your head and count on’ as the only method.",
      "A written layout that hides the make-10 split.",
    ],
    misconceptions: [
      {
        misconception: "They count on in ones from 8: 9, 10, 11, 12, 13 — and often lose one.",
        why: "Counting on works for +1 or +2; +5 across 10 is easy to miscount.",
        instead: "Fill to 10 first. The rest sits on the next frame.",
      },
      {
        misconception: "They do 8 + 5 as 8 + 2 only, and stop at 10.",
        why: "They made 10 and forgot the leftover 3.",
        instead: "Keep the leftover objects visible on the second frame.",
      },
    ],
    youAreReadyWhen: "You can add or subtract across 10 by making 10 (or breaking 10) rather than counting every one.",
    householdItems: [
      "Two ten-frames or egg boxes",
      "About 20 objects",
      "Paper for a part–whole sketch",
    ],
    setup: "Tonight’s main sums: 8 + 5 and 13 − 6. Frames empty to start.",
    activityTitle: "Fill to 10, then the leftover",
    steps: [
      "Put 8 on a frame. Split 5 into 2 and 3. Fill the frame, then put 3 on the next. Write 8 + 5 = 13.",
      "Start with 13. Take 3 to reach 10, then 3 more. Write 13 − 6 = 7.",
      "Try 9 + 4 and 15 − 7.",
      "Sketch the split of 5 as a part–whole: 2 and 3.",
    ],
    check: [
      {
        prompt: "6 + 8.",
        looksLike: "14.",
        notYet: "13 or 15, from a lost count.",
        nudge: "6 needs 4 to make 10; 8 splits into 4 and 4; 10 + 4 = 14.",
      },
      {
        prompt: "12 − 5.",
        looksLike: "7.",
        notYet: "8 or 6.",
        nudge: "12 − 2 = 10, then 3 more away is 7.",
      },
      {
        prompt: "Why split 5 in 8 + 5?",
        looksLike: "So part of it fills to 10.",
        notYet: "Because 5 is odd, or to make it harder.",
        nudge: "8 needs 2. The leftover 3 goes after 10.",
      },
    ],
    stretch: "17 − 8 by going to 10 first, then the rest.",
  }),
  ks1Year2Draft({
    id: "y2-difference-how-many-more",
    glossaryTerms: ["compare-length"],
    strand: "Addition and subtraction",
    title: "Difference: how many more?",
    shortTitle: "How many more?",
    summary: "See subtraction as the gap between two amounts, not only as take-away.",
    prerequisites: ["y2-facts-to-20"],
    statutoryOutcomes: [
      "Solve problems with addition and subtraction using concrete objects and pictorial representations, including those involving numbers, quantities and measures",
    ],
    readyToProgress: ["2AS-2"],
    whyThisMatters: "‘How many more?’ is not take-away language, but the answer is a subtract. If children only know ‘eat some, how many left?’, comparison problems stall.",
    inPlainEnglish: "Sam has 12 grapes, Mia has 7. How many more does Sam have? You are not throwing grapes away. You line them up and read the gap: 5. That gap is 12 − 7.",
    howSchoolTeachesIt: "School uses bar pictures (two bars, read the extra bit) and lined-up objects. They also count on from the smaller number to the larger. Take-away is still taught; this pack is the comparison structure.",
    sayThis: [
      "Are we taking some away, or finding the gap?",
      "Line them up. How many extra on the longer row?",
      "Count on from 7 until you reach 12. How many hops?",
    ],
    avoidThis: [
      "Grabbing the two numbers and adding because the word ‘more’ is in the question.",
      "Only ever acting subtraction as ‘remove objects from a pile’.",
    ],
    misconceptions: [
      {
        misconception: "They add 12 and 7 because they heard ‘more’.",
        why: "More often means add in everyday talk.",
        instead: "Ask ‘more than whom?’ Line up both rows. The extra is the answer.",
      },
      {
        misconception: "They take 7 from 12 by removing 7, then cannot connect that to ‘how many more’.",
        why: "Take-away and difference still feel like two operations.",
        instead: "After take-away, line the remaining 5 next to Mia’s 7 and show it is the extra Sam has.",
      },
    ],
    youAreReadyWhen: "You can show a ‘how many more’ story with two rows or two bars, and write it as a subtract.",
    householdItems: [
      "Two colours of objects, about 12 of one and 7 of the other",
      "Paper for a bar sketch",
    ],
    setup: "Tonight’s story: 12 red, 7 blue. How many more red?",
    activityTitle: "Two rows, then the gap",
    steps: [
      "Make a row of 12 and a row of 7, lined up at the same start.",
      "Point to the extra reds. Count the gap. Write 12 − 7 = 5.",
      "Draw two bars the same way.",
      "Invent one more story: ‘I need 15. I have 9. How many more do I need?’",
    ],
    check: [
      {
        prompt: "9 stickers and 4 stickers. How many more is 9?",
        looksLike: "5.",
        notYet: "13.",
        nudge: "The gap from 4 to 9 is 5.",
      },
      {
        prompt: "Draw bars for 11 and 8. What is the extra?",
        looksLike: "3.",
        notYet: "They draw one bar of 19.",
        nudge: "Two bars. Read the difference.",
      },
      {
        prompt: "Is ‘how many more’ add or subtract?",
        looksLike: "Subtract (the gap), even though the word is more.",
        notYet: "Add, because more.",
        nudge: "More than the other amount — that is the extra, a take-away or a count-on.",
      },
    ],
    stretch: "How many fewer is 7 than 12? Same gap, different sentence.",
  }),
  ks1Year2Draft({
    id: "y2-add-subtract-1s-or-10s",
    glossaryTerms: ["place-value"],
    strand: "Addition and subtraction",
    title: "Add or subtract ones, or tens, to a two-digit number",
    shortTitle: "+/− 1s or 10s",
    summary: "Change only the ones, or only the tens: 34 + 5, 34 + 20, 34 − 3, 34 − 10.",
    prerequisites: ["y2-tens-and-ones", "y2-related-facts-to-100"],
    statutoryOutcomes: [
      "Add and subtract numbers using concrete objects, pictorial representations, and mentally, including a two-digit number and ones, and a two-digit number and tens",
    ],
    readyToProgress: ["2AS-3"],
    whyThisMatters: "If only one place changes, the child should not rebuild the whole number. This is the stepping stone to adding two two-digit numbers.",
    inPlainEnglish: "34 + 5 changes the ones: 4 + 5 = 9, so 39. 34 + 20 changes the tens: 3 tens + 2 tens = 5 tens, so 54. Sometimes ones roll over, such as 34 + 8.",
    howSchoolTeachesIt: "School uses a place-value chart, a hundred square (jump down for +10), and jottings. They apply a known ones fact to the ones place, or a tens fact to the tens place.",
    sayThis: [
      "Which digit is doing the work — tens or ones?",
      "34 add 5. What is 4 add 5?",
      "34 add 20. How many tens now?",
    ],
    avoidThis: [
      "Rebuilding the whole number from 1 every time.",
      "A compact written method for +5 or +20 before the place-value jump is clear.",
    ],
    misconceptions: [
      {
        misconception: "They add 20 to the ones, getting 36 or 340.",
        why: "They have not chosen the tens place.",
        instead: "Say ‘two tens’ while pointing at the tens digit.",
      },
      {
        misconception: "They freeze when 34 + 8 crosses ten.",
        why: "The ones fact now affects the tens too.",
        instead: "Do 4 + 8 as a make-10: 12 ones is 1 ten and 2 ones, so 42.",
      },
    ],
    youAreReadyWhen: "You can add or subtract ones, and add or subtract tens, including one example that rolls over.",
    householdItems: [
      "Place-value columns drawn on paper (Tens | Ones)",
      "Digit scraps 0–9",
      "Ten-bundles for one rollover",
    ],
    setup: "Draw T | O columns. Put 3 and 4 in the columns.",
    activityTitle: "Change one column",
    steps: [
      "Add 5 ones. Write 39. Put 34 back.",
      "Add 2 tens. Write 54.",
      "Take away 1 ten. Write 24.",
      "Do one rollover: 34 + 8 ones.",
    ],
    check: [
      {
        prompt: "52 + 6.",
        looksLike: "58.",
        notYet: "58 written as 511 or 62.",
        nudge: "5 tens stay. 2 + 6 ones = 8.",
      },
      {
        prompt: "52 + 30.",
        looksLike: "82.",
        notYet: "55 or 5230.",
        nudge: "5 tens + 3 tens = 8 tens. Ones stay 2.",
      },
      {
        prompt: "47 − 5.",
        looksLike: "42.",
        notYet: "43 or 12.",
        nudge: "7 ones take 5 ones leave 2. Tens stay 4.",
      },
    ],
    stretch: "47 + 8, talking through the extra ten.",
  }),
  ks1Year2Draft({
    id: "y2-add-subtract-two-2-digit",
    glossaryTerms: ["number-line"],
    strand: "Addition and subtraction",
    title: "Add and subtract two two-digit numbers",
    shortTitle: "TO +/− TO",
    summary: "Split both numbers into tens and ones, add or subtract each place, then join — including when ones cross 10.",
    prerequisites: ["y2-add-subtract-1s-or-10s", "y2-add-subtract-across-10"],
    statutoryOutcomes: [
      "Add and subtract numbers using concrete objects, pictorial representations, and mentally, including two two-digit numbers",
      "Show that addition of two numbers can be done in any order (commutative) and subtraction of one number from another cannot",
    ],
    readyToProgress: ["2AS-4"],
    whyThisMatters: "35 + 27 is 30 + 20 and 5 + 7, then join. School’s later written layout is this split on paper. If the split is fuzzy, the layout is theatre.",
    inPlainEnglish: "35 + 27: tens first if you like (30 + 20 = 50) then ones (5 + 7 = 12), then 50 + 12 = 62. Or add 27 as +20 then +7. Subtraction cannot swap the numbers: 35 − 27 is not 27 − 35.",
    howSchoolTeachesIt: "School uses tens and ones equipment, empty number lines (jump tens, then ones), and jottings. Some classes later write ones under ones; the idea is still exchanging ten ones for one ten, not a new trick.",
    sayThis: [
      "Split both numbers into tens and ones. What shall we do first?",
      "5 + 7 is 12 ones. That is 1 ten and 2 ones — where does the extra ten go?",
      "Can we swap 35 − 27 and still get the same answer?",
    ],
    avoidThis: [
      "A compact written method with no tens-and-ones picture first.",
      "Teaching ‘carry the one’ as a chant with no exchange.",
    ],
    misconceptions: [
      {
        misconception: "They add 3 + 2 and 5 + 7 and write 512 or 39.",
        why: "They added digits, not tens and ones.",
        instead: "Say ‘three tens plus two tens’ before you touch the ones.",
      },
      {
        misconception: "They swap 35 − 27 into 27 − 35 because subtraction ‘should work like add’.",
        why: "Addition can swap; subtraction cannot.",
        instead: "Start with 35 objects. You cannot take 35 from a pile of 27.",
      },
    ],
    youAreReadyWhen: "You can add two two-digit numbers by tens and ones, including one that makes extra tens, and you know subtraction cannot swap.",
    householdItems: [
      "Tens and ones objects or drawn sticks",
      "Paper for jottings",
      "Optional: a 0–100 line",
    ],
    setup: "Tonight’s main sum: 35 + 27. Warm up with 35 + 20 if needed.",
    activityTitle: "Tens, then ones, then join",
    steps: [
      "Write 35 as 30 + 5 and 27 as 20 + 7.",
      "Add tens: 30 + 20 = 50. Add ones: 5 + 7 = 12.",
      "Join 50 and 12. Say 62.",
      "Try 35 − 12 as take 10 then take 2, on a line or with objects.",
    ],
    check: [
      {
        prompt: "23 + 14.",
        looksLike: "37.",
        notYet: "37 written as 217 or 28.",
        nudge: "20 + 10 = 30, 3 + 4 = 7.",
      },
      {
        prompt: "45 + 17.",
        looksLike: "62.",
        notYet: "52 or 512.",
        nudge: "40 + 10 = 50, 5 + 7 = 12, join.",
      },
      {
        prompt: "Can 18 + 25 be done as 25 + 18?",
        looksLike: "Yes — addition can swap.",
        notYet: "No, because 18 is smaller.",
        nudge: "Same total. Try both if unsure.",
      },
    ],
    stretch: "62 − 27 by subtracting 20 then 7, talking through 42 − 7.",
  }),
  ks1Year2Draft({
    id: "y2-add-three-ones",
    glossaryTerms: ["ten-frame"],
    strand: "Addition and subtraction",
    title: "Add three one-digit numbers",
    shortTitle: "Add three ones",
    summary: "Add three small numbers by pairing a fact you know, often a make-10, then adding the third.",
    prerequisites: ["y2-facts-to-20"],
    statutoryOutcomes: [
      "Add and subtract numbers using concrete objects, pictorial representations, and mentally, including adding three one-digit numbers",
    ],
    readyToProgress: [],
    whyThisMatters: "6 + 4 + 7 should not be a six-count then a four-count then a seven-count. Pair 6 and 4 to make 10, then add 7.",
    inPlainEnglish: "You can add in any order. Look for a pair that makes 10, or a pair you already know, then add the last number. 6 + 4 + 7 is 10 + 7 = 17.",
    howSchoolTeachesIt: "School circles a friendly pair, uses three ten-frame piles, and reminds children that addition can swap. They still check by adding in a different order.",
    sayThis: [
      "Which two would you add first, and why?",
      "Is there a pair that makes 10?",
      "Add them in a different order. Same total?",
    ],
    avoidThis: [
      "Always adding left to right even when a make-10 pair is sitting there.",
      "Forcing a written layout for three tiny numbers.",
    ],
    misconceptions: [
      {
        misconception: "They add 6 + 4 + 7 as 6 + 47 or 647.",
        why: "The three digits looked like one number.",
        instead: "Three separate piles. Point to each as its own amount.",
      },
      {
        misconception: "They add two, forget the third, and offer 10 for 6 + 4 + 7.",
        why: "Working memory dropped the last addend.",
        instead: "Keep the third pile visible. After 10, push the 7 in.",
      },
    ],
    youAreReadyWhen: "You can add three one-digit numbers by pairing, and you can check by adding in another order.",
    householdItems: [
      "Three small piles of objects (for example 6, 4 and 7)",
      "Paper",
    ],
    setup: "Make piles of 6, 4 and 7. Keep them apart.",
    activityTitle: "Find a friendly pair",
    steps: [
      "Spot 6 and 4. Join them. Say 10. Add the 7. Write 6 + 4 + 7 = 17.",
      "Now add 4 + 7 first, then 6. Same total?",
      "Try 5 + 8 + 5. Pair the fives.",
      "Try 9 + 3 + 1. Pair 9 and 1.",
    ],
    check: [
      {
        prompt: "5 + 5 + 6.",
        looksLike: "16.",
        notYet: "10 or 11.",
        nudge: "The two fives make 10, then 6.",
      },
      {
        prompt: "2 + 9 + 8.",
        looksLike: "19.",
        notYet: "19 written as 298.",
        nudge: "9 + 8 = 17, then 2 — or 2 + 8 = 10, then 9.",
      },
      {
        prompt: "Why may we add in any order?",
        looksLike: "Addition can swap; the total stays.",
        notYet: "Because it is faster to guess.",
        nudge: "Check with two different pairings.",
      },
    ],
    stretch: "Four ones, such as 3 + 7 + 2 + 8, only if they want it — two make-10 pairs.",
  }),
  ks1Year2Draft({
    id: "y2-inverse-and-missing-numbers",
    glossaryTerms: ["part-whole", "inverse"],
    strand: "Addition and subtraction",
    title: "Inverse and missing numbers",
    shortTitle: "Inverse and missing",
    summary: "Use add and subtract as a pair to check a sum and to find a missing number.",
    prerequisites: ["y2-add-subtract-across-10"],
    statutoryOutcomes: [
      "Recognise and use the inverse relationship between addition and subtraction and use this to check calculations and solve missing number problems",
    ],
    readyToProgress: [],
    whyThisMatters: "If 8 + 6 = 14, then 14 − 6 should bring you back to 8. That check, and □ + 6 = 14, is algebra later without the scary name.",
    inPlainEnglish: "Addition and subtraction undo each other — school calls that the inverse. A missing number is a part you have not been told. 14 − □ = 8 is asking for the other part of 14.",
    howSchoolTeachesIt: "School uses part–whole pictures and fact families: 8 + 6, 6 + 8, 14 − 6, 14 − 8. They put a box in different places and ask which part is missing.",
    sayThis: [
      "If 8 and 6 make 14, what is 14 take 6?",
      "Which part is hiding in □ + 6 = 14?",
      "How could we check 15 − 7 = 8?",
    ],
    avoidThis: [
      "Guessing the box without a part–whole picture.",
      "Calling it ‘the opposite’ with no undo action.",
    ],
    misconceptions: [
      {
        misconception: "They always add the two numbers they see, so □ + 6 = 14 becomes 20.",
        why: "They have a habit: two numbers → add.",
        instead: "Draw the whole 14. One part is 6. The box is the other part.",
      },
      {
        misconception: "They check 9 + 5 = 14 by adding 9 + 5 again.",
        why: "Repeating the same sum is not a check.",
        instead: "Undo it: 14 − 5 should be 9.",
      },
    ],
    youAreReadyWhen: "You can write a fact family and find a missing part using the inverse.",
    householdItems: [
      "14 objects",
      "A part–whole sketch (one whole circle, two part circles)",
      "Paper",
    ],
    setup: "Draw a part–whole. Put 14 in the whole. Tonight’s family is 8, 6 and 14.",
    activityTitle: "Family of four, then hide a part",
    steps: [
      "Build 8 and 6 making 14. Write 8 + 6, 6 + 8, 14 − 6, 14 − 8.",
      "Cover one part. Write □ + 6 = 14. Find the box.",
      "Cover the whole. Write 8 + 6 = □.",
      "Check 15 − 7 by adding the answer back on.",
    ],
    check: [
      {
        prompt: "14 − 8.",
        looksLike: "6, and they can say it undoes 8 + 6.",
        notYet: "22.",
        nudge: "The other part of 14.",
      },
      {
        prompt: "□ + 9 = 17.",
        looksLike: "8.",
        notYet: "26.",
        nudge: "17 is the whole. 9 is one part.",
      },
      {
        prompt: "How do you check 11 + 5 = 16?",
        looksLike: "16 − 5 = 11 (or 16 − 11 = 5).",
        notYet: "Add 11 + 5 again.",
        nudge: "Undo it.",
      },
    ],
    stretch: "12 = □ + 5 with the box on the right of the equals. Same missing part.",
  }),
  ks1Year2Draft({
    id: "y2-tables-2-5-10",
    glossaryTerms: ["skip-counting", "array"],
    strand: "Multiplication and division",
    title: "The 2, 5 and 10 times tables",
    shortTitle: "2, 5 and 10 tables",
    summary: "See 2s, 5s and 10s as equal groups, and write them with ×, ÷ and =.",
    prerequisites: ["y2-count-in-2-3-5-10"],
    statutoryOutcomes: [
      "Recall and use multiplication and division facts for the 2, 5 and 10 multiplication tables, including recognising odd and even numbers",
      "Calculate mathematical statements for multiplication and division within the multiplication tables and write them using the multiplication (×), division (÷) and equals (=) signs",
      "Show that multiplication of two numbers can be done in any order (commutative) and division of one number by another cannot",
    ],
    readyToProgress: ["2MD-1"],
    whyThisMatters: "Times tables in Year 2 are equal-group stories first, then a chant. Division is the same facts the other way.",
    inPlainEnglish: "4 × 5 means four groups of five, or five four times. That is 20. 20 ÷ 5 is ‘how many 5s in 20?’ Multiplication can swap: 4 × 5 = 5 × 4. Division cannot: 20 ÷ 5 is not 5 ÷ 20.",
    howSchoolTeachesIt: "School uses arrays — objects in equal rows and columns — number-line jumps, and skip-counting. They write × and ÷ in the same session as the story. They do not want a chant with no groups.",
    sayThis: [
      "Show me 4 groups of 5.",
      "If 4 × 5 is 20, what is 5 × 4?",
      "How many 5s in 20?",
    ],
    avoidThis: [
      "Only chanting with no array or jump.",
      "Timed table tests as the way in.",
    ],
    misconceptions: [
      {
        misconception: "They know 5, 10, 15, 20 but cannot write 4 × 5 = 20.",
        why: "The count and the symbols have not met.",
        instead: "Point to four jumps of 5. The 4 is how many jumps; the 5 is the size.",
      },
      {
        misconception: "They swap 20 ÷ 5 into 5 ÷ 20.",
        why: "They think every sign can swap like ×.",
        instead: "You can share 20 into 5s. You cannot share 5 into 20 equal whole groups.",
      },
    ],
    youAreReadyWhen: "You can show a 2, 5 or 10 fact with equal groups, write × and ÷ for it, and say that × can swap.",
    householdItems: [
      "20 small objects",
      "Paper to sketch arrays",
    ],
    setup: "Clear a space. Tonight live in 5s first, then one 2-fact and one 10-fact if there is time.",
    activityTitle: "Rows of 5, then write the signs",
    steps: [
      "Make 4 rows of 5. Say 4 × 5 = 20. Turn it: 5 rows of 4. Same 20.",
      "Split the 20 into groups of 5. Say 20 ÷ 5 = 4.",
      "Make 3 groups of 2. Write 3 × 2 = 6 and 6 ÷ 2 = 3.",
      "Count 10, 20, 30 with ten-bundles and write 3 × 10 = 30.",
    ],
    check: [
      {
        prompt: "5 × 6.",
        looksLike: "30, with jumps or groups.",
        notYet: "25 or 11.",
        nudge: "Six jumps of 5: 5, 10, 15, 20, 25, 30.",
      },
      {
        prompt: "20 ÷ 10.",
        looksLike: "2.",
        notYet: "10 or 30.",
        nudge: "How many 10s in 20? Two.",
      },
      {
        prompt: "Is 2 × 10 the same as 10 × 2?",
        looksLike: "Yes, both 20.",
        notYet: "No, because 2 is smaller.",
        nudge: "Two tens or ten twos — same pile.",
      },
    ],
    stretch: "Write the fact family for 5, 4 and 20.",
  }),
  ks1Year2Draft({
    id: "y2-odd-and-even",
    glossaryTerms: [],
    strand: "Multiplication and division",
    title: "Odd and even numbers",
    shortTitle: "Odd and even",
    summary: "Even numbers make pairs (and sit in the 2 times table). Odd numbers have one left over.",
    prerequisites: ["y2-tables-2-5-10"],
    statutoryOutcomes: [
      "Recall and use multiplication and division facts for the 2, 5 and 10 multiplication tables, including recognising odd and even numbers",
    ],
    readyToProgress: [],
    whyThisMatters: "Odd and even is how children later reason about whether a sum can be even, and how they check a 2 times-table fact.",
    inPlainEnglish: "Even means you can make pairs with none left over: 8 is 4 pairs. Odd means one left over: 9 is 4 pairs and a spare. Even numbers end in 0, 2, 4, 6 or 8 — after you have seen why, not as a rhyme alone.",
    howSchoolTeachesIt: "School pairs objects, colours a 0–20 line in 2s, and links even numbers to the 2 times table. They notice last digits once the pairing is solid.",
    sayThis: [
      "Can we make pairs with none left over?",
      "Is 14 in the 2 times table?",
      "What do even numbers end with — and why?",
    ],
    avoidThis: [
      "Only teaching ‘ends in 0, 2, 4, 6, 8’ with no pairing.",
      "Saying odd means strange or unlucky.",
    ],
    misconceptions: [
      {
        misconception: "They think 12 is odd because 1 is odd, or 21 is even because 2 is even.",
        why: "They looked at the wrong digit.",
        instead: "Pair 12 objects. None left over — even. The ones digit is the pairing clue for two-digit numbers.",
      },
      {
        misconception: "They say 0 is not even because it is nothing.",
        why: "Zero feels like it does not count.",
        instead: "Zero pairs: none left over. 0 is even. 10 ends in 0 and is even.",
      },
    ],
    youAreReadyWhen: "You can sort a handful of numbers into odd and even by pairing or by the 2-jump, not only by a chant.",
    householdItems: [
      "About 20 objects",
      "Number scraps 0–20",
    ],
    setup: "Tonight start with 8, 9, 10, 11. Objects ready to pair.",
    activityTitle: "Pair them, then sort the scraps",
    steps: [
      "Pair 8 objects. Even. Pair 9. One spare — odd.",
      "Colour 0, 2, 4, 6… on a 0–20 line. Those are even.",
      "Sort scraps 7, 14, 15, 20, 0 into odd and even piles.",
      "Ask whether 5 × 2 is even, and why.",
    ],
    check: [
      {
        prompt: "Is 18 odd or even?",
        looksLike: "Even — 9 pairs, or it ends in 8 after pairing makes sense.",
        notYet: "Odd, because 1 is odd.",
        nudge: "Make pairs, or hop in 2s to 18.",
      },
      {
        prompt: "Is 0 even?",
        looksLike: "Yes.",
        notYet: "No, it is nothing.",
        nudge: "No leftover objects. Also 0, 2, 4…",
      },
      {
        prompt: "Why is 15 odd?",
        looksLike: "One left over when paired; last digit 5.",
        notYet: "Because 15 is a teen.",
        nudge: "Seven pairs and a spare.",
      },
    ],
    stretch: "Add two odds (3 + 5). Is the total odd or even? Pair the story.",
  }),
  ks1Year2Draft({
    id: "y2-arrays-and-grouping",
    glossaryTerms: ["array"],
    strand: "Multiplication and division",
    title: "Arrays, grouping and sharing",
    shortTitle: "Arrays and grouping",
    summary: "Use rows and columns, and ‘how many groups?’ stories, to connect multiplication and division.",
    prerequisites: ["y2-tables-2-5-10"],
    statutoryOutcomes: [
      "Solve problems involving multiplication and division, using materials, arrays, repeated addition, mental methods, and multiplication and division facts, including problems in contexts",
    ],
    readyToProgress: ["2MD-2"],
    whyThisMatters: "‘I have 20. Groups of 5 — how many groups?’ is division where the number of groups is unknown. Year 3 will need that missing-number times sentence.",
    inPlainEnglish: "An array is objects in equal rows. 3 rows of 5 is 15, and also 5 columns of 3. Grouping asks how many 5s fit into 15. Sharing asks what each person gets if 15 is split between 3.",
    howSchoolTeachesIt: "School builds arrays, then hides a number: □ × 5 = 15. They contrast grouping (how many groups) with sharing (how many each) using the same numbers, so children see both stories.",
    sayThis: [
      "How many equal rows? How many in each row?",
      "I have 15. Groups of 5 — how many groups?",
      "15 shared between 3 people — how many each?",
    ],
    avoidThis: [
      "Only sharing sweets. Grouping ‘how many teams of 5?’ matters as much.",
      "Writing ÷ with no story.",
    ],
    misconceptions: [
      {
        misconception: "They add 3 and 5 for a 3-by-5 array.",
        why: "Rows and columns look like two numbers to combine.",
        instead: "Count the objects, or skip-count the rows: 5, 10, 15.",
      },
      {
        misconception: "They mix grouping and sharing and give 5 as the answer to both 15 ÷ 5 stories without saying which question was asked.",
        why: "The two division stories land on different numbers: groups vs each-share.",
        instead: "Act both: bags of 5 (3 bags) versus 3 plates (5 on each).",
      },
    ],
    youAreReadyWhen: "You can build a small array, write × and ÷ for it, and act a grouping story and a sharing story.",
    householdItems: [
      "15 small objects",
      "3 plates or drawn circles",
      "Paper",
    ],
    setup: "Tonight’s number is 15, with 3 and 5.",
    activityTitle: "Array, then bags, then plates",
    steps: [
      "Make 3 rows of 5. Write 3 × 5 = 15. Turn the array. Write 5 × 3 = 15.",
      "Put the 15 into bags of 5. How many bags? Write 15 ÷ 5 = 3.",
      "Share the 15 onto 3 plates. How many each? Write 15 ÷ 3 = 5.",
      "Hide a number: □ × 5 = 15. Point to the missing rows.",
    ],
    check: [
      {
        prompt: "2 rows of 10. How many altogether?",
        looksLike: "20.",
        notYet: "12.",
        nudge: "Two tens.",
      },
      {
        prompt: "20 into groups of 10. How many groups?",
        looksLike: "2.",
        notYet: "10.",
        nudge: "How many 10s in 20?",
      },
      {
        prompt: "20 shared between 10 people. How many each?",
        looksLike: "2.",
        notYet: "10.",
        nudge: "Each share is 2. Different question from grouping.",
      },
    ],
    stretch: "Write □ × 2 = 14 and 14 ÷ 2 = □. Same missing number?",
  }),
  ks1Year2Draft({
    id: "y2-thirds-and-quarters",
    glossaryTerms: ["quarter", "third", "half"],
    strand: "Fractions",
    title: "Thirds and quarters of shapes and sets",
    shortTitle: "Thirds and quarters",
    summary: "Find 1/3, 1/4 and 3/4 of a length, a shape, or a set of objects, with equal parts.",
    prerequisites: [],
    statutoryOutcomes: [
      "Recognise, find, name and write fractions 1/3, 1/4, 2/4 and 3/4 of a length, shape, set of objects or quantity",
      "Write simple fractions, for example 1/2 of 6 = 3",
    ],
    readyToProgress: [],
    whyThisMatters: "Year 2 adds thirds and names 3/4. Equal parts still make the fraction; unequal slices are not quarters.",
    inPlainEnglish: "A third is one of three equal parts. A quarter is one of four. Three-quarters is three of those four parts. 1/3 of 12 objects is 4, because 12 shared into 3 equal groups is 4 in each.",
    howSchoolTeachesIt: "School folds paper, folds a strip for length, and shares objects onto plates. They write 1/3 of 12 = 4. They still fuss over equal parts before they fuss over the written fraction.",
    sayThis: [
      "Are the parts equal?",
      "How many equal groups? That is the bottom number.",
      "If one quarter is 3, what is three-quarters?",
    ],
    avoidThis: [
      "Always drawing pizza. Lengths and sets of objects matter as much.",
      "Cutting unequal pieces and still calling them thirds.",
    ],
    misconceptions: [
      {
        misconception: "They split a shape into three bits that are not equal and call each a third.",
        why: "Three parts is not enough — they must be the same size.",
        instead: "Fold, or measure, so the parts match. Unequal means we do not have thirds yet.",
      },
      {
        misconception: "They think 1/4 is bigger than 1/3 because 4 is bigger than 3.",
        why: "They compare the bottom numbers as if bigger means more.",
        instead: "More equal parts means each part is smaller. Four quarters fill the same whole as three thirds.",
      },
    ],
    youAreReadyWhen: "You can show 1/3 and 1/4 of a shape or a small set, and you can find 3/4 as three of the quarter-shares.",
    householdItems: [
      "A strip of paper and a rectangular scrap to fold",
      "12 small objects",
      "4 plates or drawn circles",
    ],
    setup: "Tonight: fold a strip into halves then halves again for quarters. Keep 12 objects for thirds.",
    activityTitle: "Fold quarters, share thirds",
    steps: [
      "Fold a strip in half, then each half again. Shade 1/4, then 3/4.",
      "Share 12 objects onto 3 plates. Say 1/3 of 12 is 4. Write it.",
      "Share 12 onto 4 plates. Say 1/4 is 3, 3/4 is 9.",
      "Fold a rectangle into thirds as carefully as you can. Talk about whether the parts look equal.",
    ],
    check: [
      {
        prompt: "1/4 of 12.",
        looksLike: "3.",
        notYet: "4 or 8.",
        nudge: "Four equal plates. One plate is 3.",
      },
      {
        prompt: "3/4 of 12.",
        looksLike: "9.",
        notYet: "3 or 7.",
        nudge: "Three of those plates.",
      },
      {
        prompt: "1/3 of 12.",
        looksLike: "4.",
        notYet: "3.",
        nudge: "Three equal plates. One plate is 4.",
      },
    ],
    stretch: "1/2 of 10 = 5, written as a sentence matching school’s ‘1/2 of 6 = 3’ pattern.",
  }),
  ks1Year2Draft({
    id: "y2-half-and-two-quarters",
    glossaryTerms: ["equivalent-fraction", "quarter", "half", "third"],
    strand: "Fractions",
    title: "Two quarters and one half",
    shortTitle: "Half and two quarters",
    summary: "See that 2/4 covers the same amount as 1/2 when the whole is the same.",
    prerequisites: ["y2-thirds-and-quarters"],
    statutoryOutcomes: [
      "Recognise the equivalence of 2/4 and 1/2",
    ],
    readyToProgress: [],
    whyThisMatters: "This is the first named equivalence. Later fractions sit on ‘same amount, different-sized pieces’.",
    inPlainEnglish: "Two quarters of a bar is the same amount as one half of the same bar. The pieces look different; the shaded length matches.",
    howSchoolTeachesIt: "School folds a strip in half, then folds again into quarters, and stacks the shaded parts. They may use a fraction wall. They do not cancel digits.",
    sayThis: [
      "Do these two shadings cover the same amount?",
      "If I split each half into two, what do the parts become?",
      "Name 2/4 another way.",
    ],
    avoidThis: [
      "Cancelling digits with no picture.",
      "Saying 1/2 = 2/4 because ‘you double both numbers’ before they see the extra split.",
    ],
    misconceptions: [
      {
        misconception: "They think 1/2 is bigger than 2/4 because halves sound bigger.",
        why: "The words fight the picture.",
        instead: "Lay a half strip on top of two quarters.",
      },
      {
        misconception: "They shade 2 of 4 parts that are not equal.",
        why: "Unequal parts are not quarters.",
        instead: "Fold, don’t freehand, if the splits look wild.",
      },
    ],
    youAreReadyWhen: "You can show 1/2 = 2/4 on the same-size whole.",
    householdItems: [
      "Two strips of paper the same length",
      "A pencil",
    ],
    setup: "Cut two strips the same length. One will be halves, one quarters.",
    activityTitle: "Same strip, extra folds",
    steps: [
      "Fold strip A in half. Shade one half.",
      "Fold strip B in half, then each half again. Shade two quarters.",
      "Stack them. Are the shaded lengths the same?",
      "Eat (or draw) two quarters of a rectangular sandwich picture and name it as a half.",
    ],
    check: [
      {
        prompt: "Show 1/2 and 2/4 on same-size strips.",
        looksLike: "Shaded lengths match.",
        notYet: "Different-length wholes, or 1/2 vs 1/4.",
        nudge: "Same strip length first. Then extra fold.",
      },
      {
        prompt: "Is 2/4 the same amount as 1/2?",
        looksLike: "Yes, if the whole is the same.",
        notYet: "No, because 2 is more than 1.",
        nudge: "Split each half in two.",
      },
      {
        prompt: "Why isn’t 1/2 the same as 1/4?",
        looksLike: "A half is two quarters; one quarter is smaller.",
        notYet: "They say it is the same because both start with 1.",
        nudge: "Compare one half-strip and one quarter-strip.",
      },
    ],
    stretch: "If they see 4/4 = 1, celebrate, then still keep tonight’s job as 2/4 = 1/2.",
  }),
  ks1Year2Draft({
    id: "y2-units-of-measure",
    glossaryTerms: ["compare-length", "estimate"],
    strand: "Measurement",
    title: "Metres, centimetres, kilograms and litres",
    shortTitle: "Units of measure",
    summary: "Choose a sensible unit, measure to the nearest mark, and compare lengths, masses and capacities with >, < and =.",
    prerequisites: ["y2-order-to-100"],
    statutoryOutcomes: [
      "Choose and use appropriate standard units to estimate and measure length/height in any direction (m/cm); mass (kg/g); temperature (°C); capacity (litres/ml) to the nearest appropriate unit, using rulers, scales, thermometers and measuring vessels",
      "Compare and order lengths, mass, volume/capacity and record the results using >, < and =",
    ],
    readyToProgress: [],
    whyThisMatters: "Year 1 compared with hands and cubes. Year 2 names metres, centimetres, kilograms, grams, litres and millilitres — and reads a scale.",
    inPlainEnglish: "A metre is 100 centimetres. A kilogram is 1000 grams. A litre is 1000 millilitres. You pick the unit that fits (a room in metres, a book in centimetres), then compare two readings.",
    howSchoolTeachesIt: "School uses rulers, kitchen scales, jugs, and sometimes a thermometer. They estimate first, then measure. They line lengths up at the same start.",
    sayThis: [
      "Which unit fits this — centimetres or metres?",
      "Line them up at the same start before you compare.",
      "What does each mark on this scale stand for?",
    ],
    avoidThis: [
      "Asking for a conversion table with no measuring.",
      "Starting a ruler at 1 instead of 0.",
    ],
    misconceptions: [
      {
        misconception: "They think 50 cm is longer than 1 m because 50 > 1.",
        why: "They compare the numbers and ignore the unit.",
        instead: "Lay a metre (or a 100 cm tape of paper) next to 50 cm.",
      },
      {
        misconception: "They read a ruler from the metal end or from 1.",
        why: "The 0 mark is not at the physical end of some rulers.",
        instead: "Find the 0. Line the object with 0, not with the end of the plastic.",
      },
    ],
    youAreReadyWhen: "You can measure a length in cm, compare two amounts with the unit said out loud, and choose m or cm for a new object.",
    householdItems: [
      "A ruler or a homemade 30 cm mark on paper",
      "Kitchen scales if you have them, or two bags of rice/flour to compare by feel then check",
      "A measuring jug or a 500 ml bottle",
    ],
    setup: "Pick one quantity tonight if kit is thin: length is enough. Put two objects to compare, such as a book and a spoon.",
    activityTitle: "Estimate, measure, compare",
    steps: [
      "Estimate the book’s length in cm. Measure it. Compare estimate and measure.",
      "Measure a second object. Write a comparison with > or <.",
      "If you have a jug, pour 100 ml then 200 ml. Which is more?",
      "If you have a thermometer or a weather app, read today’s temperature in °C as a number on a scale — no need to convert.",
    ],
    check: [
      {
        prompt: "Which is longer: 1 m or 80 cm?",
        looksLike: "1 m.",
        notYet: "80 cm.",
        nudge: "1 m is 100 cm.",
      },
      {
        prompt: "Compare 12 cm and 9 cm with a sign.",
        looksLike: "12 cm > 9 cm.",
        notYet: "12 < 9, or units dropped.",
        nudge: "Same unit: 12 is greater.",
      },
      {
        prompt: "Would you measure a garden in cm or m?",
        looksLike: "Metres (cm would be an awkward huge number).",
        notYet: "Always cm because that is the ruler.",
        nudge: "Pick the unit that fits.",
      },
    ],
    stretch: "Order three kitchen objects by mass if you have scales.",
  }),
  ks1Year2Draft({
    id: "y2-money-pounds-and-pence",
    glossaryTerms: ["number-line", "place-value"],
    strand: "Measurement",
    title: "Pounds and pence",
    shortTitle: "Money",
    summary: "Use £ and p, make an amount in different coin combinations, and give change in one unit.",
    prerequisites: ["y2-related-facts-to-100", "y2-add-subtract-1s-or-10s"],
    statutoryOutcomes: [
      "Recognise and use symbols for pounds (£) and pence (p); combine amounts to make a particular value",
      "Find different combinations of coins that equal the same amounts of money",
      "Solve simple problems in a practical context involving addition and subtraction of money of the same unit, including giving change",
    ],
    readyToProgress: [],
    whyThisMatters: "Money is place value you can hold. Same amount, different coins is the non-standard split idea again. Change is a difference story.",
    inPlainEnglish: "100 pence make £1. You can make 30p with three 10p, or with a 20p and a 10p. Change from 50p for something costing 35p is the gap: 15p. Keep pounds with pounds and pence with pence tonight.",
    howSchoolTeachesIt: "School uses real or plastic coins, a number line to the next 10p or pound, and shop problems in one unit. They write £ and p. They do not rush a point between pounds and pence unless school already does.",
    sayThis: [
      "How many pence in a pound?",
      "Make 30p another way.",
      "Count on from the price to the coin you paid with.",
    ],
    avoidThis: [
      "Writing £2.4 for £2.40, or mixing £ and p in one number without naming them.",
      "Only ever using 1p coins.",
    ],
    misconceptions: [
      {
        misconception: "They think 5 coins must be more money than 2 coins.",
        why: "They counted coins, not worth.",
        instead: "Compare five 1p with one 10p. Worth beats how many pieces.",
      },
      {
        misconception: "They give change by adding on in ones and get lost.",
        why: "No stepping-stone to the next 10p.",
        instead: "Jump to the next 10p, then to the coin you paid with.",
      },
    ],
    youAreReadyWhen: "You can make an amount two ways, add two pence amounts, and give change from 50p or £1 using coins or a line.",
    householdItems: [
      "Real or play coins: 1p, 2p, 5p, 10p, 20p, 50p, £1 if you have them",
      "A homemade shop list with three prices in pence",
    ],
    setup: "Set a mini shop: 12p, 35p, 20p. Have a 50p coin ready.",
    activityTitle: "Make 30p two ways, then give change",
    steps: [
      "Make 30p with three 10p. Then make 30p another way.",
      "Buy 12p and 20p. Total in pence. Pay with 50p. Count on for change.",
      "Buy 35p with 50p. Find change.",
      "Write one amount with £ if you make 100p, as £1, not with a point between pounds and pence unless school already does.",
    ],
    check: [
      {
        prompt: "Two ways to make 20p.",
        looksLike: "For example 10p + 10p, or 10p + 5p + 5p, or a 20p.",
        notYet: "Only 20 ones.",
        nudge: "Same worth, different coins.",
      },
      {
        prompt: "Change from 50p for 35p.",
        looksLike: "15p.",
        notYet: "85p or £15.",
        nudge: "35p to 40p is 5p, then 10p to 50p.",
      },
      {
        prompt: "How many 10p in £1?",
        looksLike: "10.",
        notYet: "100 or 1.",
        nudge: "10 × 10p = 100p = £1.",
      },
    ],
    stretch: "Three items in pence, total then change from £1.",
  }),
  ks1Year2Draft({
    id: "y2-time-to-five-minutes",
    glossaryTerms: ["quarter", "half"],
    strand: "Measurement",
    title: "Time to five minutes",
    shortTitle: "Time to five minutes",
    summary: "Read and set analogue clocks to five minutes, including quarter past and quarter to, and know minutes in an hour.",
    prerequisites: ["y2-count-in-2-3-5-10"],
    statutoryOutcomes: [
      "Compare and sequence intervals of time",
      "Tell and write the time to five minutes, including quarter past/to the hour and draw the hands on a clock face to show these times",
      "Know the number of minutes in an hour and the number of hours in a day",
    ],
    readyToProgress: [],
    whyThisMatters: "Year 1 stopped at o’clock and half past. Year 2 walks the minute hand in 5s and names quarter past and quarter to.",
    inPlainEnglish: "Each number the minute hand points to is 5 minutes. Minute hand on 4 is 20 minutes past. Quarter past is 15 minutes (hand on 3). Quarter to is 15 minutes before the next hour (hand on 9). 60 minutes make an hour; 24 hours make a day.",
    howSchoolTeachesIt: "School uses geared clocks so both hands move together. They count in 5s around the clock, then language: past, then to. They draw hands on blank faces.",
    sayThis: [
      "Where is the minute hand pointing? Count in 5s.",
      "Is this past the hour, or to the next hour?",
      "Quarter past — which number is the minute hand on?",
    ],
    avoidThis: [
      "Digital-only reading before analogue 5-minute marks are steady.",
      "Saying ‘the little hand doesn’t matter’ — it also creeps as minutes pass.",
    ],
    misconceptions: [
      {
        misconception: "They read 4:20 as 4:04 because the minute hand is on 4.",
        why: "They counted the number as minutes, not 5-minute chunks.",
        instead: "Each number the minute hand points to is 5 minutes. 4 means 20 minutes.",
      },
      {
        misconception: "They think quarter to 3 is 3:15, mixing past and to.",
        why: "Quarter is 15 minutes, but to looks at the next hour.",
        instead: "Quarter to 3 is 15 minutes before 3: 2:45, minute hand on 9.",
      },
    ],
    youAreReadyWhen: "You can read times such as 20 past, quarter past and quarter to, and you know 60 minutes make an hour.",
    householdItems: [
      "An analogue clock or a homemade clock from a paper plate with two card hands",
      "Optional: a phone timer",
    ],
    setup: "Make or fetch a clock face. Mark 12, 3, 6, 9 first, then the other numbers.",
    activityTitle: "Count in 5s, set past and to",
    steps: [
      "Count 5, 10, 15… 60 around the clock. That is one hour of minutes.",
      "Set 4:00, then 4:20, then quarter past 4 (4:15).",
      "Set quarter to 5 (minute hand on 9, hour hand creeping toward 5).",
      "A programme lasts 15 minutes from 4:10. When does it end?",
    ],
    check: [
      {
        prompt: "Minute hand on 6, hour hand halfway past 2.",
        looksLike: "Half past 2, or 2:30.",
        notYet: "6:02.",
        nudge: "Minute hand on 6 is 30 minutes.",
      },
      {
        prompt: "How many minutes in an hour?",
        looksLike: "60.",
        notYet: "100 or 30.",
        nudge: "Sixty. Twelve lots of 5.",
      },
      {
        prompt: "Quarter to 3.",
        looksLike: "2:45, minute hand on 9.",
        notYet: "3:15 or 3:45.",
        nudge: "15 minutes before 3.",
      },
    ],
    stretch: "How many hours in a day? Talk through morning and night making 24.",
  }),
  ks1Year2Draft({
    id: "y2-2d-3d-properties",
    glossaryTerms: ["line-of-symmetry", "2d-shape", "3d-shape", "vertex", "half"],
    strand: "Geometry",
    title: "Properties of 2-D and 3-D shapes",
    shortTitle: "2-D and 3-D properties",
    summary: "Describe sides, vertices, edges, faces and a fold line that matches both halves, and spot 2-D faces on 3-D objects.",
    prerequisites: [],
    statutoryOutcomes: [
      "Identify and describe the properties of 2-D shapes, including the number of sides and line symmetry in a vertical line",
      "Identify and describe the properties of 3-D shapes, including the number of edges, vertices and faces",
      "Identify 2-D shapes on the surface of 3-D shapes",
      "Compare and sort common 2-D and 3-D shapes and everyday objects",
    ],
    readyToProgress: ["2G-1"],
    whyThisMatters: "Naming is not enough. School wants properties you can count: sides, corners, faces. A cuboid is not a cube just because it is boxy.",
    inPlainEnglish: "2-D is flat: triangles, pentagons, hexagons. Count sides and corners (vertices). A line of symmetry is a fold down the middle that matches. 3-D you can hold: faces, edges, vertices. A cylinder has a circle face.",
    howSchoolTeachesIt: "School sorts shapes, folds for symmetry, and feels boxes, tins and balls. They look at 3-D objects from odd angles so a square face is still a square.",
    sayThis: [
      "How many sides? How many corners?",
      "If I fold on this line, do the two halves match?",
      "What 2-D shape is this face of the box?",
    ],
    avoidThis: [
      "Only flashcard naming with no counting of properties.",
      "Calling every box a cube.",
    ],
    misconceptions: [
      {
        misconception: "They call a cuboid a cube because it is boxy.",
        why: "Cube needs square faces. A cereal box is usually a cuboid.",
        instead: "Compare a face’s sides. If they are not all equal, it is not a cube.",
      },
      {
        misconception: "They think a square on its corner is a different shape.",
        why: "Orientation fooled them.",
        instead: "Turn it. Count sides. Still four equal sides and square corners.",
      },
    ],
    youAreReadyWhen: "You can describe a 2-D shape by sides and a fold down the middle, and a 3-D object by faces and edges, including a 2-D face you can see.",
    householdItems: [
      "Scrap paper to fold",
      "A cereal box, a tin, a ball",
      "A few flat shapes drawn or cut: triangle, rectangle, pentagon",
    ],
    setup: "Gather one box, one tin, one ball. Paper for folding a rectangle and an irregular blob.",
    activityTitle: "Fold, count, then feel the box",
    steps: [
      "Count sides and corners on a rectangle and a pentagon.",
      "Fold the rectangle in half down the middle. Do the halves match? Try a scribbled blob that will not match.",
      "Feel the cereal box. Count faces, edges, corners. Name a face (rectangle).",
      "Compare the tin (circles) and the ball (curved all round).",
    ],
    check: [
      {
        prompt: "How many faces on a typical cereal box?",
        looksLike: "6.",
        notYet: "4 or 8.",
        nudge: "Four sides, top and bottom.",
      },
      {
        prompt: "A pentagon — sides?",
        looksLike: "5.",
        notYet: "4 or 6.",
        nudge: "Penta means five. Count them.",
      },
      {
        prompt: "What 2-D shape is the end of a typical tin?",
        looksLike: "A circle.",
        notYet: "A cylinder.",
        nudge: "The face is a circle; the solid is a cylinder.",
      },
    ],
    stretch: "Sort a mixed pile into 2-D / 3-D, then into ‘has a square face’ / ‘does not’.",
  }),
  ks1Year2Draft({
    id: "y2-turns-and-right-angles",
    glossaryTerms: ["right-angle", "quarter", "half"],
    strand: "Geometry",
    title: "Turns, patterns and right angles",
    shortTitle: "Turns and right angles",
    summary: "Describe quarter, half and three-quarter turns, clockwise and anti-clockwise, and arrange objects in a repeating pattern.",
    prerequisites: ["y2-2d-3d-properties"],
    statutoryOutcomes: [
      "Order and arrange combinations of mathematical objects in patterns and sequences",
      "Use mathematical vocabulary to describe position, direction and movement, including movement in a straight line and distinguishing between rotation as a turn and in terms of right angles for quarter, half and three-quarter turns (clockwise and anti-clockwise)",
    ],
    readyToProgress: [],
    whyThisMatters: "Year 3 will name right angles on shapes. Year 2 meets them as turns: a quarter-turn on the spot is a square corner’s worth of rotate.",
    inPlainEnglish: "A quarter-turn is a right angle — a square corner of turn. Two quarter-turns make a half-turn. Clockwise is the way clock hands move; anti-clockwise is the other way. Patterns repeat in a sequence you can continue.",
    howSchoolTeachesIt: "School stands children up to turn, uses a toy or arrow, and links the turn to a right-angle tester. They also continue shape patterns (triangle, square, triangle, square…).",
    sayThis: [
      "Turn a quarter-turn clockwise. Where do you face now?",
      "Is that a quarter, half, or three-quarters?",
      "What comes next in this pattern? How do you know?",
    ],
    avoidThis: [
      "Protractors and degrees.",
      "Saying left/right only, with no clockwise language.",
    ],
    misconceptions: [
      {
        misconception: "They think a quarter-turn depends on how big they step.",
        why: "Turn is rotation, not walking a long path.",
        instead: "Keep the feet on one spot. Face a window, then a quarter-turn to a wall.",
      },
      {
        misconception: "They continue a pattern by size (‘getting bigger’) instead of by the repeating unit.",
        why: "Sequence looked like growth.",
        instead: "Clap the unit: triangle, square — then it starts again.",
      },
    ],
    youAreReadyWhen: "You can make a quarter-turn and a half-turn both ways, and continue a simple repeating pattern.",
    householdItems: [
      "A person or toy willing to turn on the spot",
      "A book with square corners as a right-angle tester",
      "A few different objects or paper shapes for a pattern",
    ],
    setup: "Stand facing a window. Have four landmarks: window, wall, door, other wall if you can.",
    activityTitle: "Quarter-turns, then a pattern",
    steps: [
      "Face the window. One quarter-turn clockwise. Name the new facing. Check with the book’s corner at your feet if that helps.",
      "Two quarter-turns: half-turn. Four: back to the window.",
      "Try one quarter-turn anti-clockwise. Different facing.",
      "Make a repeating pattern with three objects and continue it.",
    ],
    check: [
      {
        prompt: "How many quarter-turns in a half-turn?",
        looksLike: "2.",
        notYet: "4 or 1.",
        nudge: "Two quarters make a half.",
      },
      {
        prompt: "Minute hand from 12 to 3 — what turn?",
        looksLike: "A quarter-turn clockwise.",
        notYet: "A half-turn.",
        nudge: "12 to 3 is a quarter of the clock.",
      },
      {
        prompt: "Pattern red, blue, red, blue… next two?",
        looksLike: "Red, blue.",
        notYet: "Green, or red, red.",
        nudge: "The unit is red, blue.",
      },
    ],
    stretch: "Three-quarter turn from the window. Where do you face? Check by doing three quarters, or one quarter the other way.",
  }),
  ks1Year2Draft({
    id: "y2-pictograms-and-tables",
    glossaryTerms: ["pictogram", "half"],
    strand: "Statistics",
    title: "Pictograms, tallies, blocks and tables",
    shortTitle: "Pictograms and tables",
    summary: "Build and read a pictogram, tally chart, block diagram and table, including totalling and comparing.",
    prerequisites: ["y2-count-in-2-3-5-10"],
    statutoryOutcomes: [
      "Interpret and construct simple pictograms, tally charts, block diagrams and simple tables",
      "Ask and answer simple questions by counting the number of objects in each category and sorting the categories by quantity",
      "Ask and answer questions about totalling and comparing categorical data",
    ],
    readyToProgress: [],
    whyThisMatters: "A picture might mean 2, not 1. Missing the key is the classic mix-up. Comparing categories is a ‘how many more’ story with data.",
    inPlainEnglish: "A tally is five-bar gates. A pictogram uses pictures; always read the key. A block diagram stacks one block per item (or per 2). A table is a grid of numbers. Then ask: how many altogether? How many more… than…?",
    howSchoolTeachesIt: "School collects class votes, builds a tally, then a pictogram with a key of 1 or 2, then a block diagram. They ask one-step then compare questions.",
    sayThis: [
      "What does one picture stand for?",
      "How many altogether in these two groups?",
      "How many more chose… than…?",
    ],
    avoidThis: [
      "Skipping the key.",
      "Always using a picture-means-1 key, which hides the Year 2 skill.",
    ],
    misconceptions: [
      {
        misconception: "They count pictures as 1 when the key says 2.",
        why: "They ignored the key.",
        instead: "Finger the key first: one smiley = 2 children.",
      },
      {
        misconception: "They add every number in the table when the question asked for a difference.",
        why: "More / fewer is a subtract.",
        instead: "Find the two numbers, then find the gap.",
      },
    ],
    youAreReadyWhen: "You can read a pictogram key of 2, complete a tally, and answer a ‘how many more’ question from a table.",
    householdItems: [
      "Paper",
      "A handful of fruit, toys, or socks to sort into 3 categories",
      "Coloured pens",
    ],
    setup: "Sort 12–16 items into three groups, such as colours of socks. Tonight the pictogram key will be 2.",
    activityTitle: "Tally, then a scale-2 pictogram",
    steps: [
      "Tally each group. Gate every fifth mark.",
      "Write a table: type | number.",
      "Draw a pictogram where one smiley means 2 items. Use a half-symbol if you have an odd number.",
      "Ask: how many more in the biggest group than the smallest? How many altogether?",
    ],
    check: [
      {
        prompt: "If one picture means 2, what do 3 pictures mean?",
        looksLike: "6.",
        notYet: "3.",
        nudge: "Three lots of 2.",
      },
      {
        prompt: "Tally for 7.",
        looksLike: "One gate of 5 and two extra marks.",
        notYet: "Seven separate sticks with no gate, or a gate of 7.",
        nudge: "Fifth mark is the cross-through.",
      },
      {
        prompt: "Table: cats 8, dogs 5. How many more cats?",
        looksLike: "3.",
        notYet: "13.",
        nudge: "The gap is 3.",
      },
    ],
    stretch: "How many chose cat or dog altogether, then how many more that is than the third group.",
  }),
];
