import { ks2MathsDraft } from "@/content/england/ks2/draft";
import type { Topic } from "@/content/schema";

export const year6MathsTopics: Topic[] = [
  ks2MathsDraft({
    id: "y6-numbers-to-10-million",
    glossaryTerms: ["place-value", "partition", "decimal"],
    year: 6,
    strand: "Number and place value",
    title: "Numbers to 10 million",
    shortTitle: "To 10,000,000",
    summary: "Read, write, order and compare numbers up to 10,000,000 and say the value of each digit.",
    prerequisites: [],
    statutoryOutcomes: [
      "Read, write, order and compare numbers up to 10,000,000 and determine the value of each digit",
    ],
    readyToProgress: ["6NPV-1", "6NPV-2"],
    whyThisMatters: "SAT-style place-value questions still trip children who can ‘say the number’ but not the worth of a digit in 4,050,307.0 with decimals later.",
    inPlainEnglish: "10 million is 10,000,000. Group digits in threes: 10 000 000. In 8,040,216 the 4 is forty thousand.",
    howSchoolTeachesIt: "Charts to ten millions, grouping, and composing with non-standard partitions (80 hundred thousands, and so on).",
    sayThis: [
      "Read 8,040,216 in groups of three.",
      "What is the 4 worth?",
      "Which is greater, 9,999,999 or 10,000,000?",
    ],
    avoidThis: [
      "Dropping zeros in the middle.",
      "Mixing millions and thousands names.",
    ],
    misconceptions: [
      {
        misconception: "8 million 40 thousand as 8,000,040.",
        why: "Forty vs forty thousand.",
        instead: "40 thousand is 040 in the thousands group: 8,040,000.",
      },
      {
        misconception: "They think 10 million has 10 digits starting with 10 and seven zeros glued wrongly (100,000,000).",
        why: "Counting zeros.",
        instead: "10,000,000 has 7 zeros after 1? 1 and 7 zeros is 10 million. Yes 10,000,000.",
      },
    ],
    youAreReadyWhen: "You can write 8 million 40 thousand 216 in digits and order three 7-digit numbers.",
    householdItems: [
      "Place-value chart to 10 millions",
      "Digit scraps",
    ],
    setup: "Write 8,040,216.",
    activityTitle: "Group, name, order",
    steps: [
      "Name each digit.",
      "Write 8,040,216 with spaces.",
      "Order 2,009,000; 2,090,000; 1,999,999.",
      "Partition 8,040,216 as 8 millions + 40 thousands + 216.",
    ],
    check: [
      {
        prompt: "4 in 8,040,216.",
        looksLike: "40,000.",
        notYet: "4,000 or 4 million.",
        nudge: "Ten-thousands? 8,040,216 → 4 is ten thousands: 40,000.",
      },
      {
        prompt: "10 million in digits.",
        looksLike: "10,000,000.",
        notYet: "1,000,000 or 100,000,000.",
        nudge: "1 and 7 zeros.",
      },
      {
        prompt: "Smallest: 2,009,000; 1,999,999; 2,090,000.",
        looksLike: "1,999,999.",
        notYet: "2,009,000.",
        nudge: "Still under 2 million.",
      },
    ],
    stretch: "How many millions in 10,000,000?",
  }),
  ks2MathsDraft({
    id: "y6-rounding-and-negatives",
    glossaryTerms: ["negative-number", "multiple", "number-line", "rounding", "numeral"],
    year: 6,
    strand: "Number and place value",
    title: "Rounding to any degree of accuracy, and intervals across zero",
    shortTitle: "Rounding and negatives",
    summary: "Round any whole number as asked, and find the gap between a positive and a negative number in context.",
    prerequisites: ["y6-numbers-to-10-million"],
    statutoryOutcomes: [
      "Round any whole number to a required degree of accuracy",
      "Use negative numbers in context, and calculate intervals across 0",
    ],
    readyToProgress: ["6NPV-3"],
    whyThisMatters: "‘Nearest 20’ or ‘nearest 50’ appears. Intervals across 0 (4 °C to −7 °C) are a hop-count, not 4−7=−3 as the distance.",
    inPlainEnglish: "Degree of accuracy means which multiple you round to: 10, 20, 50, 1,000… From −7 to 4 the interval is 11. Count: 7 down to 0, then 4 up.",
    howSchoolTeachesIt: "Number lines, including negatives. They round to 20 and 50 as well as powers of 10. Distance across 0 is the sum of the distances to 0.",
    sayThis: [
      "Round 347 to the nearest 50.",
      "How many degrees from −7 to 4?",
      "Why is the gap not 3?",
    ],
    avoidThis: [
      "Using 4 − 7 = −3 as the length of the interval.",
      "Rounding to 50 by only looking at the last digit 7.",
    ],
    misconceptions: [
      {
        misconception: "Interval from −7 to 4 as 3 or −3.",
        why: "They subtracted the numerals.",
        instead: "7 + 4 = 11 hops.",
      },
      {
        misconception: "347 to nearest 50 as 350 because nearest 10 was 350.",
        why: "Wrong multiple.",
        instead: "Multiples of 50: 300 and 350. Midpoint 325. 347 is nearer 350.",
      },
    ],
    youAreReadyWhen: "You can round to 50 and to 1,000, and find an interval that crosses 0.",
    householdItems: [
      "A line from −10 to 10",
      "A line from 300 to 400 marked 350",
    ],
    setup: "Two lines: temperature and rounding.",
    activityTitle: "Hops across 0, then nearest 50",
    steps: [
      "−7 to 4 hops.",
      "−3 to −8 (same side: 5).",
      "347 to nearest 50 and nearest 20.",
      "A bank story only if comfortable: overdrawn £30 to +£20 is £50 swing.",
    ],
    check: [
      {
        prompt: "Interval −5 to 9.",
        looksLike: "14.",
        notYet: "4.",
        nudge: "5+9.",
      },
      {
        prompt: "347 to nearest 50.",
        looksLike: "350.",
        notYet: "300 or 340.",
        nudge: "Past 325.",
      },
      {
        prompt: "Same-side interval −2 to −9.",
        looksLike: "7.",
        notYet: "11.",
        nudge: "Do not add to zero; both below.",
      },
    ],
    stretch: "Nearest 20: 347 → 340 (multiples 340, 360; midpoint 350; 347 below → 340).",
  }),
  ks2MathsDraft({
    id: "y6-long-multiplication",
    glossaryTerms: ["long-multiplication", "estimate", "decimal", "fluency", "inverse"],
    year: 6,
    strand: "Calculation",
    title: "Long multiplication of 4-digit by 2-digit",
    shortTitle: "Long multiplication",
    summary: "The formal long-multiplication method for up to 4 digits × 2 digits, with an estimate first.",
    prerequisites: ["y6-numbers-to-10-million"],
    statutoryOutcomes: [
      "Multiply multi-digit numbers up to 4 digits by a two-digit whole number using the formal written method of long multiplication",
    ],
    readyToProgress: ["6AS/MD-2"],
    whyThisMatters: "Fluency here unlocks decimals × whole numbers later. The tens row still needs a place-holder.",
    inPlainEnglish: "2,146 × 23 is 2,146×3 plus 2,146×20. Add those products. Estimate 2,000×20=40,000.",
    howSchoolTeachesIt: "Grid then compact. They keep an estimate and an inverse (divide) if division is already there.",
    sayThis: [
      "Estimate first.",
      "Ones row, then tens row with a 0.",
      "Does 49,000-ish fit 2,146×23?",
    ],
    avoidThis: [
      "Skipping the tens zero.",
      "Estimating after you already believe a wild answer.",
    ],
    misconceptions: [
      {
        misconception: "They multiply 2,146×2 instead of ×20 for the tens.",
        why: "Forgot the place.",
        instead: "×2 tens = ×20.",
      },
      {
        misconception: "They add the two rows with columns misaligned.",
        why: "The 0 in ones on the second row is doing a job.",
        instead: "Line ones under ones.",
      },
    ],
    youAreReadyWhen: "You can complete 2,146 × 23 (or a similar 4-by-2) and compare it to an estimate.",
    householdItems: [
      "Paper",
      "Calculator only to check at the end if you want — not during",
    ],
    setup: "Estimate 2,146 × 23 ≈ 2,000 × 25 = 50,000 or 2,000 × 20 = 40,000.",
    activityTitle: "Estimate, long multiply, compare",
    steps: [
      "Write 2,146 × 3.",
      "Write 2,146 × 20 with 0.",
      "Add.",
      "Compare to 40,000–50,000.",
    ],
    check: [
      {
        prompt: "Why 0 on the second row?",
        looksLike: "Multiplied by tens.",
        notYet: "Decoration.",
        nudge: "Place holder.",
      },
      {
        prompt: "Rough size of 2,146 × 23.",
        looksLike: "About 40–50 thousand.",
        notYet: "About 400.",
        nudge: "2,000×20.",
      },
      {
        prompt: "1,024 × 10.",
        looksLike: "10,240.",
        notYet: "1,0240 with a gap, or 10240 as 1,024×1.",
        nudge: "Digits shift one place.",
      },
    ],
    stretch: "1,024 × 16.",
  }),
  ks2MathsDraft({
    id: "y6-long-division",
    glossaryTerms: ["short-division", "long-division", "remainder", "multiple", "estimate", "rounding", "decimal"],
    year: 6,
    strand: "Calculation",
    title: "Long and short division by 2-digit numbers",
    shortTitle: "Long division",
    summary: "Divide 4-digit numbers by 2-digit numbers, interpreting remainders as r, fractions, or rounding for the story.",
    prerequisites: ["y6-long-multiplication"],
    statutoryOutcomes: [
      "Divide numbers up to 4 digits by a two-digit whole number using the formal written method of long division, and interpret remainders as whole number remainders, fractions, or by rounding, as appropriate for the context",
      "Divide numbers up to 4 digits by a two-digit number using the formal written method of short division where appropriate",
    ],
    readyToProgress: ["6AS/MD-2"],
    whyThisMatters: "This is a statutory written method. Remainders still follow the story: coaches, money, or exact leftover.",
    inPlainEnglish: "How many 15s in 432? Estimate 15×30=450, a little high, try 28. Long division writes those guesses. 432÷15=28 r 12, or 28 12/15=28 4/5.",
    howSchoolTeachesIt: "Chunking (subtract multiples) then compact long division. Short division when the divisor is friendly. Estimate every time.",
    sayThis: [
      "About how many 15s in 432?",
      "What is left? Can we take another 15?",
      "Does this story want a rounded-up coach?",
    ],
    avoidThis: [
      "A compact algorithm with no estimate and no remainder sentence.",
      "Always a decimal.",
    ],
    misconceptions: [
      {
        misconception: "They guess 15×20=300, subtract, then forget the 20 in the answer.",
        why: "Chunks not recorded.",
        instead: "Write the 20, then the next chunk, then add the 20s.",
      },
      {
        misconception: "Remainder 15 when dividing by 15.",
        why: "Another group was possible.",
        instead: "Remainder < divisor.",
      },
    ],
    youAreReadyWhen: "You can divide a 3-digit number by a 2-digit number with an estimate, and interpret the remainder in a sentence.",
    householdItems: [
      "Paper",
      "Optional: 45 objects ÷ 12 as a tiny physical start",
    ],
    setup: "Warm 45 ÷ 12 = 3 r 9. Then 432 ÷ 15 on paper.",
    activityTitle: "Estimate, chunks, remainder sentence",
    steps: [
      "15×30=450 too big. 15×20=300. Subtract from 432 → 132.",
      "15×8=120. Remainder 12.",
      "Answer 28 r 12. Fraction 12/15=4/5.",
      "Coaches of 15 for 432 people: 29 coaches.",
    ],
    check: [
      {
        prompt: "45 ÷ 12.",
        looksLike: "3 r 9.",
        notYet: "4 r 3 without checking 12×3.",
        nudge: "12×3=36, 9 left.",
      },
      {
        prompt: "Remainder when dividing by 15 can be at most…",
        looksLike: "14.",
        notYet: "15.",
        nudge: "15 would make another group.",
      },
      {
        prompt: "432 people, 15 per coach, everyone seated.",
        looksLike: "29 coaches.",
        notYet: "28.",
        nudge: "12 leftover people still need a coach.",
      },
    ],
    stretch: "Short division 672 ÷ 16 if the layout is one they know.",
  }),
  ks2MathsDraft({
    id: "y6-order-of-operations",
    glossaryTerms: ["order-of-operations"],
    year: 6,
    strand: "Calculation",
    title: "Order of operations",
    shortTitle: "Order of operations",
    summary: "Use brackets and the usual order so 2 + 1 × 3 is 5, not 9, unless the brackets say otherwise.",
    prerequisites: ["y6-long-multiplication"],
    statutoryOutcomes: [
      "Perform mental calculations, including with mixed operations and large numbers",
      "Use their knowledge of the order of operations to carry out calculations involving the 4 operations",
    ],
    readyToProgress: [],
    whyThisMatters: "Secondary maths assumes this. A wrong order is a wrong method in costume.",
    inPlainEnglish: "Do brackets first. Then multiply and divide (left to right). Then add and subtract (left to right). 2+1×3=5 because 1×3 happens before adding. (2+1)×3=9.",
    howSchoolTeachesIt: "Schools may say BODMAS, BIDMAS or PEMDAS — names for the same order: brackets, then multiply and divide left to right, then add and subtract left to right. They explore 2+1×3 vs (2+1)×3. Indices if they appear are later; Year 6 statutory is the four operations plus brackets.",
    sayThis: [
      "Are there brackets?",
      "Any multiply or divide before we add?",
      "What changes if I put brackets here?",
    ],
    avoidThis: [
      "Saying ‘always multiply first’ when a divide is to the left of a multiply — left to right at the same level.",
      "Teaching two minuses make a plus as BODMAS.",
    ],
    misconceptions: [
      {
        misconception: "2+1×3=9 because they go left to right with all four operations.",
        why: "Add felt first.",
        instead: "The × binds 1 and 3 first.",
      },
      {
        misconception: "They think BIDMAS means divide before multiply always.",
        why: "The B-I-D-M-A-S letters look ranked inside DM.",
        instead: "D and M are a pair, left to right.",
      },
    ],
    youAreReadyWhen: "You can evaluate 2+1×3 and (2+1)×3 and a mix such as 20−12÷3.",
    householdItems: [
      "Paper",
      "12 objects if you want 12÷3 visible",
    ],
    setup: "Write 2+1×3 and (2+1)×3.",
    activityTitle: "Two different 2, 1 and 3s",
    steps: [
      "Work 2+1×3=5.",
      "Work (2+1)×3=9.",
      "20−12÷3=16.",
      "20−(12÷3) same; (20−12)÷3=8/3 — show brackets matter.",
    ],
    check: [
      {
        prompt: "2 + 1 × 3.",
        looksLike: "5.",
        notYet: "9.",
        nudge: "Multiply first.",
      },
      {
        prompt: "(2 + 1) × 3.",
        looksLike: "9.",
        notYet: "5.",
        nudge: "Brackets first.",
      },
      {
        prompt: "20 − 12 ÷ 3.",
        looksLike: "16.",
        notYet: "8/3 or 2.66 or 8.",
        nudge: "Divide 12÷3 first, then 20−4.",
      },
    ],
    stretch: "3×4+5×2 without going left-to-right blindly: 12+10=22.",
  }),
  ks2MathsDraft({
    id: "y6-common-factors-and-multiples",
    glossaryTerms: ["lcm", "hcf", "common-factor", "multiple", "factor", "prime"],
    year: 6,
    strand: "Calculation",
    title: "Common factors, common multiples and primes",
    shortTitle: "Factors, multiples, primes",
    summary: "Find common factors and common multiples, and keep primes fluent — the toolkit for simplifying fractions.",
    prerequisites: ["y6-order-of-operations"],
    statutoryOutcomes: [
      "Identify common factors, common multiples and prime numbers",
    ],
    readyToProgress: [],
    whyThisMatters: "Lowest common multiple and highest common factor are how unlike fractions join. Year 6 names them in problems, not only in isolation.",
    inPlainEnglish: "Common factors of 12 and 18: 1,2,3,6 (highest 6). Common multiples of 4 and 6 include 12, 24… (lowest 12). Primes still have exactly two factors.",
    howSchoolTeachesIt: "Lists, Venn diagrams, prime factor trees if school uses them. Then apply to 4/12 = 1/3.",
    sayThis: [
      "Highest common factor of 12 and 18?",
      "First common multiple of 4 and 6?",
      "Is 51 prime?",
    ],
    avoidThis: [
      "LCM/HCF as only acronyms.",
      "Saying 9 is prime.",
    ],
    misconceptions: [
      {
        misconception: "They give 12 as HCF of 12 and 18 because 12 is a factor of 12.",
        why: "HCF must divide both.",
        instead: "12 does not divide 18. 6 does.",
      },
      {
        misconception: "They think 51 is prime.",
        why: "Odd and awkward.",
        instead: "3×17=51.",
      },
    ],
    youAreReadyWhen: "You can find HCF of 12 and 18, LCM of 4 and 6, and test a number such as 51.",
    householdItems: [
      "Paper for two factor rainbows and two multiple lists",
    ],
    setup: "Rainbows for 12 and 18. Lists 4,8,12,16… and 6,12,18…",
    activityTitle: "Rainbows and lists",
    steps: [
      "HCF from rainbow overlap.",
      "LCM from first shared multiple.",
      "Prime test 51.",
      "Simplify 12/18 using HCF 6.",
    ],
    check: [
      {
        prompt: "HCF of 12 and 18.",
        looksLike: "6.",
        notYet: "12 or 36.",
        nudge: "Biggest number in both rainbows.",
      },
      {
        prompt: "LCM of 4 and 6.",
        looksLike: "12.",
        notYet: "24 or 2.",
        nudge: "First shared multiple, not the product 24 unless needed.",
      },
      {
        prompt: "12/18 simplified.",
        looksLike: "2/3.",
        notYet: "6/9 only, or 1/2.",
        nudge: "Divide by 6.",
      },
    ],
    stretch: "LCM of 8 and 12 for adding 1/8 + 1/12 later.",
  }),
  ks2MathsDraft({
    id: "y6-simplify-and-compare-fractions",
    glossaryTerms: ["common-factor", "denominator", "multiple", "quarter", "factor", "hcf", "lcm"],
    year: 6,
    strand: "Fractions",
    title: "Simplify fractions and compare any two fractions",
    shortTitle: "Simplify and compare",
    summary: "Use common factors to simplify, and common multiples (or reasoning) to compare fractions, including those greater than 1.",
    prerequisites: ["y6-common-factors-and-multiples"],
    statutoryOutcomes: [
      "Use common factors to simplify fractions; use common multiples to express fractions in the same denomination",
      "Compare and order fractions, including fractions >1",
    ],
    readyToProgress: ["6F-1", "6F-2", "6F-3"],
    whyThisMatters: "Comparing 3/7 and 5/12 by ‘bigger denominator is smaller’ fails. Same-size pieces, or a number-line argument, is the honest way.",
    inPlainEnglish: "Simplify 8/12 by dividing by 4 → 2/3. To compare 3/7 and 5/12, convert to 84ths (7×12) or use another common denominator. 9/4 is 2 1/4, greater than 2.",
    howSchoolTeachesIt: "HCF simplify. LCM denominators. Sometimes ‘both compared to 1/2’ as reasoning without a huge LCM.",
    sayThis: [
      "What is the HCF of 8 and 12?",
      "Can we compare both to 1/2 first?",
      "9/4 compared with 2.",
    ],
    avoidThis: [
      "Cross-multiplying as an unexplained trick.",
      "Always 7×12=84 when a nicer compare exists.",
    ],
    misconceptions: [
      {
        misconception: "3/7 > 5/12 because 7<12 so pieces are bigger, ignoring how many pieces.",
        why: "Denominator-only compare.",
        instead: "3/7 is a bit less than 1/2; 5/12 is also a bit less — need a finer check.",
      },
      {
        misconception: "They ‘simplify’ 8/12 to 7/11 by subtracting 1.",
        why: "Not a common factor.",
        instead: "Divide both by 4.",
      },
    ],
    youAreReadyWhen: "You can simplify 8/12 and compare 3/4, 5/6 and 7/8, including one fraction >1.",
    householdItems: [
      "Paper",
      "Bars for quarters, sixths, eighths",
    ],
    setup: "Three bars.",
    activityTitle: "Simplify, then line up",
    steps: [
      "8/12 → 2/3.",
      "Compare 3/4 and 5/6 (twelfths: 9/12 vs 10/12).",
      "Place 9/4 on a line.",
      "Order 3/7 and 5/12 if energy — 36/84 vs 35/84, so 3/7 slightly larger.",
    ],
    check: [
      {
        prompt: "Simplify 9/12.",
        looksLike: "3/4.",
        notYet: "9/12 already, or 1/3.",
        nudge: "÷3.",
      },
      {
        prompt: "Larger: 3/4 or 5/6.",
        looksLike: "5/6.",
        notYet: "3/4.",
        nudge: "9/12 vs 10/12.",
      },
      {
        prompt: "9/4 vs 2.",
        looksLike: "9/4 is larger (2 1/4).",
        notYet: "2 is larger.",
        nudge: "8/4=2, 9/4 is one quarter more.",
      },
    ],
    stretch: "Reason: 3/8 vs 1/2 (3/8 < 4/8).",
  }),
  ks2MathsDraft({
    id: "y6-add-subtract-unlike-fractions",
    glossaryTerms: ["equivalent-fraction", "mixed-number", "denominator", "half", "third", "lcm"],
    year: 6,
    strand: "Fractions",
    title: "Add and subtract fractions with different denominators",
    shortTitle: "Unlike fractions",
    summary: "Convert to the same denominator, including mixed numbers, using equivalent fractions.",
    prerequisites: ["y6-simplify-and-compare-fractions"],
    statutoryOutcomes: [
      "Add and subtract fractions with different denominators and mixed numbers, using the concept of equivalent fractions",
    ],
    readyToProgress: [],
    whyThisMatters: "This is the KS2 end-point for fraction calculation with +/−. A wrong common denominator is a wrong method.",
    inPlainEnglish: "1/2 + 1/3 = 3/6 + 2/6 = 5/6. Mixed: 1 1/2 + 2/3: convert to 3/2 + 2/3 = 9/6 + 4/6 = 13/6 = 2 1/6, or add wholes then parts with conversion.",
    howSchoolTeachesIt: "Start with related denominators, then LCM. Bars still welcome. Mixed numbers converted or split.",
    sayThis: [
      "What denominator fits both?",
      "1/2 as sixths? 1/3 as sixths?",
      "Do we need to convert mixed numbers first?",
    ],
    avoidThis: [
      "Adding denominators.",
      "Butterfly cross-multiply without equivalence talk.",
    ],
    misconceptions: [
      {
        misconception: "1/2 + 1/3 = 2/5.",
        why: "Add tops and bottoms.",
        instead: "Same-size pieces.",
      },
      {
        misconception: "1 1/2 + 2/3 = 1 3/5.",
        why: "Added 1/2+2/3 wrongly as 3/5, kept the 1.",
        instead: "1/2+2/3 is 7/6, plus 1 is 13/6.",
      },
    ],
    youAreReadyWhen: "You can add 1/2 and 1/3, subtract 5/6 − 1/4, and one mixed example.",
    householdItems: [
      "Bars for halves, thirds, sixths",
    ],
    setup: "Sixth-bar ready.",
    activityTitle: "Make sixths, then mixed",
    steps: [
      "1/2+1/3=5/6.",
      "5/6−1/4 (twelfths: 10/12−3/12=7/12).",
      "1 1/2 + 2/3.",
      "Simplify if needed.",
    ],
    check: [
      {
        prompt: "1/2 + 1/5.",
        looksLike: "7/10.",
        notYet: "2/7.",
        nudge: "5/10+2/10.",
      },
      {
        prompt: "5/6 − 1/3.",
        looksLike: "1/2 or 3/6.",
        notYet: "4/3.",
        nudge: "1/3=2/6; 5/6−2/6=3/6.",
      },
      {
        prompt: "2 1/4 − 3/4.",
        looksLike: "1 1/2 or 6/4−3/4=3/4 wait: 2 1/4=9/4; 9/4−3/4=6/4=1 1/2.",
        notYet: "2, or 1 2/0.",
        nudge: "Convert or regroup 2 1/4 as 1 5/4, minus 3/4 = 1 2/4.",
      },
    ],
    stretch: "3/8 + 1/6 (24ths).",
  }),
  ks2MathsDraft({
    id: "y6-multiply-and-divide-fractions",
    glossaryTerms: ["denominator", "numerator", "quarter", "inverse", "third", "area", "half"],
    year: 6,
    strand: "Fractions",
    title: "Multiply fractions and divide a fraction by a whole number",
    shortTitle: "Multiply and divide fractions",
    summary: "Multiply simple pairs of proper fractions, and divide a proper fraction by a whole number, with pictures first.",
    prerequisites: ["y6-add-subtract-unlike-fractions"],
    statutoryOutcomes: [
      "Multiply simple pairs of proper fractions, writing the answer in its simplest form",
      "Divide proper fractions by whole numbers",
    ],
    readyToProgress: [],
    whyThisMatters: "1/4 × 1/2 as ‘a quarter of a half’ is 1/8, not 1/6. Division 1/3 ÷ 2 is half of a third, 1/6.",
    inPlainEnglish: "Of often means ×: a half of a quarter is 1/8. Shade 1/2 of a bar, then 1/4 of that. Dividing by 2 splits each piece in two: 1/3 ÷ 2 = 1/6. Compact: multiply numerators, multiply denominators; for ÷ whole, multiply the denominator (or × 1/whole).",
    howSchoolTeachesIt: "Area of a rectangle split both ways, then compact. They simplify. They do not yet require dividing a fraction by a fraction (KS3).",
    sayThis: [
      "A half of a quarter — draw it.",
      "1/3 split into 2 equal shares?",
      "Why is 1/4 × 1/2 not 2/6?",
    ],
    avoidThis: [
      "Keep-change-flip for ÷2 as the first image without a bar.",
      "KS3 ÷ fraction by fraction unless school already did.",
    ],
    misconceptions: [
      {
        misconception: "1/4 × 1/2 = 1/6 (add denominators) or 2/8 unsimplified only, stuck.",
        why: "Add or they won’t simplify.",
        instead: "1/8. Picture of a quartered half.",
      },
      {
        misconception: "1/3 ÷ 2 = 2/3.",
        why: "They × the top.",
        instead: "Splitting a third in two makes smaller pieces: sixths.",
      },
    ],
    youAreReadyWhen: "You can show 1/2 × 1/4 = 1/8 and 1/3 ÷ 2 = 1/6 on a bar, then write it.",
    householdItems: [
      "A rectangle bar",
      "Two colours",
    ],
    setup: "One rectangle. You will split it two ways.",
    activityTitle: "Half of a quarter, then split a third",
    steps: [
      "Shade 1/2, then 1/4 of the whole (or of the half) to see 1/8.",
      "1/3 bar split into 2: 1/6.",
      "Write 2/3 × 1/4 = 2/12 = 1/6.",
      "3/4 ÷ 3 = 1/4 (share three-quarters between 3).",
    ],
    check: [
      {
        prompt: "1/2 × 1/5.",
        looksLike: "1/10.",
        notYet: "1/7 or 2/10.",
        nudge: "Half of a fifth.",
      },
      {
        prompt: "1/4 ÷ 2.",
        looksLike: "1/8.",
        notYet: "2/4 or 1/2.",
        nudge: "Half of a quarter.",
      },
      {
        prompt: "Simplify 2/12.",
        looksLike: "1/6.",
        notYet: "2/6.",
        nudge: "÷2.",
      },
    ],
    stretch: "If 1/4 of a length is 36 cm, the whole is 144 cm — multiply by 4, inverse of fraction of.",
  }),
  ks2MathsDraft({
    id: "y6-decimals-and-percentages",
    glossaryTerms: ["short-division", "percentage", "place-value", "hundredths", "remainder", "decimal", "tenths"],
    year: 6,
    strand: "Fractions",
    title: "Decimal place value, calculating, and FDP equivalents",
    shortTitle: "Decimals and % equivalents",
    summary: "3 decimal places, multiply/divide by 10/100/1,000, multiply decimals by wholes, and recall fraction–decimal–percentage facts.",
    prerequisites: ["y6-multiply-and-divide-fractions"],
    statutoryOutcomes: [
      "Associate a fraction with division and calculate decimal fraction equivalents",
      "Identify the value of each digit in numbers given to 3 decimal places and multiply and divide numbers by 10, 100 and 1,000 giving answers up to 3 decimal places",
      "Multiply one-digit numbers with up to 2 decimal places by whole numbers",
      "Use written division methods in cases where the answer has up to 2 decimal places",
      "Recall and use equivalences between simple fractions, decimals and percentages, including in different contexts",
    ],
    readyToProgress: [],
    whyThisMatters: "3÷8=0.375 is fraction as division. Money × 3 and measures ÷ 10 live here. Equivalents must be recall, not a hunt every time.",
    inPlainEnglish: "3/8 means 3÷8 = 0.375. 1.27 × 3: 1×3 and 0.2×3 and 0.07×3. 0.375 = 37.5% is possible but 3/8 as a % is 37.5% — know 1/8=12.5% if school wants it, and the Y5 benchmarks solidly.",
    howSchoolTeachesIt: "Place-value multiply, short division for 3÷8, and a facts table of 1/2, 1/4, 1/5, 1/10, 1/8 maybe. Written division with 2 dp money.",
    sayThis: [
      "3/8 as a divide.",
      "1.27 × 3, splitting the places.",
      "1/5 as a decimal and a percent?",
    ],
    avoidThis: [
      "Recurring 1/3=0.33 as if exact. Say 0.333… or 1/3.",
      "Sliding the point with no size talk.",
    ],
    misconceptions: [
      {
        misconception: "1.27 × 3 = 1.81 (they did 7×3=21, wrote 1, forgot the extra tenth).",
        why: "Exchange through the point.",
        instead: "0.07×3=0.21; 0.2×3=0.6; plus 0.21=0.81; plus 3=3.81.",
      },
      {
        misconception: "3÷8=0.3 remainder 6, stopped.",
        why: "Remainders in decimal division continue with extra zeros.",
        instead: "Bring down 0 tenths, hundredths, thousandths: 0.375.",
      },
    ],
    youAreReadyWhen: "You can work 3÷8 to 3 dp, 1.27×3, and give 2/5 as 0.4 and 40%.",
    householdItems: [
      "Place-value chart with 3 dp",
      "Paper for 3÷8 bus stop",
    ],
    setup: "Chart and a bus stop for 8 | 3.000.",
    activityTitle: "Divide for a decimal, then ×",
    steps: [
      "3÷8=0.375.",
      "1.27×3 split.",
      "2/5=0.4=40%. 1/8=0.125 if they meet it.",
      "£4.50 ÷ 5 using 2 dp.",
    ],
    check: [
      {
        prompt: "2/5 as decimal and %.",
        looksLike: "0.4 and 40%.",
        notYet: "0.2 and 2%.",
        nudge: "2/5=4/10.",
      },
      {
        prompt: "1.5 × 4.",
        looksLike: "6.",
        notYet: "1.9 or 0.6.",
        nudge: "1×4 and 0.5×4.",
      },
      {
        prompt: "6 ÷ 1000.",
        looksLike: "0.006.",
        notYet: "0.06 or 6.",
        nudge: "6 thousandths.",
      },
    ],
    stretch: "0.375 as 375/1000 = 3/8 simplified.",
  }),
  ks2MathsDraft({
    id: "y6-percentages-of-amounts",
    glossaryTerms: ["percentage", "bar-model", "decimal", "tenths", "half"],
    year: 6,
    strand: "Ratio and proportion",
    title: "Percentages of amounts",
    shortTitle: "% of amounts",
    summary: "Find percentages of measures and quantities, including 15% of 360, using 10%, 5% and 1% building blocks.",
    prerequisites: ["y6-decimals-and-percentages"],
    statutoryOutcomes: [
      "Solve problems involving the calculation of percentages and the use of percentages for comparison",
    ],
    readyToProgress: [],
    whyThisMatters: "Sales, comparison questions, and SATs all ask 15% of. Building from 10% and 1% keeps the method school-like, not a calculator-only leap.",
    inPlainEnglish: "10% is a tenth. 5% is half of that. 1% is 1/100. 15% = 10% + 5%. 15% of 360: 10% is 36, 5% is 18, total 54.",
    howSchoolTeachesIt: "Bar models of 100%, then 10% chunks. Comparison: which is larger, 20% of 50 or 10% of 120?",
    sayThis: [
      "What is 10% of this?",
      "Half of that 10% is 5%.",
      "Do we need 1% as well?",
    ],
    avoidThis: [
      "Always ×0.15 as the first teaching if they have no 10% picture.",
      "Finding 15% of 360 as 15×360.",
    ],
    misconceptions: [
      {
        misconception: "15% of 360 = 15.",
        why: "They copied 15.",
        instead: "Of 360, not 15 things called percent.",
      },
      {
        misconception: "10% of 360 = 10 or 350.",
        why: "Minus 10 or a literal 10.",
        instead: "Tenth of 360 is 36.",
      },
    ],
    youAreReadyWhen: "You can find 10%, 5%, 1% and 15% of a friendly number, and compare two percentage amounts.",
    householdItems: [
      "A bar marked 100%",
      "360 as a story (360° or 360 points)",
    ],
    setup: "Bar of 360 as 100%.",
    activityTitle: "10%, 5%, 15%",
    steps: [
      "10% of 360=36.",
      "5%=18. 15%=54.",
      "1% of 360=3.6 if they are ready, or 1% of 200=2.",
      "Compare 20% of 50 (10) and 10% of 120 (12).",
    ],
    check: [
      {
        prompt: "10% of 80.",
        looksLike: "8.",
        notYet: "10 or 70.",
        nudge: "÷10.",
      },
      {
        prompt: "15% of 200.",
        looksLike: "30.",
        notYet: "15 or 215.",
        nudge: "20+10.",
      },
      {
        prompt: "Larger: 25% of 40 or 10% of 90?",
        looksLike: "25% of 40 is 10; 10% of 90 is 9; so 25% of 40.",
        notYet: "10% of 90 because 90 is bigger.",
        nudge: "Work both.",
      },
    ],
    stretch: "Increase 200 by 15% → 230. That is +15%, not 15% remaining.",
  }),
  ks2MathsDraft({
    id: "y6-ratio",
    glossaryTerms: ["percentage", "bar-model", "third", "ratio"],
    year: 6,
    strand: "Ratio and proportion",
    title: "Ratio as ‘for every’",
    shortTitle: "Ratio",
    summary: "Compare quantities with ‘for every’ and a:b, finding missing values with integer multiply and divide.",
    prerequisites: ["y6-percentages-of-amounts"],
    statutoryOutcomes: [
      "Solve problems involving the relative sizes of 2 quantities where missing values can be found by using integer multiplication and division facts",
    ],
    readyToProgress: ["6AS/MD-3"],
    whyThisMatters: "Ratio is not a third type of fraction exactly, but it uses the same multiplicative thinking. Mixing 2:3 with 2/3 is the classic collision.",
    inPlainEnglish: "2:3 squash means 2 parts cordial for every 3 parts water. For 4 parts cordial, water is 6. Total parts 5 in the 2:3 mix, so each part is the total divided by 5 when you know the whole.",
    howSchoolTeachesIt: "For every…, bar models in parts, recipes. Notation a:b. They keep ratio and fraction talk distinct: 2:3 is not ‘2/3 of the drink is cordial’ (that would be 2/5).",
    sayThis: [
      "For every 2 cordial, how much water?",
      "If we double the recipe, what happens to both?",
      "2:3 mix — what fraction is cordial?",
    ],
    avoidThis: [
      "Writing 2:3 = 2/3.",
      "Adding 2 and 3 then treating that as one of the amounts.",
    ],
    misconceptions: [
      {
        misconception: "2:3 cordial to water means 2/3 of the jug is cordial.",
        why: "Ratio parts vs fraction of the whole.",
        instead: "2 parts out of 2+3=5, so 2/5 cordial.",
      },
      {
        misconception: "They add the same to both instead of multiplying when scaling.",
        why: "Additive thinking.",
        instead: "Double both; don’t +2 and +2 to the ratio numbers as amounts unless parts are 1.",
      },
    ],
    youAreReadyWhen: "You can scale a 2:3 recipe and say what fraction of the mix is each part.",
    householdItems: [
      "Cordial or squash if you have it, or two colours of counters (2 red, 3 blue)",
      "Cups",
    ],
    setup: "2 red and 3 blue counters. That is one ‘batch’.",
    activityTitle: "Batches of 2:3",
    steps: [
      "Make one batch. Say 2:3.",
      "Make two batches: 4:6.",
      "If 10 counters in the same ratio, each part is 2, so 4 red 6 blue.",
      "Fraction red = 2/5.",
    ],
    check: [
      {
        prompt: "Double 2:3.",
        looksLike: "4:6 (or 2:3 still as simplest).",
        notYet: "4:5 or 3:4.",
        nudge: "Both parts ×2.",
      },
      {
        prompt: "In 2:3, fraction that is the first quantity.",
        looksLike: "2/5.",
        notYet: "2/3.",
        nudge: "Parts over total parts.",
      },
      {
        prompt: "Recipe 2 eggs for 3 cups flour. 6 eggs need…",
        looksLike: "9 cups flour.",
        notYet: "7 or 12.",
        nudge: "Eggs ×3, so flour ×3.",
      },
    ],
    stretch: "Share £20 in 2:3. Total 5 parts, each £4, so £8 and £12.",
  }),
  ks2MathsDraft({
    id: "y6-scale-factors",
    glossaryTerms: ["scale-factor", "factor", "ratio", "area"],
    year: 6,
    strand: "Ratio and proportion",
    title: "Scale factors and similar shapes",
    shortTitle: "Scale factors",
    summary: "Enlarge a shape by an integer scale factor and find a missing length when the scale factor is known.",
    prerequisites: ["y6-ratio"],
    statutoryOutcomes: [
      "Solve problems involving similar shapes where the scale factor is known or can be found",
    ],
    readyToProgress: [],
    whyThisMatters: "Maps, models and similar triangles in KS3. Tonight: every length × k, angles stay the same.",
    inPlainEnglish: "Scale factor 3 means every length is 3 times as long. A 2 cm side becomes 6 cm. Angles do not triple. Area would ×9, but Year 6 may only need lengths unless school goes there.",
    howSchoolTeachesIt: "Squared paper enlargements from a point, then similar rectangles. Find k by dividing matching sides.",
    sayThis: [
      "What happens to each length?",
      "Do the angles change?",
      "This side was 5 cm, now 20 cm — scale factor?",
    ],
    avoidThis: [
      "Tripling angles.",
      "Adding 3 cm to each side and calling it scale factor 3.",
    ],
    misconceptions: [
      {
        misconception: "They add the scale factor to each side.",
        why: "Additive again.",
        instead: "Multiply lengths.",
      },
      {
        misconception: "They enlarge one side and not the others.",
        why: "Not similar.",
        instead: "Every length × k.",
      },
    ],
    youAreReadyWhen: "You can enlarge a rectangle by 2 on squared paper and find k from two matching sides.",
    householdItems: [
      "Squared paper",
      "A 3-by-2 rectangle",
    ],
    setup: "Draw a 3 by 2 rectangle. Enlarge by 2 from a corner.",
    activityTitle: "Enlarge, then find k",
    steps: [
      "Every side ×2: 6 by 4. Check angles still 90.",
      "A triangle 3,4,5 enlarged by 3: 9,12,15.",
      "Matching sides 5 cm and 20 cm: k=4.",
      "If a map 1 cm to 3 km, 4 cm on the map is 12 km.",
    ],
    check: [
      {
        prompt: "Scale factor 3, side 7 cm.",
        looksLike: "21 cm.",
        notYet: "10 cm.",
        nudge: "×3.",
      },
      {
        prompt: "Sides 6 cm and 18 cm matching. k?",
        looksLike: "3.",
        notYet: "12 or 6.",
        nudge: "18÷6.",
      },
      {
        prompt: "Do 90° angles become 270°?",
        looksLike: "No.",
        notYet: "Yes.",
        nudge: "Lengths scale; angles stay.",
      },
    ],
    stretch: "Area of 3×2 is 6. Enlarged 6×4 area 24, which is 4 times — 2². Mention only if they notice.",
  }),
  ks2MathsDraft({
    id: "y6-unequal-sharing",
    glossaryTerms: ["multiple", "ratio"],
    year: 6,
    strand: "Ratio and proportion",
    title: "Unequal sharing and grouping",
    shortTitle: "Unequal sharing",
    summary: "Share using fractions and multiples: for every 1 of these, 3 of those; 3/5 of the class, and so on.",
    prerequisites: ["y6-ratio"],
    statutoryOutcomes: [
      "Solve problems involving unequal sharing and grouping using knowledge of fractions and multiples",
    ],
    readyToProgress: [],
    whyThisMatters: "This is the statutory wording that sits under ‘for every’ and fraction-of-a-group. It is how ratio meets 3/5 of 30.",
    inPlainEnglish: "3/5 of 30 children are boys: 5 equal groups of 6, three groups 18. ‘For every 2 boys, 3 girls’ in a class of 30 is 5 parts, 12 boys 18 girls.",
    howSchoolTeachesIt: "Bar of equal parts. They choose fraction-of or ratio-parts depending on the sentence.",
    sayThis: [
      "Is this a fraction of the whole, or for every?",
      "How many equal parts?",
      "3/5 of 30.",
    ],
    avoidThis: [
      "Always splitting 50-50.",
      "Using ratio 3:5 when the sentence said 3/5 of.",
    ],
    misconceptions: [
      {
        misconception: "3/5 of 30 as 3×5=15, leftover 15.",
        why: "They multiplied the digits of the fraction.",
        instead: "÷5 ×3.",
      },
      {
        misconception: "For every 2 boys 3 girls, 30 children → 2+3=5, then they assign 2 boys and 3 girls only, leftover 25.",
        why: "They didn’t scale the parts.",
        instead: "6 batches of the ratio.",
      },
    ],
    youAreReadyWhen: "You can solve a 3/5 of n and a for-every share of a total.",
    householdItems: [
      "30 counters",
      "5 plates",
    ],
    setup: "30 counters. 5 plates for fifths.",
    activityTitle: "Fifths, then for-every",
    steps: [
      "3/5 of 30=18.",
      "For every 2 red, 3 blue, 30 counters: 12 red 18 blue.",
      "A grouping: packs of 4 with 3 left over — 3 leftover from 19 is 4 packs r 3.",
      "Say which sentence was fraction-of vs ratio.",
    ],
    check: [
      {
        prompt: "2/5 of 40.",
        looksLike: "16.",
        notYet: "8 or 10.",
        nudge: "8 per fifth, two of them.",
      },
      {
        prompt: "For every 1 adult, 4 children. 20 people all children and adults in that ratio.",
        looksLike: "4 adults, 16 children.",
        notYet: "1 and 4.",
        nudge: "5 parts of 4.",
      },
      {
        prompt: "3/5 of the class are boys — is that 3:5 boys:girls?",
        looksLike: "No. 3:2 boys:girls if the rest are girls.",
        notYet: "Yes.",
        nudge: "3 parts boys, 2 parts girls.",
      },
    ],
    stretch: "A recipe ‘3 spoonfuls flour for every egg’, 4 eggs → 12 spoons.",
  }),
  ks2MathsDraft({
    id: "y6-simple-formulae",
    glossaryTerms: ["perimeter", "formula", "number-word", "inverse", "area", "half"],
    year: 6,
    strand: "Algebra",
    title: "Simple formulae",
    shortTitle: "Formulae",
    summary: "Use a formula such as p = 2(l + w) by substituting numbers, in maths and in familiar measure contexts.",
    prerequisites: [],
    statutoryOutcomes: [
      "Use simple formulae",
    ],
    readyToProgress: [],
    whyThisMatters: "Secondary algebra is this with more letters. Tonight: a letter stands for a number you can swap in, not a plus-shaped mystery.",
    inPlainEnglish: "A formula is a recipe with letters. Perimeter of a rectangle p = 2(l + w). If l=5 and w=3, p=16. The letter is a place-holder you swap a number into.",
    howSchoolTeachesIt: "Substitute into perimeter, area, even speed if they meet it. They write the formula in words as well as letters.",
    sayThis: [
      "What does this letter stand for tonight?",
      "Swap in 5 and 3. Brackets first.",
      "If p=16 and w=3, what is l?",
    ],
    avoidThis: [
      "Solving for two unknowns here — that is a later pack.",
      "Saying algebra is ‘just guess’.",
    ],
    misconceptions: [
      {
        misconception: "2(l+w) as 2l + w.",
        why: "They distribute only onto l.",
        instead: "2 times the whole sum.",
      },
      {
        misconception: "They add 2 to l+w instead of multiplying.",
        why: "The 2 stuck to the bracket looks like +2.",
        instead: "Two lots of (l+w).",
      },
    ],
    youAreReadyWhen: "You can use p=2(l+w) with given numbers, including finding a missing length when the perimeter is known.",
    householdItems: [
      "A book to measure l and w",
      "Paper",
    ],
    setup: "Measure a book in cm. Write p=2(l+w).",
    activityTitle: "Measure, substitute, inverse",
    steps: [
      "Measure l and w. Compute p. Check by adding four sides.",
      "Swap: if p=24 and w=4, find l.",
      "Write the same recipe in words: perimeter is two lots of length plus width.",
      "a+b=b+a with 4 and 7 as a swap-order formula.",
    ],
    check: [
      {
        prompt: "l=8, w=3, p=2(l+w).",
        looksLike: "22.",
        notYet: "13 or 16.",
        nudge: "2×11.",
      },
      {
        prompt: "p=20, w=4, l?",
        looksLike: "6.",
        notYet: "16 or 24.",
        nudge: "Half of 20 is 10, then take off the width.",
      },
      {
        prompt: "Does 2(l+w) equal 2l+2w for l=5, w=3?",
        looksLike: "Yes — both 16.",
        notYet: "They only distribute onto l.",
        nudge: "Two lots of the whole sum.",
      },
    ],
    stretch: "Area a=l×w with the same book. Different formula, different answer.",
  }),
  ks2MathsDraft({
    id: "y6-sequences-and-missing-numbers",
    glossaryTerms: ["formula", "number-word", "inverse"],
    year: 6,
    strand: "Algebra",
    title: "Sequences and missing-number sentences",
    shortTitle: "Sequences and missing numbers",
    summary: "Describe linear sequences, and write missing-number problems with a letter.",
    prerequisites: ["y6-simple-formulae"],
    statutoryOutcomes: [
      "Generate and describe linear number sequences",
      "Express missing number problems algebraically",
    ],
    readyToProgress: [],
    whyThisMatters: "Term-to-term rules (add 4) and position-to-term (4n) both appear. Missing numbers as x+7=20 is algebra, not a blank box only.",
    inPlainEnglish: "3, 7, 11, 15… add 4 each time. The 10th term: 3+9×4=39, or 4n−1. x+7=20 means x=13. 3x=12 means x=4.",
    howSchoolTeachesIt: "They describe in words, then sometimes 4n. Empty boxes become letters. One-step then two-step such as 2x+1=9.",
    sayThis: [
      "What do we add each time?",
      "What would the 5th term be?",
      "x+7=20 — what is x?",
    ],
    avoidThis: [
      "nth-term quadratic. Stay linear.",
      "Guess-and-check as the only method when inverse is ready.",
    ],
    misconceptions: [
      {
        misconception: "They add 4 to 3 to get the 10th term as 7, losing how many adds.",
        why: "One add is not nine adds.",
        instead: "From term 1 to 10 there are 9 jumps.",
      },
      {
        misconception: "2x+1=9 as x=8 (they subtracted 1 from 9 and ignored the 2).",
        why: "Did only one inverse.",
        instead: "Subtract 1 first (8), then divide by 2 (4).",
      },
    ],
    youAreReadyWhen: "You can continue a +4 sequence, find a near term, and solve x+7=20 and 2x=10.",
    householdItems: [
      "Paper",
      "A 0–40 line",
    ],
    setup: "Write 3, 7, 11, 15.",
    activityTitle: "Jumps, then a letter",
    steps: [
      "Next three terms.",
      "10th term via 9 jumps of 4.",
      "x+7=20. 2x=10.",
      "2x+1=9 with a bar: two equal x and a 1 make 9.",
    ],
    check: [
      {
        prompt: "Next term after 15 in +4 from 3.",
        looksLike: "19.",
        notYet: "16 or 18.",
        nudge: "Add 4.",
      },
      {
        prompt: "x − 8 = 5.",
        looksLike: "x=13.",
        notYet: "3.",
        nudge: "Inverse of −8 is +8.",
      },
      {
        prompt: "3x = 18.",
        looksLike: "x=6.",
        notYet: "15 or 21.",
        nudge: "Divide by 3.",
      },
    ],
    stretch: "4n−1 for n=1,2,3 matches 3,7,11 if they are ready.",
  }),
  ks2MathsDraft({
    id: "y6-two-unknowns",
    glossaryTerms: [],
    year: 6,
    strand: "Algebra",
    title: "Pairs of numbers for two unknowns",
    shortTitle: "Two unknowns",
    summary: "Find pairs that satisfy an equation with two unknowns, and list combinations systematically.",
    prerequisites: ["y6-sequences-and-missing-numbers"],
    statutoryOutcomes: [
      "Find pairs of numbers that satisfy an equation with 2 unknowns",
      "Enumerate possibilities of combinations of 2 variables",
    ],
    readyToProgress: ["6AS/MD-4"],
    whyThisMatters: "This is not solving a unique x. Many pairs can work: a+b=9 has (1,8), (2,7)… Constraints (whole numbers, a>b) cut the list.",
    inPlainEnglish: "x+y=9 with whole numbers greater than 0: list systematically. 2x+y=10 has different pairs. A menu: 2 ice creams and 3 toppings, how many combinations — that is enumerate.",
    howSchoolTeachesIt: "Tables of values, organised lists, sometimes a simple grid. They do not use simultaneous-equation elimination unless a teacher chooses to.",
    sayThis: [
      "Can more than one pair work?",
      "Let’s hold x=1, then x=2…",
      "Have we listed without repeats?",
    ],
    avoidThis: [
      "Saying there is always one answer.",
      "Random guessing with no table.",
    ],
    misconceptions: [
      {
        misconception: "They think x+y=9 has only 4+5 because that is a famous pair.",
        why: "One pair feels like the pair.",
        instead: "List in order.",
      },
      {
        misconception: "They mix ice-cream combinations with x+y=9 as if flavours add to 9.",
        why: "Different structures.",
        instead: "Combinations: each of these with each of those. Sums: two numbers adding to 9.",
      },
    ],
    youAreReadyWhen: "You can list whole-number pairs for x+y=7 and combinations for 3 tops × 2 sauces.",
    householdItems: [
      "Paper table",
      "3 spoons and 2 forks for combinations",
    ],
    setup: "Table with x from 1 up. x+y=7.",
    activityTitle: "A sum table and an outfit grid",
    steps: [
      "List pairs for x+y=7, positive wholes.",
      "2x+y=10, y whole ≥0, a few rows.",
      "3 spoons × 2 forks: 6 outfits.",
      "Say which task was a sum and which was each-with-each.",
    ],
    check: [
      {
        prompt: "Positive whole pairs for x+y=4.",
        looksLike: "(1,3),(2,2),(3,1) — and (4,0) if 0 allowed; say the rule.",
        notYet: "Only (2,2).",
        nudge: "Organise by x=1,2,3…",
      },
      {
        prompt: "2 hats, 3 coats, outfits.",
        looksLike: "6.",
        notYet: "5.",
        nudge: "2×3.",
      },
      {
        prompt: "Can two different pairs both satisfy x+y=9?",
        looksLike: "Yes.",
        notYet: "No.",
        nudge: "Many points on that line.",
      },
    ],
    stretch: "x and y positive, x+y=9, x>y: fewer pairs.",
  }),
  ks2MathsDraft({
    id: "y6-convert-measures",
    glossaryTerms: ["percentage", "place-value", "decimal", "ratio"],
    year: 6,
    strand: "Measurement",
    title: "Convert measures, including miles and kilometres",
    shortTitle: "Convert measures",
    summary: "Convert metric units with up to 3 dp, and convert between miles and kilometres using a given fact.",
    prerequisites: ["y6-decimals-and-percentages"],
    statutoryOutcomes: [
      "Solve problems involving the calculation and conversion of units of measure, using decimal notation up to 3 decimal places where appropriate",
      "Use, read, write and convert between standard units… using decimal notation to up to 3 decimal places",
      "Convert between miles and kilometres",
    ],
    readyToProgress: [],
    whyThisMatters: "5 miles ≈ 8 km is a statutory relationship. Graphs of miles against km appear in statistics too.",
    inPlainEnglish: "3.25 kg = 3,250 g. 4.5 km = 4,500 m. A common school fact: 5 miles ≈ 8 km, so 10 miles ≈ 16 km. Convert smaller to larger by dividing.",
    howSchoolTeachesIt: "Place value for metric. A conversion graph or 5–8 fact for miles. Sensible-answer checks.",
    sayThis: [
      "Bigger to smaller: multiply.",
      "5 miles to km, using 5≈8.",
      "3.25 kg in grams?",
    ],
    avoidThis: [
      "Using 1 mile = 1 km.",
      "3.25 kg = 3,250 kg.",
    ],
    misconceptions: [
      {
        misconception: "They ×10 for km to m (should ×1,000).",
        why: "Wrong power.",
        instead: "Kilo is 1,000.",
      },
      {
        misconception: "8 miles as 5 km (they inverted the 5:8 fact).",
        why: "Ratio upside down.",
        instead: "5 miles match 8 km, so miles are the smaller number in that pair.",
      },
    ],
    youAreReadyWhen: "You can convert 3.25 kg and 4.5 km, and convert 10 miles using 5 miles ≈ 8 km.",
    householdItems: [
      "Paper",
      "A 5-to-8 conversion note",
    ],
    setup: "Write 1 km=1,000 m, 1 kg=1,000 g, 5 miles≈8 km.",
    activityTitle: "Metric, then miles",
    steps: [
      "3.25 kg → g. 12 mm → cm → m.",
      "4.5 km in m.",
      "10 miles ≈ 16 km. 8 km ≈ 5 miles.",
      "A 2.5 litre bottle in ml.",
    ],
    check: [
      {
        prompt: "3.25 kg in g.",
        looksLike: "3,250 g.",
        notYet: "325 g.",
        nudge: "×1,000.",
      },
      {
        prompt: "10 miles in km (5≈8).",
        looksLike: "16 km.",
        notYet: "13 km or 50 km.",
        nudge: "Double 5 miles → double 8 km.",
      },
      {
        prompt: "500 m in km.",
        looksLike: "0.5 km.",
        notYet: "5 km or 0.05 km.",
        nudge: "÷1,000.",
      },
    ],
    stretch: "A conversion graph: 0 miles 0 km, 5 miles 8 km. Read 2.5 miles as 4 km.",
  }),
  ks2MathsDraft({
    id: "y6-area-triangles-parallelograms",
    glossaryTerms: ["perpendicular", "right-angle", "perimeter", "formula", "area", "half"],
    year: 6,
    strand: "Measurement",
    title: "Area of triangles and parallelograms, and same-area different-perimeter",
    shortTitle: "Area formulae",
    summary: "Use the formulae for the area of rectangles, triangles and parallelograms, and see that area and perimeter can tell different stories.",
    prerequisites: ["y6-simple-formulae"],
    statutoryOutcomes: [
      "Recognise that shapes with the same areas can have different perimeters and vice versa",
      "Recognise when it is possible to use formulae for area and volume of shapes",
      "Calculate the area of parallelograms and triangles",
    ],
    readyToProgress: [],
    whyThisMatters: "Triangle area 1/2 × base × height is a halved rectangle. Using a slanted side as height is the trap.",
    inPlainEnglish: "Triangle: half of the rectangle that has the same base and perpendicular height. Parallelogram: base × perpendicular height (not the slant). A 1×12 rectangle and a 3×4 rectangle both have area 12 and different perimeters.",
    howSchoolTeachesIt: "Dissection: two triangles make a parallelogram. They measure perpendicular height with a square-on drop.",
    sayThis: [
      "Where is the perpendicular height?",
      "Half of this rectangle?",
      "Can two shapes share an area but not a perimeter?",
    ],
    avoidThis: [
      "Using the slanted side as height.",
      "Always 1/2 × a × b × c for a triangle.",
    ],
    misconceptions: [
      {
        misconception: "They take two sides of the triangle and multiply, forgetting 1/2 or using a non-height.",
        why: "No perpendicular.",
        instead: "Drop a right-angle height to the base you chose.",
      },
      {
        misconception: "They think equal area means equal perimeter.",
        why: "The 1×12 vs 3×4 counterexample.",
        instead: "Build both.",
      },
    ],
    youAreReadyWhen: "You can find a triangle area with base and perpendicular height, a parallelogram area, and give two rectangles with area 12 and different perimeters.",
    householdItems: [
      "Squared paper",
      "A right-angle card",
    ],
    setup: "Draw a 6 by 4 rectangle. Draw a triangle with base 6 and height 4. Draw a skinny 1 by 12.",
    activityTitle: "Halve, slant, compare",
    steps: [
      "Rectangle 24. Triangle half of that 12 if it uses those base and height.",
      "Parallelogram: count squares or base×height.",
      "Perimeters of 3×4 and 1×12.",
      "Same perimeter 16, different areas: 7×1 vs 5×3 — optional.",
    ],
    check: [
      {
        prompt: "Triangle base 8, perpendicular height 5.",
        looksLike: "20.",
        notYet: "40 or 13.",
        nudge: "1/2×8×5.",
      },
      {
        prompt: "Parallelogram base 7, perpendicular height 3.",
        looksLike: "21.",
        notYet: "21 using the slant 4 if they pick 7×4.",
        nudge: "Perpendicular 3, not the slant.",
      },
      {
        prompt: "Area 12, 1 by 12 perimeter vs 3 by 4.",
        looksLike: "26 vs 14.",
        notYet: "Both 12.",
        nudge: "Walk the edges.",
      },
    ],
    stretch: "Compound: triangle on top of a rectangle.",
  }),
  ks2MathsDraft({
    id: "y6-volume-cuboids",
    glossaryTerms: ["estimate", "formula", "volume", "area"],
    year: 6,
    strand: "Measurement",
    title: "Volume of cubes and cuboids",
    shortTitle: "Volume of cuboids",
    summary: "Count cm³, then use length × width × height, and compare in cm³ and m³.",
    prerequisites: ["y6-area-triangles-parallelograms"],
    statutoryOutcomes: [
      "Calculate, estimate and compare volume of cubes and cuboids using standard units, including cubic centimetres (cm³) and cubic metres (m³)",
    ],
    readyToProgress: [],
    whyThisMatters: "The formula is layers of area. Mixing m³ and cm³ by 100 not 1,000,000 is a classic SAT error — keep conversions gentle.",
    inPlainEnglish: "A cuboid 4 cm by 3 cm by 2 cm is 2 layers of 12 cubes: 24 cm³. Volume = l×w×h. A metre cube is a lot of centimetre cubes (1,000,000), so we compare mostly within one unit tonight.",
    howSchoolTeachesIt: "Build, then formula. They estimate large spaces in m³ roughly (a room).",
    sayThis: [
      "How many in a layer? How many layers?",
      "Why cm³?",
      "A 2×2×2 cube vs a 2×2×3 cuboid.",
    ],
    avoidThis: [
      "Adding l+w+h.",
      "Converting m³ to cm³ as ×100.",
    ],
    misconceptions: [
      {
        misconception: "Volume 4×3×2 as 9 or 24 cm.",
        why: "Forgot the third number or the cube unit.",
        instead: "24 cm³.",
      },
      {
        misconception: "They count only visible cubes.",
        why: "Hollow looking drawings.",
        instead: "Layers.",
      },
    ],
    youAreReadyWhen: "You can compute l×w×h for a small cuboid and compare two cuboid volumes.",
    householdItems: [
      "24 cubes if possible",
      "Paper for 4×3×2",
    ],
    setup: "Build 4×3×2 or draw layers.",
    activityTitle: "Layers then formula",
    steps: [
      "Count 24. Write 4×3×2.",
      "A cube 3×3×3=27. Compare.",
      "Estimate a large box in cm³.",
      "Talk m³ as a room, without a conversion drill.",
    ],
    check: [
      {
        prompt: "5×2×3 volume.",
        looksLike: "30 cm³.",
        notYet: "10 or 30 cm.",
        nudge: "× three lengths.",
      },
      {
        prompt: "Which holds more: 2×2×5 or 3×3×2?",
        looksLike: "2×2×5=20 vs 18, so 2×2×5.",
        notYet: "3×3×2 because 3 is bigger.",
        nudge: "Multiply.",
      },
      {
        prompt: "A 1 cm cube volume.",
        looksLike: "1 cm³.",
        notYet: "1 cm.",
        nudge: "1×1×1.",
      },
    ],
    stretch: "A missing height: volume 60, base 5×4, height 3.",
  }),
  ks2MathsDraft({
    id: "y6-circles",
    glossaryTerms: ["circumference", "diameter", "estimate", "radius"],
    year: 6,
    strand: "Geometry",
    title: "Radius, diameter and circumference",
    shortTitle: "Circles",
    summary: "Name radius, diameter and circumference, and know the diameter is twice the radius.",
    prerequisites: [],
    statutoryOutcomes: [
      "Illustrate and name parts of circles, including radius, diameter and circumference and know that the diameter is twice the radius",
    ],
    readyToProgress: [],
    whyThisMatters: "π comes fully in KS3. Year 6 is the parts and d=2r. Some schools mention C≈3×d as a measure check.",
    inPlainEnglish: "Radius: centre to edge. Diameter: through the centre, edge to edge, twice the radius. Circumference: the distance around. d=2r.",
    howSchoolTeachesIt: "Drawing with a compass or a plate. String around for circumference. They may compare string to 3 diameters.",
    sayThis: [
      "Where is the centre?",
      "If r=4 cm, what is d?",
      "Around vs across?",
    ],
    avoidThis: [
      "Forcing π=22/7 calculations if school has not. A wrong π method is worse than no π.",
      "Calling radius the around.",
    ],
    misconceptions: [
      {
        misconception: "They think radius is the around because it sounds like ‘rail’ or ‘race around’.",
        why: "Words.",
        instead: "Radius is a spoke. Circumference is the rim.",
      },
      {
        misconception: "d=r² because of the little 2 in 2r they misread.",
        why: "Notation.",
        instead: "2×r, not r squared.",
      },
    ],
    youAreReadyWhen: "You can mark r, d and circumference on a plate, and use d=2r both ways.",
    householdItems: [
      "A plate or cup rim",
      "String",
      "A ruler",
    ],
    setup: "A circular object. Paper to draw r and d.",
    activityTitle: "Spoke, across, around",
    steps: [
      "Find a centre (estimate). Draw a radius. Draw a diameter.",
      "Measure r, predict d, measure d.",
      "String around: circumference. Compare to 3 diameters.",
      "Write d=2r with your numbers.",
    ],
    check: [
      {
        prompt: "r=6 cm, d?",
        looksLike: "12 cm.",
        notYet: "8 or 36.",
        nudge: "2×6.",
      },
      {
        prompt: "d=10, r?",
        looksLike: "5.",
        notYet: "20.",
        nudge: "Halve.",
      },
      {
        prompt: "Circumference is…",
        looksLike: "The distance around.",
        notYet: "The spoke.",
        nudge: "Rim.",
      },
    ],
    stretch: "If string is about 3 × d, that is a taste of π, not a precise calculation unless school asks.",
  }),
  ks2MathsDraft({
    id: "y6-missing-angles",
    glossaryTerms: [],
    year: 6,
    strand: "Geometry",
    title: "Missing angles, including vertically opposite",
    shortTitle: "Missing angles",
    summary: "Use angles at a point, on a line, in triangles and quadrilaterals, and vertically opposite angles, to find unknowns.",
    prerequisites: ["y6-circles"],
    statutoryOutcomes: [
      "Draw 2-D shapes using given dimensions and angles",
      "Compare and classify geometric shapes based on their properties and sizes and find unknown angles in any triangles, quadrilaterals, and regular polygons",
      "Recognise angles where they meet at a point, are on a straight line, or are vertically opposite, and find missing angles",
    ],
    readyToProgress: [],
    whyThisMatters: "This is geometry as calculation. Facts: 180° in a triangle, 360° in a quadrilateral, 360° at a point, 180° on a line, vertically opposite equal.",
    inPlainEnglish: "Vertically opposite: the two angles that look like a kiss of two lines crossing — they are equal. A triangle’s three angles add to 180°. Regular hexagon interior angles are equal; Year 6 may find one from a split into triangles.",
    howSchoolTeachesIt: "Fact box, then missing numbers. They draw with a protractor when asked. Nets of 3-D if time — optional tonight.",
    sayThis: [
      "Which fact fits: line, point, triangle, opposite?",
      "Do these two look vertically opposite?",
      "180 minus the two we know?",
    ],
    avoidThis: [
      "Guessing from the drawing’s look without a fact.",
      "Assuming a triangle is equilateral because it looks even.",
    ],
    misconceptions: [
      {
        misconception: "They add 90+90+90 in a triangle.",
        why: "They used rectangle facts on a triangle.",
        instead: "Triangles total 180, so three 90s cannot close.",
      },
      {
        misconception: "They think adjacent angles on a cross are equal, not the opposite ones.",
        why: "Wrong pair.",
        instead: "The equal pair do not share an arm; they sit back-to-back.",
      },
    ],
    youAreReadyWhen: "You can find a missing triangle angle, a missing angle on a line, and a vertically opposite angle.",
    householdItems: [
      "Paper",
      "Protractor if drawing",
      "Two sticks to make a cross",
    ],
    setup: "Draw a triangle 70°, 40°, missing. Draw a cross. Draw 125° on a straight line.",
    activityTitle: "Fact, then missing number",
    steps: [
      "Triangle missing 70°.",
      "Line missing 55° from 125°.",
      "Cross: if one angle 70°, opposite 70°, adjacent 110°.",
      "Regular pentagon talk only if they know the split — optional.",
    ],
    check: [
      {
        prompt: "Triangle 90° and 30°, third?",
        looksLike: "60°.",
        notYet: "120° or 270°.",
        nudge: "180−120.",
      },
      {
        prompt: "On a line, 70°, missing?",
        looksLike: "110°.",
        notYet: "290°.",
        nudge: "180−70.",
      },
      {
        prompt: "Vertically opposite to 65°.",
        looksLike: "65°.",
        notYet: "115°.",
        nudge: "The equal back-to-back angle.",
      },
    ],
    stretch: "Quadrilateral 90, 90, 80, missing 100 because 360−260.",
  }),
  ks2MathsDraft({
    id: "y6-four-quadrants",
    glossaryTerms: ["negative-number", "coordinate", "translation", "horizontal", "reflection", "rounding"],
    year: 6,
    strand: "Geometry",
    title: "Four quadrants, translation and reflection in the axes",
    shortTitle: "Four quadrants",
    summary: "Plot coordinates with negative numbers, translate, and reflect in the axes.",
    prerequisites: ["y6-rounding-and-negatives"],
    statutoryOutcomes: [
      "Describe positions on the full coordinate grid (all 4 quadrants)",
      "Draw and translate simple shapes on the coordinate plane, and reflect them in the axes",
    ],
    readyToProgress: ["6G-1"],
    whyThisMatters: "Negative coordinates reuse the through-zero line. (2,−3) is 2 right, 3 down. Reflection in the x-axis flips the sign of y.",
    inPlainEnglish: "Four quadrants: right-up is (+,+). Left-down is (−,−). Across first, then up/down. Translate: add to x and y (right and up positive). Reflect in y-axis: (2,3)→(−2,3).",
    howSchoolTeachesIt: "Equal scales, labelled axes through 0. They complete rectangles from three corners, including negatives. Algebraic hints: (a,b)→(a−2,b+3).",
    sayThis: [
      "Across first — is it negative?",
      "Down means the second number is negative.",
      "Reflect in the x-axis: what happens to y?",
    ],
    avoidThis: [
      "Drawing all four quadrants with unequal scales.",
      "Up first.",
    ],
    misconceptions: [
      {
        misconception: "They plot (−2,3) at (2,−3).",
        why: "Sign stuck to the wrong axis.",
        instead: "First number is across. Minus first number is left.",
      },
      {
        misconception: "They reflect in x-axis by changing x.",
        why: "Wrong axis.",
        instead: "x-axis is the horizontal mirror: y flips sign.",
      },
    ],
    youAreReadyWhen: "You can plot (2,−3) and (−4,1), translate a triangle, and reflect one point in an axis.",
    householdItems: [
      "Squared paper with axes −5 to 5 both ways",
    ],
    setup: "Draw four quadrants. Equal spaces. Label 0.",
    activityTitle: "Plot, slide, flip",
    steps: [
      "Plot (2,3),(2,−3),(−2,3).",
      "Translate (2,3) by 3 left 2 down → (−1,1).",
      "Reflect (2,3) in the y-axis → (−2,3).",
      "Complete a rectangle using a fourth point you predict.",
    ],
    check: [
      {
        prompt: "Plot (−4, 0).",
        looksLike: "On the x-axis, 4 left.",
        notYet: "4 down.",
        nudge: "y=0 is the across axis.",
      },
      {
        prompt: "(3,−2) reflected in the x-axis.",
        looksLike: "(3,2).",
        notYet: "(−3,−2).",
        nudge: "y sign flips.",
      },
      {
        prompt: "2 right 5 down from (0,0).",
        looksLike: "(2,−5).",
        notYet: "(−2,5) or (2,5).",
        nudge: "Down is negative y.",
      },
    ],
    stretch: "(a,b) to (a+3,b−1) as a translation described with letters.",
  }),
  ks2MathsDraft({
    id: "y6-pie-charts-and-mean",
    glossaryTerms: ["percentage", "pie-chart", "mean", "quarter", "formula", "half"],
    year: 6,
    strand: "Statistics",
    title: "Pie charts, line graphs and the mean",
    shortTitle: "Pie charts and mean",
    summary: "Read pie charts using fractions, percentages and angles; keep line graphs fluent; calculate the mean as a fair share.",
    prerequisites: [],
    statutoryOutcomes: [
      "Interpret and construct pie charts and line graphs and use these to solve problems",
      "Calculate and interpret the mean as an average",
    ],
    readyToProgress: [],
    whyThisMatters: "Mean is total shared equally, not ‘the middle number’ (that is median, later). A pie is a whole turn of 360° linked to 100% and to the data total.",
    inPlainEnglish: "Mean of 2, 5, 5, 8: add (20), divide by how many (4), mean 5. Pie: if a quarter of 24 children chose blue, that slice is 6 children and 90°.",
    howSchoolTeachesIt: "Fair share with objects, then the formula. Pie charts from simple fractions (1/2, 1/4, 1/3) before awkward angles. Line graphs from Y5 still used.",
    sayThis: [
      "Total, then share equally between how many numbers?",
      "This slice is a quarter of the pie — a quarter of the total children?",
      "Is the mean one of the numbers? It might not be.",
    ],
    avoidThis: [
      "Calling the mean the middle value.",
      "A pie with angles that do not sum to 360°.",
    ],
    misconceptions: [
      {
        misconception: "They take the middle of the list as the mean without sharing.",
        why: "Median leak, or the word average in everyday English.",
        instead: "Add, then divide by the count of numbers.",
      },
      {
        misconception: "They think a larger slice must be the larger % even on a 3-D tilted pie in a textbook photo.",
        why: "Perspective pies lie.",
        instead: "Read the key and labels, not the 3-D drawing.",
      },
    ],
    youAreReadyWhen: "You can find the mean of a small set, and read a pie chart slice that is a simple fraction of a known total.",
    householdItems: [
      "12 counters",
      "Paper circle split into 4",
      "A tiny data set: 2, 5, 5, 8",
    ],
    setup: "12 counters for mean-as-share. Circle in quarters for a pie of 12 children.",
    activityTitle: "Fair share, then a pie",
    steps: [
      "Share 2+5+5+8=20 into 4: mean 5.",
      "12 children, 1/4 chose red: 3 children, 90° slice.",
      "A line graph recap: difference between two times.",
      "When not to use the mean: one extreme 100 with 2,3,4 — mention as talk.",
    ],
    check: [
      {
        prompt: "Mean of 4, 6, 8.",
        looksLike: "6.",
        notYet: "5 or 18.",
        nudge: "18÷3.",
      },
      {
        prompt: "Pie: half of 40 children.",
        looksLike: "20 children, 180°.",
        notYet: "20° or 50%. wait 50% is correct too — 20 children and 180°.",
        nudge: "Half the whole.",
      },
      {
        prompt: "Mean of 2, 2, 2, 10.",
        looksLike: "4.",
        notYet: "2 because most are 2.",
        nudge: "16÷4=4. The 10 pulled it.",
      },
    ],
    stretch: "Construct a pie for 6, 6, 12 children (1/4, 1/4, 1/2).",
  }),
];
